ProgramNode(0...272)(
  ScopeNode(0...0)([]),
  StatementsNode(0...272)(
    [CaseNode(0...21)(
       SymbolNode(5...8)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...8)("hi"),
         nil,
         "hi"
       ),
       [WhenNode(9...17)(
          KEYWORD_WHEN(9...13)("when"),
          [SymbolNode(14...17)(
             SYMBOL_BEGIN(14...15)(":"),
             IDENTIFIER(15...17)("hi"),
             nil,
             "hi"
           )],
          nil
        )],
       nil,
       (0...4),
       (18...21)
     ),
     CaseNode(23...81)(
       TrueNode(28...32)(),
       [WhenNode(34...53)(
          KEYWORD_WHEN(34...38)("when"),
          [TrueNode(39...43)()],
          StatementsNode(45...53)(
            [CallNode(45...53)(
               nil,
               nil,
               IDENTIFIER(45...49)("puts"),
               nil,
               ArgumentsNode(50...53)(
                 [SymbolNode(50...53)(
                    SYMBOL_BEGIN(50...51)(":"),
                    IDENTIFIER(51...53)("hi"),
                    nil,
                    "hi"
                  )]
               ),
               nil,
               nil,
               "puts"
             )]
          )
        ),
        WhenNode(55...76)(
          KEYWORD_WHEN(55...59)("when"),
          [FalseNode(60...65)()],
          StatementsNode(67...76)(
            [CallNode(67...76)(
               nil,
               nil,
               IDENTIFIER(67...71)("puts"),
               nil,
               ArgumentsNode(72...76)(
                 [SymbolNode(72...76)(
                    SYMBOL_BEGIN(72...73)(":"),
                    IDENTIFIER(73...76)("bye"),
                    nil,
                    "bye"
                  )]
               ),
               nil,
               nil,
               "puts"
             )]
          )
        )],
       nil,
       (23...27),
       (78...81)
     ),
     CaseNode(83...103)(
       nil,
       [WhenNode(89...98)(
          KEYWORD_WHEN(89...93)("when"),
          [SplatNode(94...98)(
             USTAR(94...95)("*"),
             CallNode(95...98)(
               nil,
               nil,
               IDENTIFIER(95...98)("foo"),
               nil,
               nil,
               nil,
               nil,
               "foo"
             )
           )],
          nil
        )],
       nil,
       (83...87),
       (100...103)
     ),
     CaseNode(105...134)(
       SymbolNode(110...113)(
         SYMBOL_BEGIN(110...111)(":"),
         IDENTIFIER(111...113)("hi"),
         nil,
         "hi"
       ),
       [WhenNode(114...122)(
          KEYWORD_WHEN(114...118)("when"),
          [SymbolNode(119...122)(
             SYMBOL_BEGIN(119...120)(":"),
             IDENTIFIER(120...122)("hi"),
             nil,
             "hi"
           )],
          nil
        )],
       ElseNode(123...134)(
         KEYWORD_ELSE(123...127)("else"),
         StatementsNode(128...130)(
           [SymbolNode(128...130)(
              SYMBOL_BEGIN(128...129)(":"),
              IDENTIFIER(129...130)("b"),
              nil,
              "b"
            )]
         ),
         KEYWORD_END(131...134)("end")
       ),
       (105...109),
       (131...134)
     ),
     CaseNode(136...172)(
       CallNode(141...145)(
         nil,
         nil,
         IDENTIFIER(141...145)("this"),
         nil,
         nil,
         nil,
         nil,
         "this"
       ),
       [WhenNode(147...167)(
          KEYWORD_WHEN(147...151)("when"),
          [ConstantReadNode(152...158)(), ConstantReadNode(160...167)()],
          nil
        )],
       nil,
       (136...140),
       (169...172)
     ),
     CaseNode(174...198)(
       nil,
       [WhenNode(179...194)(
          KEYWORD_WHEN(179...183)("when"),
          [CallNode(184...194)(
             CallNode(184...187)(
               nil,
               nil,
               IDENTIFIER(184...187)("foo"),
               nil,
               nil,
               nil,
               nil,
               "foo"
             ),
             nil,
             EQUAL_EQUAL(188...190)("=="),
             nil,
             ArgumentsNode(191...194)(
               [CallNode(191...194)(
                  nil,
                  nil,
                  IDENTIFIER(191...194)("bar"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "bar"
                )]
             ),
             nil,
             nil,
             "=="
           )],
          nil
        )],
       nil,
       (174...178),
       (195...198)
     ),
     CaseNode(200...230)(
       nil,
       [WhenNode(205...211)(
          KEYWORD_WHEN(205...209)("when"),
          [CallNode(210...211)(
             nil,
             nil,
             IDENTIFIER(210...211)("a"),
             nil,
             nil,
             nil,
             nil,
             "a"
           )],
          nil
        )],
       ElseNode(212...230)(
         KEYWORD_ELSE(212...216)("else"),
         nil,
         KEYWORD_END(227...230)("end")
       ),
       (200...204),
       (227...230)
     ),
     CaseNode(232...272)(
       CallNode(237...241)(
         nil,
         nil,
         IDENTIFIER(237...241)("type"),
         nil,
         nil,
         nil,
         nil,
         "type"
       ),
       [WhenNode(246...253)(
          KEYWORD_WHEN(246...250)("when"),
          [SymbolNode(251...253)(
             SYMBOL_BEGIN(251...252)(":"),
             IDENTIFIER(252...253)("b"),
             nil,
             "b"
           )],
          StatementsNode(0...0)([])
        )],
       ElseNode(260...272)(
         KEYWORD_ELSE(260...264)("else"),
         StatementsNode(0...0)([]),
         KEYWORD_END(269...272)("end")
       ),
       (232...236),
       (269...272)
     )]
  )
)
