ProgramNode(0...120)(
  ScopeNode(0...0)([]),
  StatementsNode(0...120)(
    [HashNode(0...2)(BRACE_LEFT(0...1)("{"), [], BRACE_RIGHT(1...2)("}")),
     HashNode(4...7)(BRACE_LEFT(4...5)("{"), [], BRACE_RIGHT(6...7)("}")),
     HashNode(9...27)(
       BRACE_LEFT(9...10)("{"),
       [AssocNode(11...17)(
          CallNode(11...12)(
            nil,
            nil,
            IDENTIFIER(11...12)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          ),
          CallNode(16...17)(
            nil,
            nil,
            IDENTIFIER(16...17)("b"),
            nil,
            nil,
            nil,
            nil,
            "b"
          ),
          EQUAL_GREATER(13...15)("=>")
        ),
        AssocNode(19...25)(
          CallNode(19...20)(
            nil,
            nil,
            IDENTIFIER(19...20)("c"),
            nil,
            nil,
            nil,
            nil,
            "c"
          ),
          CallNode(24...25)(
            nil,
            nil,
            IDENTIFIER(24...25)("d"),
            nil,
            nil,
            nil,
            nil,
            "d"
          ),
          EQUAL_GREATER(21...23)("=>")
        )],
       BRACE_RIGHT(26...27)("}")
     ),
     HashNode(29...44)(
       BRACE_LEFT(29...30)("{"),
       [AssocNode(31...37)(
          CallNode(31...32)(
            nil,
            nil,
            IDENTIFIER(31...32)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          ),
          CallNode(36...37)(
            nil,
            nil,
            IDENTIFIER(36...37)("b"),
            nil,
            nil,
            nil,
            nil,
            "b"
          ),
          EQUAL_GREATER(33...35)("=>")
        ),
        AssocSplatNode(39...42)(
          CallNode(41...42)(
            nil,
            nil,
            IDENTIFIER(41...42)("c"),
            nil,
            nil,
            nil,
            nil,
            "c"
          ),
          (39...41)
        )],
       BRACE_RIGHT(43...44)("}")
     ),
     HashNode(46...79)(
       BRACE_LEFT(46...47)("{"),
       [AssocNode(54...58)(
          SymbolNode(54...56)(
            nil,
            LABEL(54...55)("a"),
            LABEL_END(55...56)(":"),
            "a"
          ),
          CallNode(57...58)(
            nil,
            nil,
            IDENTIFIER(57...58)("b"),
            nil,
            nil,
            nil,
            nil,
            "b"
          ),
          nil
        ),
        AssocNode(66...70)(
          SymbolNode(66...68)(
            nil,
            LABEL(66...67)("c"),
            LABEL_END(67...68)(":"),
            "c"
          ),
          CallNode(69...70)(
            nil,
            nil,
            IDENTIFIER(69...70)("d"),
            nil,
            nil,
            nil,
            nil,
            "d"
          ),
          nil
        )],
       BRACE_RIGHT(78...79)("}")
     ),
     HashNode(81...106)(
       BRACE_LEFT(81...82)("{"),
       [AssocNode(83...87)(
          SymbolNode(83...85)(
            nil,
            LABEL(83...84)("a"),
            LABEL_END(84...85)(":"),
            "a"
          ),
          CallNode(86...87)(
            nil,
            nil,
            IDENTIFIER(86...87)("b"),
            nil,
            nil,
            nil,
            nil,
            "b"
          ),
          nil
        ),
        AssocNode(89...93)(
          SymbolNode(89...91)(
            nil,
            LABEL(89...90)("c"),
            LABEL_END(90...91)(":"),
            "c"
          ),
          CallNode(92...93)(
            nil,
            nil,
            IDENTIFIER(92...93)("d"),
            nil,
            nil,
            nil,
            nil,
            "d"
          ),
          nil
        ),
        AssocSplatNode(95...98)(
          CallNode(97...98)(
            nil,
            nil,
            IDENTIFIER(97...98)("e"),
            nil,
            nil,
            nil,
            nil,
            "e"
          ),
          (95...97)
        ),
        AssocNode(100...104)(
          SymbolNode(100...102)(
            nil,
            LABEL(100...101)("f"),
            LABEL_END(101...102)(":"),
            "f"
          ),
          CallNode(103...104)(
            nil,
            nil,
            IDENTIFIER(103...104)("g"),
            nil,
            nil,
            nil,
            nil,
            "g"
          ),
          nil
        )],
       BRACE_RIGHT(105...106)("}")
     ),
     HashNode(108...120)(
       BRACE_LEFT(108...109)("{"),
       [AssocNode(110...118)(
          SymbolNode(110...114)(
            STRING_BEGIN(110...111)("\""),
            STRING_CONTENT(111...112)("a"),
            LABEL_END(112...114)("\":"),
            "a"
          ),
          CallNode(115...118)(
            CallNode(116...118)(
              nil,
              nil,
              IDENTIFIER(116...118)("b?"),
              nil,
              nil,
              nil,
              nil,
              "b?"
            ),
            nil,
            BANG(115...116)("!"),
            nil,
            nil,
            nil,
            nil,
            "!"
          ),
          nil
        )],
       BRACE_RIGHT(119...120)("}")
     )]
  )
)
