ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [InterpolatedStringNode(0...10)(
       HEREDOC_START(0...6)("<<-END"),
       [],
       HEREDOC_END(7...10)("END")
     )]
  )
)
