ProgramNode(0...48)(
  ScopeNode(0...0)([]),
  StatementsNode(0...48)(
    [LambdaNode(0...11)(
       ScopeNode(0...2)([IDENTIFIER(6...9)("foo")]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(2...11)(
         ParametersNode(6...9)(
           [RequiredParameterNode(6...9)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (2...3),
         (10...11)
       ),
       nil
     ),
     LambdaNode(16...30)(
       ScopeNode(16...18)([LABEL(19...20)("x")]),
       MINUS_GREATER(16...18)("->"),
       BlockParametersNode(18...30)(
         ParametersNode(19...29)(
           [],
           [],
           [],
           nil,
           [KeywordParameterNode(19...29)(
              LABEL(19...21)("x:"),
              InterpolatedStringNode(22...29)(
                STRING_BEGIN(22...23)("\""),
                [StringNode(23...24)(
                   nil,
                   STRING_CONTENT(23...24)("b"),
                   nil,
                   "b"
                 ),
                 StringInterpolatedNode(24...28)(
                   EMBEXPR_BEGIN(24...26)("\#{"),
                   StatementsNode(26...27)(
                     [CallNode(26...27)(
                        nil,
                        nil,
                        IDENTIFIER(26...27)("a"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "a"
                      )]
                   ),
                   EMBEXPR_END(27...28)("}")
                 )],
                STRING_END(28...29)("\"")
              )
            )],
           nil,
           nil
         ),
         [],
         (18...19),
         (29...30)
       ),
       nil
     ),
     LambdaNode(36...48)(
       ScopeNode(36...38)([LABEL(39...40)("a")]),
       MINUS_GREATER(36...38)("->"),
       BlockParametersNode(38...48)(
         ParametersNode(39...47)(
           [],
           [],
           [],
           nil,
           [KeywordParameterNode(39...47)(
              LABEL(39...41)("a:"),
              CallNode(42...47)(
                CallNode(42...43)(
                  nil,
                  nil,
                  IDENTIFIER(42...43)("b"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "b"
                ),
                nil,
                STAR(44...45)("*"),
                nil,
                ArgumentsNode(46...47)([IntegerNode(46...47)()]),
                nil,
                nil,
                "*"
              )
            )],
           nil,
           nil
         ),
         [],
         (38...39),
         (47...48)
       ),
       nil
     )]
  )
)
