ProgramNode(0...125)(
  ScopeNode(0...0)([]),
  StatementsNode(0...125)(
    [AndNode(0...19)(
       CallNode(0...7)(
         CallNode(4...7)(
           nil,
           nil,
           IDENTIFIER(4...7)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         nil,
         KEYWORD_NOT(0...3)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       CallNode(12...19)(
         CallNode(16...19)(
           nil,
           nil,
           IDENTIFIER(16...19)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         ),
         nil,
         KEYWORD_NOT(12...15)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       KEYWORD_AND(8...11)("and")
     ),
     CallNode(21...37)(
       AndNode(25...36)(
         CallNode(25...28)(
           nil,
           nil,
           IDENTIFIER(25...28)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         CallNode(33...36)(
           nil,
           nil,
           IDENTIFIER(33...36)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         ),
         KEYWORD_AND(29...32)("and")
       ),
       nil,
       KEYWORD_NOT(21...24)("not"),
       PARENTHESIS_LEFT(24...25)("("),
       nil,
       PARENTHESIS_RIGHT(36...37)(")"),
       nil,
       "!"
     ),
     CallNode(39...46)(
       CallNode(43...46)(
         nil,
         nil,
         IDENTIFIER(43...46)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       KEYWORD_NOT(39...42)("not"),
       nil,
       nil,
       nil,
       nil,
       "!"
     ),
     AndNode(48...69)(
       CallNode(48...55)(
         CallNode(52...55)(
           nil,
           nil,
           IDENTIFIER(52...55)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         nil,
         KEYWORD_NOT(48...51)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       CallNode(60...69)(
         CallNode(66...69)(
           nil,
           nil,
           IDENTIFIER(66...69)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         ),
         nil,
         KEYWORD_NOT(60...63)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       KEYWORD_AND(56...59)("and")
     ),
     AndNode(72...97)(
       CallNode(72...79)(
         CallNode(76...79)(
           nil,
           nil,
           IDENTIFIER(76...79)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         nil,
         KEYWORD_NOT(72...75)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       CallNode(88...97)(
         CallNode(94...97)(
           nil,
           nil,
           IDENTIFIER(94...97)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         ),
         nil,
         KEYWORD_NOT(88...91)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       KEYWORD_AND(80...83)("and")
     ),
     AndNode(100...125)(
       CallNode(100...107)(
         CallNode(104...107)(
           nil,
           nil,
           IDENTIFIER(104...107)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         nil,
         KEYWORD_NOT(100...103)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       CallNode(114...125)(
         CallNode(122...125)(
           nil,
           nil,
           IDENTIFIER(122...125)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         ),
         nil,
         KEYWORD_NOT(114...117)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       KEYWORD_AND(108...111)("and")
     )]
  )
)
