ProgramNode(0...40)(
  ScopeNode(0...0)([]),
  StatementsNode(0...40)(
    [ForwardingSuperNode(0...5)(nil),
     SuperNode(7...14)(
       KEYWORD_SUPER(7...12)("super"),
       PARENTHESIS_LEFT(12...13)("("),
       nil,
       PARENTHESIS_RIGHT(13...14)(")"),
       nil
     ),
     SuperNode(16...24)(
       KEYWORD_SUPER(16...21)("super"),
       PARENTHESIS_LEFT(21...22)("("),
       ArgumentsNode(22...23)([IntegerNode(22...23)()]),
       PARENTHESIS_RIGHT(23...24)(")"),
       nil
     ),
     SuperNode(26...40)(
       KEYWORD_SUPER(26...31)("super"),
       PARENTHESIS_LEFT(31...32)("("),
       ArgumentsNode(32...39)(
         [IntegerNode(32...33)(),
          IntegerNode(35...36)(),
          IntegerNode(38...39)()]
       ),
       PARENTHESIS_RIGHT(39...40)(")"),
       nil
     )]
  )
)
