ProgramNode(0...109)(
  ScopeNode(0...0)([]),
  StatementsNode(0...109)(
    [UntilNode(0...18)(
       KEYWORD_UNTIL(0...5)("until"),
       TrueNode(6...10)(),
       StatementsNode(12...13)([IntegerNode(12...13)()])
     ),
     UntilNode(20...32)(
       KEYWORD_UNTIL_MODIFIER(22...27)("until"),
       TrueNode(28...32)(),
       StatementsNode(20...21)([IntegerNode(20...21)()])
     ),
     UntilNode(34...50)(
       KEYWORD_UNTIL_MODIFIER(40...45)("until"),
       TrueNode(46...50)(),
       StatementsNode(34...39)([BreakNode(34...39)(nil, (34...39))])
     ),
     UntilNode(52...67)(
       KEYWORD_UNTIL_MODIFIER(57...62)("until"),
       TrueNode(63...67)(),
       StatementsNode(52...56)([NextNode(52...56)(nil, (52...56))])
     ),
     UntilNode(69...86)(
       KEYWORD_UNTIL_MODIFIER(76...81)("until"),
       TrueNode(82...86)(),
       StatementsNode(69...75)(
         [ReturnNode(69...75)(KEYWORD_RETURN(69...75)("return"), nil)]
       )
     ),
     UntilNode(88...109)(
       KEYWORD_UNTIL_MODIFIER(99...104)("until"),
       CallNode(105...109)(
         nil,
         nil,
         IDENTIFIER(105...109)("bar?"),
         nil,
         nil,
         nil,
         nil,
         "bar?"
       ),
       StatementsNode(88...98)(
         [CallNode(88...98)(
            nil,
            nil,
            IDENTIFIER(88...91)("foo"),
            nil,
            ArgumentsNode(92...98)(
              [SymbolNode(92...94)(
                 SYMBOL_BEGIN(92...93)(":"),
                 IDENTIFIER(93...94)("a"),
                 nil,
                 "a"
               ),
               SymbolNode(96...98)(
                 SYMBOL_BEGIN(96...97)(":"),
                 IDENTIFIER(97...98)("b"),
                 nil,
                 "b"
               )]
            ),
            nil,
            nil,
            "foo"
          )]
       )
     )]
  )
)
