# Prism::TestCompilePrism#test_repeated_proc_params../ruby/st.c:2621: Assertion Failed: set_rebuild_table_with:new_tab->num_entries == tab->num_entries
exclude(/^test_/, "FIXME: bug. Skip all tests for now")

exclude(/^test_GlobalVariable/, "global variables")
exclude(:test_ClassVariableTargetNode, "class variables")
exclude(:test_ClassVariableAndWriteNode, "class variables")
exclude(:test_ClassVariableOperatorWriteNode, "class variables")
exclude(:test_ClassVariableOrWriteNode, "class variables")
exclude(:test_ClassVariableWriteNode, "class variables")
exclude(:test_ConstantWriteNode, "global side  effects")
exclude(:test_InstanceVariableTargetNode, "class ivars")
exclude(:test_InstanceVariableReadNode, "class ivars")
exclude(:test_InstanceVariableWriteNode, "class ivars")
exclude(:test_EmbeddedVariableNode, "class ivars")
exclude(:test_InterpolatedMatchLastLineNode, "global variables")
exclude(:test_InterpolatedRegularExpressionNode, "global variables")
exclude(:test_InterpolatedStringNode, "global variables")
exclude(:test_InterpolatedSymbolNode, "global variables")
exclude(:test_AliasGlobalVariableNode, "global variables")
exclude(:test_ClassVariableReadNode, "class variables")
exclude(:test_ForNode_gvar, "gvars")
exclude(:test_PostExecutionNode_set_ivar, "set ivar of main")
exclude(:test_PinnedVariableNode_ractor_unsafe, "ractor incompatible")
exclude(:test_DefinedNode_ractor_unsafe, "ractor incompatible")
exclude(:test_ConstantPathOrWriteNode_ractor_unsafe, "ractor incompatible")
exclude(:test_ConstantPathOperatorWriteNode_ractor_unsafe, "ractor incompatible")
exclude(:test_IfNode_ractor_unsafe, "gvars")
