name: Setup ubuntu environment
description: >-
  At the beginning there was no way but to copy & paste `apt-get`
  everywhere.  But now that we have composite actions, it seems better
  merge them into one.

inputs:
  arch:
    required: false
    default: ''
    description: >-
      Architecture.  Because we run this on a GitHub-hosted runner
      acceptable value for this input is very limited.

outputs:
  arch:
    value: ${{ steps.uname.outputs.uname }}
    description: >-
      Actual architecture.  This could be different from the one
      passed to the `inputs.arch`.  For instance giving `i386` to this
      action yields `i686`.

runs:
  using: composite

  steps:
    - id: uname
      name: uname
      shell: bash
      env:
        arch: ${{ inputs.arch }}
      run: |
        setarch="${arch:+setarch $arch --}"
        # normalize `uname`
        if uname=$(${setarch} uname -m 2> /dev/null); then
          # `setarch` works, `$arch` is a valid architecture name.
          echo "setarch=${setarch}" >> "$GITHUB_OUTPUT"
        else
          # if `setarch` failed, take the given `arch` as-is.
          uname="${arch}"
          setarch=""
        fi
        echo "uname=$uname" >> "$GITHUB_OUTPUT"
        echo "dpkg=${uname/686/386}" >> "$GITHUB_OUTPUT"

    - name: set SETARCH
      shell: bash
      run: echo "SETARCH=${setarch}" >> "$GITHUB_ENV" # zizmor: ignore[github-env]
      env:
        setarch: ${{ steps.uname.outputs.setarch }} # validated

    - name: dpkg setup
      shell: bash
      run: sudo dpkg --add-architecture "${dpkg}"
      # `dpkg` is valid, also `uname`.
      if: ${{ inputs.arch }}
      env:
        dpkg: ${{ steps.uname.outputs.dpkg }}

    - name: apt-get
      shell: bash
      env:
        arch: ${{ inputs.arch && format(':{0}', steps.uname.outputs.dpkg) || '' }}
      run: |
        set -x
        sudo apt-get update -qq || :
        sudo apt-get install --no-install-recommends -qq -y -o=Dpkg::Use-Pty=0 \
        ${arch:+cross}build-essential${arch/:/-} \
        libssl-dev${arch} libyaml-dev${arch} libreadline6-dev${arch} \
        zlib1g-dev${arch} libncurses5-dev${arch} libffi-dev${arch} \
        autoconf ruby
        sudo apt-get install -qq -y pkg-config${arch} || :
