<?xml version="1.0" encoding="utf-8"?>
<definitions name = "emptycomplextype"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:jp.gr.jin.rrr.example.emptycomplextype"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

  <types>
    <xsd:schema elementFormDefault="qualified"
	targetNamespace="urn:jp.gr.jin.rrr.example.emptycomplextype">
      <xsd:element name="typeIn">
        <xsd:complexType />
      </xsd:element>

      <xsd:element name="typeOut">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" maxOccurs="1" name="str1" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="str2" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="seq">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:any />
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>
</definitions>
