#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.7.3'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end
module Lrama
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 521)

include Lrama::Report::Duration

def initialize(text, path, debug = false)
  @grammar_file = Lrama::Lexer::GrammarFile.new(path, text)
  @yydebug = debug
  @rule_counter = Lrama::Grammar::Counter.new(0)
  @midrule_action_counter = Lrama::Grammar::Counter.new(1)
end

def parse
  report_duration(:parse) do
    @lexer = Lrama::Lexer.new(@grammar_file)
    @grammar = Lrama::Grammar.new(@rule_counter)
    @precedence_number = 0
    reset_precs
    do_parse
    @grammar
  end
end

def next_token
  @lexer.next_token
end

def on_error(error_token_id, error_value, value_stack)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
    value = "'#{error_value.s_value}'"
  else
    location = @lexer.location
    value = error_value.inspect
  end

  error_message = "parse error on value #{value} (#{token_to_str(error_token_id) || '?'})"

  raise_parse_error(error_message, location)
end

def on_action_error(error_message, error_value)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
  else
    location = @lexer.location
  end

  raise_parse_error(error_message, location)
end

private

def reset_precs
  @prec_seen = false
  @code_after_prec = false
end

def begin_c_declaration(end_symbol)
  @lexer.status = :c_declaration
  @lexer.end_symbol = end_symbol
end

def end_c_declaration
  @lexer.status = :initial
  @lexer.end_symbol = nil
end

def raise_parse_error(error_message, location)
  raise ParseError, location.generate_error_message(error_message)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    96,    50,    97,   156,   155,    78,    50,    50,   156,   199,
    78,    78,    50,    50,   199,    49,    78,   158,    69,     6,
     3,     7,   158,   200,   210,   154,     8,    50,   200,    49,
    40,   174,   175,   176,    47,    50,    46,    49,    53,    78,
    74,    50,    53,    49,   159,    53,    81,    98,    56,   159,
   201,   174,   175,   176,    94,   201,    22,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    46,    50,    50,    49,    49,    91,    81,    81,    50,
    50,    49,    49,    50,    81,    49,    57,    78,   184,    58,
    59,    22,    24,    25,    26,    27,    28,    29,    30,    31,
    32,    33,    34,    35,    36,    37,     9,    50,    60,    49,
    13,    14,    15,    16,    17,    18,    61,    62,    19,    20,
    21,    22,    24,    25,    26,    27,    28,    29,    30,    31,
    32,    33,    34,    35,    36,    37,    38,    50,    50,    49,
    49,    78,   184,    50,    50,    49,    49,    78,   184,    50,
    50,    49,    49,    78,   184,    50,    50,    49,    49,    78,
   184,    50,    50,    49,    49,    78,   184,    50,    50,    49,
    49,    78,    78,    50,    50,    49,    49,    78,    78,    50,
    50,    49,    49,    78,    78,    50,    50,   190,    49,    78,
    78,    50,    50,   190,    49,    78,    78,    50,    50,   190,
    49,    78,    50,    50,    49,    49,   152,   203,   153,   204,
   174,   175,   176,   219,   221,   204,   204,    63,    64,    65,
    66,    87,    88,    92,    94,    99,    99,    99,   101,   107,
   111,   112,   115,   115,   115,   115,   118,   121,   122,   124,
   126,   127,   128,   129,   130,   133,   137,   138,   139,   142,
   143,   144,   146,   161,   163,   164,   165,   166,   167,   168,
   169,   142,   171,   179,   180,   189,   194,   195,   197,   202,
   189,    94,   194,   216,   218,    94,   223,    94 ]

racc_action_check = [
    48,   141,    48,   141,   140,   141,   170,   188,   170,   188,
   170,   188,   207,    32,   207,    32,   207,   141,    32,     2,
     1,     2,   170,   188,   199,   140,     3,    14,   207,    14,
     7,   199,   199,   199,    13,    33,     9,    33,    15,    33,
    33,    34,    16,    34,   141,    17,    34,    48,    18,   170,
   188,   157,   157,   157,   157,   207,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,    41,    35,    36,    35,    36,    41,    35,    36,    37,
    68,    37,    68,   165,    37,   165,    19,   165,   165,    22,
    24,    41,    41,    41,    41,    41,    41,    41,    41,    41,
    41,    41,    41,    41,    41,    41,     4,    69,    25,    69,
     4,     4,     4,     4,     4,     4,    26,    27,     4,     4,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     4,     4,     4,   166,    80,   166,
    80,   166,   166,   167,    81,   167,    81,   167,   167,   181,
   107,   181,   107,   181,   181,   185,   109,   185,   109,   185,
   185,   186,   115,   186,   115,   186,   186,    73,    74,    73,
    74,    73,    74,   112,   114,   112,   114,   112,   114,   134,
   159,   134,   159,   134,   159,   171,   201,   171,   201,   171,
   201,   202,   204,   202,   204,   202,   204,   210,   117,   210,
   117,   210,   131,   135,   131,   135,   136,   191,   136,   191,
   192,   192,   192,   213,   217,   213,   217,    28,    29,    30,
    31,    38,    39,    44,    45,    52,    54,    55,    56,    67,
    71,    72,    79,    84,    85,    86,    87,    93,    94,   100,
   102,   103,   104,   105,   106,   110,   118,   119,   120,   121,
   122,   123,   125,   145,   147,   148,   149,   150,   151,   152,
   153,   154,   156,   160,   162,   168,   173,   177,   187,   190,
   197,   198,   203,   206,   211,   216,   222,   223 ]

racc_action_pointer = [
   nil,    20,     9,    26,    97,   nil,   nil,    23,   nil,    32,
   nil,   nil,   nil,    28,    24,    19,    23,    26,    43,    67,
   nil,   nil,    70,   nil,    71,    89,    97,   112,   212,   213,
   214,   215,    10,    32,    38,    69,    70,    76,   216,   220,
   nil,    67,   nil,   nil,   200,   174,   nil,   nil,    -5,   nil,
   nil,   nil,   206,   nil,   207,   208,   209,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   221,    77,   104,
   nil,   224,   223,   164,   165,   nil,   nil,   nil,   nil,   224,
   135,   141,   nil,   nil,   225,   226,   227,   196,   nil,   nil,
   nil,   nil,   nil,   195,   233,   nil,   nil,   nil,   nil,   nil,
   237,   nil,   238,   239,   240,   241,   242,   147,   nil,   153,
   238,   nil,   170,   nil,   171,   159,   nil,   195,   241,   236,
   246,   204,   199,   249,   nil,   250,   nil,   nil,   nil,   nil,
   nil,   199,   nil,   nil,   176,   200,   165,   nil,   nil,   nil,
   -19,    -2,   nil,   nil,   nil,   233,   nil,   234,   235,   236,
   237,   238,   217,   255,   216,   nil,   222,     4,   nil,   177,
   243,   nil,   244,   nil,   nil,    80,   134,   140,   220,   nil,
     3,   182,   nil,   258,   nil,   nil,   nil,   265,   nil,   nil,
   nil,   146,   nil,   nil,   nil,   152,   158,   224,     4,   nil,
   229,   166,   163,   nil,   nil,   nil,   nil,   225,   221,   -16,
   nil,   183,   188,   264,   189,   nil,   253,     9,   nil,   nil,
   194,   272,   nil,   172,   nil,   nil,   225,   173,   nil,   nil,
   nil,   nil,   256,   227,   nil ]

racc_action_default = [
    -2,  -136,    -8,  -136,  -136,    -3,    -4,  -136,   225,  -136,
    -9,   -10,   -11,  -136,  -136,  -136,  -136,  -136,  -136,  -136,
   -23,   -24,  -136,   -28,  -136,  -136,  -136,  -136,  -136,  -136,
  -136,  -136,  -136,  -136,  -136,  -136,  -136,  -136,  -136,  -136,
    -7,  -121,   -94,   -96,  -136,  -118,  -120,   -12,  -125,   -92,
   -93,  -124,   -14,   -83,   -15,   -16,  -136,   -20,   -25,   -29,
   -32,   -35,   -38,   -39,   -40,   -41,   -42,   -43,   -49,  -136,
   -52,   -69,   -44,   -73,  -136,   -76,   -78,   -79,  -133,   -45,
   -86,  -136,   -89,   -91,   -46,   -47,   -48,  -136,    -5,    -1,
   -95,  -122,   -97,  -136,  -136,   -13,  -126,  -127,  -128,   -80,
  -136,   -17,  -136,  -136,  -136,  -136,  -136,  -136,   -53,   -50,
   -71,   -70,  -136,   -77,   -74,  -136,   -90,   -87,  -136,  -136,
  -136,  -102,  -136,  -136,   -84,  -136,   -21,   -26,   -30,   -33,
   -36,   -51,   -54,   -72,   -75,   -88,  -136,   -56,    -6,  -123,
   -98,   -99,  -103,  -119,   -81,  -136,   -18,  -136,  -136,  -136,
  -136,  -136,  -136,  -136,  -102,  -101,   -92,  -118,  -107,  -136,
  -136,   -85,  -136,   -22,   -27,  -136,  -136,  -136,   -60,   -57,
  -100,  -136,  -104,  -134,  -111,  -112,  -113,  -136,  -110,   -82,
   -19,   -31,  -129,  -131,  -132,   -34,   -37,   -55,   -58,   -61,
   -92,  -136,  -114,  -105,  -135,  -108,  -130,   -60,  -118,   -92,
   -65,  -136,  -136,  -134,  -136,  -116,  -136,   -59,   -62,   -63,
  -136,  -136,   -68,  -136,  -106,  -115,  -118,  -136,   -66,  -117,
  -109,   -64,  -136,  -118,   -67 ]

racc_goto_table = [
    93,    51,    73,    68,   116,    75,   108,   173,   193,     1,
   188,   196,     2,   191,   117,   196,   196,   141,     4,    71,
    41,    83,    83,    83,    83,    42,    79,    84,    85,    86,
    52,    54,    55,   181,   185,   186,    89,     5,   214,   207,
   109,   116,   205,   114,   213,   113,    75,   108,   135,   209,
   170,    39,   217,   119,    10,    71,    71,    90,    11,   116,
    12,    48,    95,   125,   162,   102,   147,    83,    83,   108,
   103,   148,   104,   149,   105,   150,   106,   151,   131,    67,
    72,   134,   110,   132,    75,   136,   113,   187,   211,   222,
   123,   160,   100,   145,    71,   140,    71,   177,   206,   120,
   nil,   nil,    83,   nil,    83,   nil,   113,   nil,   nil,   nil,
   nil,   nil,   172,   157,   nil,   nil,   nil,   nil,    71,   nil,
   nil,   nil,    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   178,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   157,   192,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   208,   nil,   nil,   nil,   nil,   nil,   nil,
   198,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   220,   nil,   212,   192,   nil,   215,   nil,   224,   198,
   nil,   nil,   192 ]

racc_goto_check = [
    41,    34,    46,    32,    53,    40,    33,    42,    59,     1,
    39,    63,     2,    43,    52,    63,    63,    58,     3,    34,
     4,    34,    34,    34,    34,    54,    31,    31,    31,    31,
    14,    14,    14,    20,    20,    20,     5,     6,    59,    39,
    32,    53,    42,    46,    43,    40,    40,    33,    52,    42,
    58,     7,    43,     8,     9,    34,    34,    54,    10,    53,
    11,    12,    13,    15,    16,    17,    18,    34,    34,    33,
    21,    22,    23,    24,    25,    26,    27,    28,    32,    29,
    30,    46,    35,    36,    40,    37,    40,    38,    44,    45,
    48,    49,    50,    51,    34,    57,    34,    60,    61,    62,
   nil,   nil,    34,   nil,    34,   nil,    40,   nil,   nil,   nil,
   nil,   nil,    41,    40,   nil,   nil,   nil,   nil,    34,   nil,
   nil,   nil,    34,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    40,    40,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    41,   nil,   nil,   nil,   nil,   nil,   nil,
    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    41,   nil,    40,    40,   nil,    40,   nil,    41,    40,
   nil,   nil,    40 ]

racc_goto_pointer = [
   nil,     9,    12,    16,    11,    -5,    35,    45,   -35,    50,
    54,    56,    47,    14,    15,   -38,   -82,     8,   -60,   nil,
  -132,    12,   -56,    13,   -55,    14,   -54,    15,   -53,    47,
    47,    -8,   -29,   -62,   -13,    11,   -27,   -33,   -81,  -158,
   -28,   -45,  -150,  -158,  -112,  -129,   -31,   nil,    -9,   -53,
    39,   -31,   -67,   -76,    16,   nil,   nil,   -26,  -104,  -165,
   -61,   -97,     8,  -170 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    44,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    23,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    70,    76,   nil,   nil,   nil,   nil,   nil,
   183,   nil,   nil,   nil,   nil,   nil,   nil,    77,   nil,   nil,
   nil,   nil,    80,    82,   nil,    43,    45,   nil,   nil,   nil,
   nil,   nil,   nil,   182 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 54, :_reduce_none,
  0, 55, :_reduce_none,
  2, 55, :_reduce_none,
  0, 60, :_reduce_4,
  0, 61, :_reduce_5,
  5, 59, :_reduce_6,
  2, 59, :_reduce_none,
  0, 56, :_reduce_8,
  2, 56, :_reduce_none,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  2, 62, :_reduce_12,
  3, 62, :_reduce_none,
  2, 62, :_reduce_none,
  2, 62, :_reduce_15,
  2, 62, :_reduce_16,
  0, 68, :_reduce_17,
  0, 69, :_reduce_18,
  7, 62, :_reduce_19,
  0, 70, :_reduce_20,
  0, 71, :_reduce_21,
  6, 62, :_reduce_22,
  1, 62, :_reduce_23,
  1, 62, :_reduce_none,
  0, 74, :_reduce_25,
  0, 75, :_reduce_26,
  6, 63, :_reduce_27,
  1, 63, :_reduce_none,
  0, 76, :_reduce_29,
  0, 77, :_reduce_30,
  7, 63, :_reduce_none,
  0, 78, :_reduce_32,
  0, 79, :_reduce_33,
  7, 63, :_reduce_34,
  0, 80, :_reduce_35,
  0, 81, :_reduce_36,
  7, 63, :_reduce_37,
  2, 63, :_reduce_38,
  2, 63, :_reduce_39,
  2, 63, :_reduce_40,
  2, 63, :_reduce_41,
  2, 63, :_reduce_42,
  2, 72, :_reduce_none,
  2, 72, :_reduce_44,
  2, 72, :_reduce_45,
  2, 72, :_reduce_46,
  2, 72, :_reduce_47,
  2, 72, :_reduce_48,
  1, 82, :_reduce_49,
  2, 82, :_reduce_50,
  3, 82, :_reduce_51,
  1, 85, :_reduce_52,
  2, 85, :_reduce_53,
  3, 86, :_reduce_54,
  7, 64, :_reduce_55,
  1, 90, :_reduce_56,
  3, 90, :_reduce_57,
  1, 91, :_reduce_58,
  3, 91, :_reduce_59,
  0, 92, :_reduce_60,
  1, 92, :_reduce_61,
  3, 92, :_reduce_62,
  3, 92, :_reduce_63,
  5, 92, :_reduce_64,
  0, 97, :_reduce_65,
  0, 98, :_reduce_66,
  7, 92, :_reduce_67,
  3, 92, :_reduce_68,
  0, 88, :_reduce_none,
  1, 88, :_reduce_none,
  0, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 83, :_reduce_73,
  2, 83, :_reduce_74,
  3, 83, :_reduce_75,
  1, 99, :_reduce_76,
  2, 99, :_reduce_77,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  0, 101, :_reduce_80,
  0, 102, :_reduce_81,
  6, 67, :_reduce_82,
  0, 103, :_reduce_83,
  0, 104, :_reduce_84,
  5, 67, :_reduce_85,
  1, 84, :_reduce_86,
  2, 84, :_reduce_87,
  3, 84, :_reduce_88,
  1, 105, :_reduce_89,
  2, 105, :_reduce_90,
  1, 106, :_reduce_none,
  1, 87, :_reduce_92,
  1, 87, :_reduce_93,
  1, 57, :_reduce_none,
  2, 57, :_reduce_none,
  1, 107, :_reduce_none,
  2, 107, :_reduce_none,
  4, 108, :_reduce_98,
  1, 110, :_reduce_99,
  3, 110, :_reduce_100,
  2, 110, :_reduce_none,
  0, 111, :_reduce_102,
  1, 111, :_reduce_103,
  3, 111, :_reduce_104,
  4, 111, :_reduce_105,
  6, 111, :_reduce_106,
  0, 113, :_reduce_107,
  0, 114, :_reduce_108,
  7, 111, :_reduce_109,
  3, 111, :_reduce_110,
  1, 95, :_reduce_111,
  1, 95, :_reduce_112,
  1, 95, :_reduce_113,
  1, 96, :_reduce_114,
  3, 96, :_reduce_115,
  2, 96, :_reduce_116,
  4, 96, :_reduce_117,
  0, 94, :_reduce_none,
  3, 94, :_reduce_119,
  1, 109, :_reduce_none,
  0, 58, :_reduce_none,
  0, 115, :_reduce_122,
  3, 58, :_reduce_123,
  1, 65, :_reduce_none,
  0, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 73, :_reduce_129,
  2, 73, :_reduce_130,
  1, 116, :_reduce_none,
  1, 116, :_reduce_none,
  1, 100, :_reduce_133,
  0, 112, :_reduce_none,
  1, 112, :_reduce_none ]

racc_reduce_n = 136

racc_shift_n = 225

racc_token_table = {
  false => 0,
  :error => 1,
  :C_DECLARATION => 2,
  :CHARACTER => 3,
  :IDENT_COLON => 4,
  :IDENTIFIER => 5,
  :INTEGER => 6,
  :STRING => 7,
  :TAG => 8,
  "%%" => 9,
  "%{" => 10,
  "%}" => 11,
  "%require" => 12,
  "%expect" => 13,
  "%define" => 14,
  "%param" => 15,
  "%lex-param" => 16,
  "%parse-param" => 17,
  "%code" => 18,
  "{" => 19,
  "}" => 20,
  "%initial-action" => 21,
  "%no-stdlib" => 22,
  ";" => 23,
  "%union" => 24,
  "%destructor" => 25,
  "%printer" => 26,
  "%error-token" => 27,
  "%after-shift" => 28,
  "%before-reduce" => 29,
  "%after-reduce" => 30,
  "%after-shift-error-token" => 31,
  "%after-pop-stack" => 32,
  "%token" => 33,
  "%type" => 34,
  "%left" => 35,
  "%right" => 36,
  "%precedence" => 37,
  "%nonassoc" => 38,
  "%rule" => 39,
  "(" => 40,
  ")" => 41,
  ":" => 42,
  "," => 43,
  "|" => 44,
  "%empty" => 45,
  "%prec" => 46,
  "?" => 47,
  "+" => 48,
  "*" => 49,
  "[" => 50,
  "]" => 51,
  "{...}" => 52 }

racc_nt_base = 53

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "C_DECLARATION",
  "CHARACTER",
  "IDENT_COLON",
  "IDENTIFIER",
  "INTEGER",
  "STRING",
  "TAG",
  "\"%%\"",
  "\"%{\"",
  "\"%}\"",
  "\"%require\"",
  "\"%expect\"",
  "\"%define\"",
  "\"%param\"",
  "\"%lex-param\"",
  "\"%parse-param\"",
  "\"%code\"",
  "\"{\"",
  "\"}\"",
  "\"%initial-action\"",
  "\"%no-stdlib\"",
  "\";\"",
  "\"%union\"",
  "\"%destructor\"",
  "\"%printer\"",
  "\"%error-token\"",
  "\"%after-shift\"",
  "\"%before-reduce\"",
  "\"%after-reduce\"",
  "\"%after-shift-error-token\"",
  "\"%after-pop-stack\"",
  "\"%token\"",
  "\"%type\"",
  "\"%left\"",
  "\"%right\"",
  "\"%precedence\"",
  "\"%nonassoc\"",
  "\"%rule\"",
  "\"(\"",
  "\")\"",
  "\":\"",
  "\",\"",
  "\"|\"",
  "\"%empty\"",
  "\"%prec\"",
  "\"?\"",
  "\"+\"",
  "\"*\"",
  "\"[\"",
  "\"]\"",
  "\"{...}\"",
  "$start",
  "input",
  "prologue_declarations",
  "bison_declarations",
  "grammar",
  "epilogue_opt",
  "prologue_declaration",
  "@1",
  "@2",
  "bison_declaration",
  "grammar_declaration",
  "rule_declaration",
  "variable",
  "value",
  "params",
  "@3",
  "@4",
  "@5",
  "@6",
  "symbol_declaration",
  "generic_symlist",
  "@7",
  "@8",
  "@9",
  "@10",
  "@11",
  "@12",
  "@13",
  "@14",
  "token_declarations",
  "symbol_declarations",
  "token_declarations_for_precedence",
  "token_declaration_list",
  "token_declaration",
  "id",
  "int_opt",
  "alias",
  "rule_args",
  "rule_rhs_list",
  "rule_rhs",
  "symbol",
  "named_ref_opt",
  "parameterizing_suffix",
  "parameterizing_args",
  "@15",
  "@16",
  "symbol_declaration_list",
  "string_as_id",
  "@17",
  "@18",
  "@19",
  "@20",
  "token_declaration_list_for_precedence",
  "token_declaration_for_precedence",
  "rules_or_grammar_declaration",
  "rules",
  "id_colon",
  "rhs_list",
  "rhs",
  "tag_opt",
  "@21",
  "@22",
  "@23",
  "generic_symlist_item" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_4(val, _values, result)
                                begin_c_declaration("%}")
                            @grammar.prologue_first_lineno = @lexer.line

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_5(val, _values, result)
                                end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_6(val, _values, result)
                                @grammar.prologue = val[2].s_value

    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_8(val, _values, result)
     result = ""
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_12(val, _values, result)
     @grammar.expect = val[1]
    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_15(val, _values, result)
                             val[1].each {|token|
                           @grammar.lex_param = Grammar::Code::NoReferenceCode.new(type: :lex_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_16(val, _values, result)
                             val[1].each {|token|
                           @grammar.parse_param = Grammar::Code::NoReferenceCode.new(type: :parse_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_17(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_18(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_19(val, _values, result)
                             @grammar.add_percent_code(id: val[1], code: val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_20(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_21(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_22(val, _values, result)
                             @grammar.initial_action = Grammar::Code::InitialActionCode.new(type: :initial_action, token_code: val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_23(val, _values, result)
     @grammar.no_stdlib = true
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_25(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_26(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_27(val, _values, result)
                               @grammar.set_union(
                             Grammar::Code::NoReferenceCode.new(type: :union, token_code: val[3]),
                             val[3].line
                           )

    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.y', 92)
  def _reduce_29(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_30(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

# reduce 31 omitted

module_eval(<<'.,.,', 'parser.y', 101)
  def _reduce_32(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 105)
  def _reduce_33(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_34(val, _values, result)
                               @grammar.add_printer(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_35(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 121)
  def _reduce_36(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_37(val, _values, result)
                               @grammar.add_error_token(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_38(val, _values, result)
                               @grammar.after_shift = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 137)
  def _reduce_39(val, _values, result)
                               @grammar.before_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 141)
  def _reduce_40(val, _values, result)
                               @grammar.after_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 145)
  def _reduce_41(val, _values, result)
                               @grammar.after_shift_error_token = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 149)
  def _reduce_42(val, _values, result)
                               @grammar.after_pop_stack = val[1]

    result
  end
.,.,

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_44(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              @grammar.add_type(id: id, tag: hash[:tag])
                            }
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 163)
  def _reduce_45(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_left(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 173)
  def _reduce_46(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_right(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 183)
  def _reduce_47(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_precedence(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 193)
  def _reduce_48(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_nonassoc(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 204)
  def _reduce_49(val, _values, result)
                              val[0].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: nil, replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 210)
  def _reduce_50(val, _values, result)
                              val[1].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[0], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 216)
  def _reduce_51(val, _values, result)
                              val[2].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[1], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 221)
  def _reduce_52(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_53(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_54(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 228)
  def _reduce_55(val, _values, result)
                            rule = Grammar::ParameterizingRule::Rule.new(val[1].s_value, val[3], val[6])
                        @grammar.add_parameterizing_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_56(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 233)
  def _reduce_57(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 237)
  def _reduce_58(val, _values, result)
                      builder = val[0]
                  result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 242)
  def _reduce_59(val, _values, result)
                      builder = val[2]
                  result = val[0].append(builder)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 248)
  def _reduce_60(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRule::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 253)
  def _reduce_61(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRule::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 258)
  def _reduce_62(val, _values, result)
                  token = val[1]
              token.alias_name = val[2]
              builder = val[0]
              builder.symbols << token
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 266)
  def _reduce_63(val, _values, result)
                    builder = val[0]
                builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]])
                result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 272)
  def _reduce_64(val, _values, result)
                    builder = val[0]
                builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3])
                result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 278)
  def _reduce_65(val, _values, result)
                  if @prec_seen
                on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
                @code_after_prec = true
              end
              begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 286)
  def _reduce_66(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 290)
  def _reduce_67(val, _values, result)
                  user_code = val[3]
              user_code.alias_name = val[6]
              builder = val[0]
              builder.user_code = user_code
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 298)
  def _reduce_68(val, _values, result)
                  sym = @grammar.find_symbol_by_id!(val[2])
              @prec_seen = true
              builder = val[0]
              builder.precedence_sym = sym
              result = builder

    result
  end
.,.,

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

module_eval(<<'.,.,', 'parser.y', 313)
  def _reduce_73(val, _values, result)
                               result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 317)
  def _reduce_74(val, _values, result)
                               result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 321)
  def _reduce_75(val, _values, result)
                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 324)
  def _reduce_76(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 325)
  def _reduce_77(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 78 omitted

# reduce 79 omitted

module_eval(<<'.,.,', 'parser.y', 332)
  def _reduce_80(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 336)
  def _reduce_81(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 340)
  def _reduce_82(val, _values, result)
                  result = val[0].append(val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 344)
  def _reduce_83(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 348)
  def _reduce_84(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 352)
  def _reduce_85(val, _values, result)
                  result = [val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 357)
  def _reduce_86(val, _values, result)
                                             result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 361)
  def _reduce_87(val, _values, result)
                                             result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 365)
  def _reduce_88(val, _values, result)
                                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 368)
  def _reduce_89(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 369)
  def _reduce_90(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 91 omitted

module_eval(<<'.,.,', 'parser.y', 373)
  def _reduce_92(val, _values, result)
     on_action_error("ident after %prec", val[0]) if @prec_seen
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 374)
  def _reduce_93(val, _values, result)
     on_action_error("char after %prec", val[0]) if @prec_seen
    result
  end
.,.,

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

module_eval(<<'.,.,', 'parser.y', 384)
  def _reduce_98(val, _values, result)
                 lhs = val[0]
             lhs.alias_name = val[1]
             val[3].each do |builder|
               builder.lhs = lhs
               builder.complete_input
               @grammar.add_rule_builder(builder)
             end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 395)
  def _reduce_99(val, _values, result)
                    builder = val[0]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 403)
  def _reduce_100(val, _values, result)
                    builder = val[2]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = val[0].append(builder)

    result
  end
.,.,

# reduce 101 omitted

module_eval(<<'.,.,', 'parser.y', 413)
  def _reduce_102(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 418)
  def _reduce_103(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 423)
  def _reduce_104(val, _values, result)
               token = val[1]
           token.alias_name = val[2]
           builder = val[0]
           builder.add_rhs(token)
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 431)
  def _reduce_105(val, _values, result)
               token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]], lhs_tag: val[3])
           builder = val[0]
           builder.add_rhs(token)
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 439)
  def _reduce_106(val, _values, result)
               token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3], lhs_tag: val[5])
           builder = val[0]
           builder.add_rhs(token)
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 447)
  def _reduce_107(val, _values, result)
               if @prec_seen
             on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
             @code_after_prec = true
           end
           begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 455)
  def _reduce_108(val, _values, result)
               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 459)
  def _reduce_109(val, _values, result)
               user_code = val[3]
           user_code.alias_name = val[6]
           builder = val[0]
           builder.user_code = user_code
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 467)
  def _reduce_110(val, _values, result)
               sym = @grammar.find_symbol_by_id!(val[2])
           @prec_seen = true
           builder = val[0]
           builder.precedence_sym = sym
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 474)
  def _reduce_111(val, _values, result)
     result = "option"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 475)
  def _reduce_112(val, _values, result)
     result = "nonempty_list"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 476)
  def _reduce_113(val, _values, result)
     result = "list"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 478)
  def _reduce_114(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 479)
  def _reduce_115(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 480)
  def _reduce_116(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 481)
  def _reduce_117(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[0].s_value, location: @lexer.location, args: val[2])]
    result
  end
.,.,

# reduce 118 omitted

module_eval(<<'.,.,', 'parser.y', 484)
  def _reduce_119(val, _values, result)
     result = val[1].s_value
    result
  end
.,.,

# reduce 120 omitted

# reduce 121 omitted

module_eval(<<'.,.,', 'parser.y', 491)
  def _reduce_122(val, _values, result)
                        begin_c_declaration('\Z')
                    @grammar.epilogue_first_lineno = @lexer.line + 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 496)
  def _reduce_123(val, _values, result)
                        end_c_declaration
                    @grammar.epilogue = val[2].s_value

    result
  end
.,.,

# reduce 124 omitted

# reduce 125 omitted

# reduce 126 omitted

# reduce 127 omitted

# reduce 128 omitted

module_eval(<<'.,.,', 'parser.y', 507)
  def _reduce_129(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 508)
  def _reduce_130(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 131 omitted

# reduce 132 omitted

module_eval(<<'.,.,', 'parser.y', 513)
  def _reduce_133(val, _values, result)
     result = Lrama::Lexer::Token::Ident.new(s_value: val[0])
    result
  end
.,.,

# reduce 134 omitted

# reduce 135 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Lrama
