// This file is @generated by src/hir/gen_hir_effect.rb.
mod bits {
  pub const Any: u64 = Frame | World;
  pub const Frame: u64 = Locals | PC | Stack;
  pub const Locals: u64 = 1u64 << 0;
  pub const None: u64 = 0u64;
  pub const PC: u64 = 1u64 << 1;
  pub const Stack: u64 = 1u64 << 2;
  pub const World: u64 = 1u64 << 3;
  pub const AllBitPatterns: [(&str, u64); 7] = [
    ("Any", Any),
    ("World", World),
    ("Frame", Frame),
    ("Stack", Stack),
    ("PC", PC),
    ("Locals", Locals),
    ("None", None),
  ];
  pub const NumEffectBits: u64 = 4;
}
pub mod effects {
  use super::*;
  pub const Any: Effect = Effect::from_bits(bits::Any);
  pub const Frame: Effect = Effect::from_bits(bits::Frame);
  pub const Locals: Effect = Effect::from_bits(bits::Locals);
  pub const None: Effect = Effect::from_bits(bits::None);
  pub const PC: Effect = Effect::from_bits(bits::PC);
  pub const Stack: Effect = Effect::from_bits(bits::Stack);
  pub const World: Effect = Effect::from_bits(bits::World);
}
