<?xml version="1.0" encoding="utf-8"?>
<definitions
    name="lp"
    targetNamespace="urn:lp"
    xmlns:tns="urn:lp"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="urn:lp" schemaLocation="lp.xsd"/>
    </schema>
  </types>

  <message name="login_in">
    <part name="parameters" element="tns:login" />
  </message>
  <message name="login_out">
    <part name="parameters" element="tns:loginResponse" />
  </message>

  <portType name="lp_porttype">
    <operation name="login">
      <input message="tns:login_in" />
      <output message="tns:login_out" />
    </operation>
  </portType>

  <binding name="lp_binding" type="tns:lp_porttype">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <operation name="login">
      <soap:operation soapAction="urn:lp:login" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>

  <service name="lp_service">
    <port name="lp_service_port" binding="tns:lp_binding">
      <soap:address location="http://localhost:17171/" />
    </port>
  </service>
</definitions>
