ProgramNode(0...27)(
  ScopeNode(0...0)([]),
  StatementsNode(0...27)(
    [AndNode(0...27)(
       AndNode(0...18)(
         TrueNode(0...4)(),
         CallNode(9...18)(
           FalseNode(13...18)(),
           nil,
           KEYWORD_NOT(9...12)("not"),
           nil,
           nil,
           nil,
           nil,
           "!"
         ),
         KEYWORD_AND(5...8)("and")
       ),
       TrueNode(23...27)(),
       KEYWORD_AND(19...22)("and")
     )]
  )
)
