ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [ArrayNode(0...11)(
       [IntegerNode(1...2)(),
        HashNode(4...10)(
          nil,
          [AssocNode(4...10)(
             IntegerNode(4...5)(),
             IntegerNode(9...10)(),
             EQUAL_GREATER(6...8)("=>")
           )],
          nil
        )],
       BRACKET_LEFT_ARRAY(0...1)("["),
       BRACKET_RIGHT(10...11)("]")
     )]
  )
)
