ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [ArrayNode(0...8)(
       [HashNode(1...7)(
          nil,
          [AssocNode(1...7)(
             IntegerNode(1...2)(),
             IntegerNode(6...7)(),
             EQUAL_GREATER(3...5)("=>")
           )],
          nil
        )],
       BRACKET_LEFT_ARRAY(0...1)("["),
       BRACKET_RIGHT(7...8)("]")
     )]
  )
)
