ProgramNode(0...20)(
  ScopeNode(0...0)([]),
  StatementsNode(0...20)(
    [DefNode(0...20)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...14)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(6...10)(
            LABEL(6...8)("a:"),
            IntegerNode(9...10)()
          )],
         nil,
         BlockParameterNode(12...14)(IDENTIFIER(13...14)("b"), (12...13))
       ),
       nil,
       ScopeNode(0...3)([LABEL(6...7)("a"), IDENTIFIER(13...14)("b")]),
       (0...3),
       nil,
       (5...6),
       (14...15),
       nil,
       (17...20)
     )]
  )
)
