ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [CallNode(0...6)(
       ArrayNode(0...4)(
         [],
         PERCENT_LOWER_W(0...3)("%w["),
         STRING_END(3...4)("]")
       ),
       DOT(4...5)("."),
       IDENTIFIER(5...6)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     ),
     CallNode(8...12)(
       ArrayNode(8...10)(
         [],
         BRACKET_LEFT_ARRAY(8...9)("["),
         BRACKET_RIGHT(9...10)("]")
       ),
       DOT(10...11)("."),
       IDENTIFIER(11...12)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
