ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [HashNode(0...6)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(2...4)(
          SymbolNode(2...4)(
            nil,
            LABEL(2...3)("y"),
            LABEL_END(3...4)(":"),
            "y"
          ),
          nil,
          nil
        )],
       BRACE_RIGHT(5...6)("}")
     )]
  )
)
