ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [CallNode(0...6)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...5)(
         [HashNode(2...5)(
            nil,
            [AssocNode(2...5)(
               SymbolNode(2...4)(
                 nil,
                 LABEL(2...3)("b"),
                 LABEL_END(3...4)(":"),
                 "b"
               ),
               IntegerNode(4...5)(),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(5...6)(")"),
       nil,
       "a"
     )]
  )
)
