ProgramNode(0...3)(
  ScopeNode(0...0)([]),
  StatementsNode(0...3)(
    [CallNode(0...3)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(1...2)("."),
       CONSTANT(2...3)("B"),
       nil,
       ArgumentsNode(6...7)([IntegerNode(6...7)()]),
       nil,
       nil,
       "B="
     )]
  )
)
