ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [CallNode(0...13)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       nil,
       BRACKET_LEFT_RIGHT_EQUAL(1...2)("["),
       BRACKET_LEFT(1...2)("["),
       ArgumentsNode(2...13)(
         [ArrayNode(2...8)(
            [IntegerNode(3...4)(), IntegerNode(6...7)()],
            BRACKET_LEFT_ARRAY(2...3)("["),
            BRACKET_RIGHT(7...8)("]")
          ),
          IntegerNode(12...13)()]
       ),
       BRACKET_RIGHT(8...9)("]"),
       nil,
       "[]="
     )]
  )
)
