ProgramNode(0...14)(
  ScopeNode(0...0)([]),
  StatementsNode(0...14)(
    [RangeNode(0...4)(nil, IntegerNode(2...4)(), (0...2)),
     RangeNode(7...10)(
       nil,
       CallNode(9...10)(
         nil,
         nil,
         IDENTIFIER(9...10)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       (7...9)
     ),
     CallNode(13...14)(
       nil,
       nil,
       IDENTIFIER(13...14)("c"),
       nil,
       nil,
       nil,
       nil,
       "c"
     )]
  )
)
