ProgramNode(0...32)(
  ScopeNode(0...0)([]),
  StatementsNode(0...32)(
    [BeginNode(0...32)(
       KEYWORD_BEGIN(0...5)("begin"),
       nil,
       RescueNode(7...13)(
         KEYWORD_RESCUE(7...13)("rescue"),
         [],
         nil,
         nil,
         nil,
         nil
       ),
       ElseNode(15...27)(
         KEYWORD_ELSE(15...19)("else"),
         nil,
         KEYWORD_ENSURE(21...27)("ensure")
       ),
       EnsureNode(21...32)(
         KEYWORD_ENSURE(21...27)("ensure"),
         nil,
         KEYWORD_END(29...32)("end")
       ),
       KEYWORD_END(29...32)("end")
     )]
  )
)
