ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [BeginNode(0...23)(
       KEYWORD_BEGIN(0...5)("begin"),
       nil,
       RescueNode(6...12)(
         KEYWORD_RESCUE(6...12)("rescue"),
         [],
         nil,
         nil,
         nil,
         nil
       ),
       nil,
       EnsureNode(13...23)(
         KEYWORD_ENSURE(13...19)("ensure"),
         nil,
         KEYWORD_END(20...23)("end")
       ),
       KEYWORD_END(20...23)("end")
     )]
  )
)
