ProgramNode(0...30)(
  ScopeNode(0...0)([]),
  StatementsNode(0...30)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...18)(
         [DefNode(2...18)(
            IDENTIFIER(6...7)("b"),
            nil,
            ParametersNode(8...9)(
              [RequiredParameterNode(8...9)()],
              [],
              [],
              nil,
              [],
              nil,
              nil
            ),
            StatementsNode(12...13)(
              [CallNode(12...13)(
                 nil,
                 nil,
                 IDENTIFIER(12...13)("d"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "d"
               )]
            ),
            ScopeNode(2...5)([IDENTIFIER(8...9)("c")]),
            (2...5),
            nil,
            (7...8),
            (9...10),
            nil,
            (15...18)
          )]
       ),
       nil,
       nil,
       "a"
     ),
     CallNode(20...30)(
       CallNode(20...21)(
         nil,
         nil,
         IDENTIFIER(20...21)("e"),
         nil,
         nil,
         nil,
         nil,
         "e"
       ),
       DOT(21...22)("."),
       IDENTIFIER(22...23)("f"),
       nil,
       nil,
       nil,
       BlockNode(24...30)(
         ScopeNode(24...26)([]),
         nil,
         nil,
         (24...26),
         (27...30)
       ),
       "f"
     )]
  )
)
