ProgramNode(0...20)(
  ScopeNode(0...0)([]),
  StatementsNode(0...20)(
    [CallNode(0...20)(
       nil,
       nil,
       IDENTIFIER(0...2)("bl"),
       nil,
       nil,
       nil,
       BlockNode(3...20)(
         ScopeNode(3...4)([LABEL(6...8)("kw")]),
         BlockParametersNode(5...15)(
           ParametersNode(6...14)(
             [],
             [],
             [],
             nil,
             [KeywordParameterNode(6...14)(
                LABEL(6...9)("kw:"),
                SymbolNode(10...14)(
                  SYMBOL_BEGIN(10...11)(":"),
                  IDENTIFIER(11...14)("val"),
                  nil,
                  "val"
                )
              )],
             nil,
             nil
           ),
           [],
           (5...6),
           (14...15)
         ),
         StatementsNode(16...18)([LocalVariableReadNode(16...18)(0)]),
         (3...4),
         (19...20)
       ),
       "bl"
     )]
  )
)
