ProgramNode(0...25)(
  ScopeNode(0...0)([]),
  StatementsNode(0...25)(
    [CallNode(0...25)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...25)(
         ScopeNode(2...3)(
           [IDENTIFIER(5...6)("b"),
            IDENTIFIER(8...9)("c"),
            IDENTIFIER(14...15)("d"),
            IDENTIFIER(17...18)("e"),
            IDENTIFIER(21...22)("f")]
         ),
         BlockParametersNode(4...23)(
           ParametersNode(5...22)(
             [RequiredParameterNode(5...6)()],
             [OptionalParameterNode(8...11)(
                IDENTIFIER(8...9)("c"),
                EQUAL(9...10)("="),
                IntegerNode(10...11)()
              )],
             [RequiredParameterNode(17...18)()],
             RestParameterNode(13...15)(
               USTAR(13...14)("*"),
               IDENTIFIER(14...15)("d")
             ),
             [],
             nil,
             BlockParameterNode(20...22)(IDENTIFIER(21...22)("f"), (20...21))
           ),
           [],
           (4...5),
           (22...23)
         ),
         nil,
         (2...3),
         (24...25)
       ),
       "a"
     )]
  )
)
