ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [CallNode(0...11)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...11)(
         ScopeNode(2...3)([IDENTIFIER(7...8)("b")]),
         BlockParametersNode(4...9)(
           ParametersNode(5...8)(
             [],
             [],
             [],
             nil,
             [],
             KeywordRestParameterNode(5...8)(
               USTAR_STAR(5...7)("**"),
               IDENTIFIER(7...8)("b")
             ),
             nil
           ),
           [],
           (4...5),
           (8...9)
         ),
         nil,
         (2...3),
         (10...11)
       ),
       "a"
     )]
  )
)
