ProgramNode(0...33)(
  ScopeNode(0...0)([]),
  StatementsNode(0...33)(
    [CallNode(0...33)(
       CallNode(0...16)(
         CallNode(0...1)(
           nil,
           nil,
           IDENTIFIER(0...1)("a"),
           nil,
           nil,
           nil,
           nil,
           "a"
         ),
         DOT(1...2)("."),
         IDENTIFIER(2...3)("b"),
         nil,
         ArgumentsNode(4...7)(
           [CallNode(4...7)(
              nil,
              nil,
              IDENTIFIER(4...5)("c"),
              PARENTHESIS_LEFT(5...6)("("),
              nil,
              PARENTHESIS_RIGHT(6...7)(")"),
              nil,
              "c"
            )]
         ),
         nil,
         BlockNode(8...16)(
           ScopeNode(8...10)([]),
           nil,
           StatementsNode(11...12)(
             [CallNode(11...12)(
                nil,
                nil,
                IDENTIFIER(11...12)("d"),
                nil,
                nil,
                nil,
                nil,
                "d"
              )]
           ),
           (8...10),
           (13...16)
         ),
         "b"
       ),
       DOT(16...17)("."),
       IDENTIFIER(17...18)("e"),
       nil,
       ArgumentsNode(19...20)(
         [CallNode(19...20)(
            nil,
            nil,
            IDENTIFIER(19...20)("f"),
            nil,
            nil,
            nil,
            nil,
            "f"
          )]
       ),
       nil,
       BlockNode(21...33)(
         ScopeNode(21...23)([IDENTIFIER(25...26)("g")]),
         BlockParametersNode(24...27)(
           ParametersNode(25...26)(
             [RequiredParameterNode(25...26)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (24...25),
           (26...27)
         ),
         StatementsNode(28...29)(
           [CallNode(28...29)(
              nil,
              nil,
              IDENTIFIER(28...29)("h"),
              nil,
              nil,
              nil,
              nil,
              "h"
            )]
         ),
         (21...23),
         (30...33)
       ),
       "e"
     )]
  )
)
