ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [CallNode(0...16)(
       nil,
       nil,
       IDENTIFIER(0...4)("blah"),
       nil,
       nil,
       nil,
       BlockNode(5...16)(
         ScopeNode(5...7)([LABEL(9...10)("k")]),
         BlockParametersNode(8...12)(
           ParametersNode(9...11)(
             [],
             [],
             [],
             nil,
             [KeywordParameterNode(9...11)(LABEL(9...11)("k:"), nil)],
             nil,
             nil
           ),
           [],
           (8...9),
           (11...12)
         ),
         nil,
         (5...7),
         (13...16)
       ),
       "blah"
     )]
  )
)
