ProgramNode(0...31)(
  ScopeNode(0...0)([]),
  StatementsNode(0...31)(
    [CallNode(0...31)(
       CallNode(0...16)(
         CallNode(0...1)(
           nil,
           nil,
           IDENTIFIER(0...1)("a"),
           nil,
           nil,
           nil,
           nil,
           "a"
         ),
         DOT(1...2)("."),
         IDENTIFIER(2...3)("b"),
         nil,
         ArgumentsNode(4...7)(
           [CallNode(4...7)(
              nil,
              nil,
              IDENTIFIER(4...5)("c"),
              PARENTHESIS_LEFT(5...6)("("),
              nil,
              PARENTHESIS_RIGHT(6...7)(")"),
              nil,
              "c"
            )]
         ),
         nil,
         BlockNode(8...16)(
           ScopeNode(8...10)([]),
           nil,
           StatementsNode(11...12)(
             [CallNode(11...12)(
                nil,
                nil,
                IDENTIFIER(11...12)("d"),
                nil,
                nil,
                nil,
                nil,
                "d"
              )]
           ),
           (8...10),
           (13...16)
         ),
         "b"
       ),
       DOT(16...17)("."),
       IDENTIFIER(17...18)("e"),
       nil,
       nil,
       nil,
       BlockNode(19...31)(
         ScopeNode(19...21)([IDENTIFIER(23...24)("f")]),
         BlockParametersNode(22...25)(
           ParametersNode(23...24)(
             [RequiredParameterNode(23...24)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (22...23),
           (24...25)
         ),
         StatementsNode(26...27)(
           [CallNode(26...27)(
              nil,
              nil,
              IDENTIFIER(26...27)("g"),
              nil,
              nil,
              nil,
              nil,
              "g"
            )]
         ),
         (19...21),
         (28...31)
       ),
       "e"
     )]
  )
)
