ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [CallNode(0...12)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...12)(
         ScopeNode(2...3)([IDENTIFIER(5...6)("b"), IDENTIFIER(8...9)("c")]),
         BlockParametersNode(4...10)(
           ParametersNode(5...6)(
             [RequiredParameterNode(5...6)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [IDENTIFIER(8...9)("c")],
           (4...5),
           (9...10)
         ),
         nil,
         (2...3),
         (11...12)
       ),
       "a"
     )]
  )
)
