ProgramNode(0...14)(
  ScopeNode(0...0)([]),
  StatementsNode(0...14)(
    [CallNode(0...14)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...14)(
         ScopeNode(2...3)([IDENTIFIER(5...6)("b")]),
         BlockParametersNode(4...12)(
           ParametersNode(5...11)(
             [],
             [OptionalParameterNode(5...11)(
                IDENTIFIER(5...6)("b"),
                EQUAL(7...8)("="),
                SymbolNode(9...11)(
                  SYMBOL_BEGIN(9...10)(":"),
                  IDENTIFIER(10...11)("c"),
                  nil,
                  "c"
                )
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (11...12)
         ),
         nil,
         (2...3),
         (13...14)
       ),
       "a"
     )]
  )
)
