ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...18)(
         ScopeNode(2...3)([IDENTIFIER(6...7)("b"), IDENTIFIER(11...12)("c")]),
         BlockParametersNode(4...16)(
           ParametersNode(6...14)(
             [],
             [OptionalParameterNode(6...9)(
                IDENTIFIER(6...7)("b"),
                EQUAL(7...8)("="),
                IntegerNode(8...9)()
              ),
              OptionalParameterNode(11...14)(
                IDENTIFIER(11...12)("c"),
                EQUAL(12...13)("="),
                IntegerNode(13...14)()
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (15...16)
         ),
         nil,
         (2...3),
         (17...18)
       ),
       "a"
     )]
  )
)
