ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [RegularExpressionNode(0...6)(
       REGEXP_BEGIN(0...3)("%r'"),
       STRING_CONTENT(3...5)("\\'"),
       REGEXP_END(5...6)("'"),
       "'"
     )]
  )
)
