ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [CallNode(0...9)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       nil,
       ArgumentsNode(2...9)(
         [RangeNode(2...9)(
            ParenthesesNode(2...4)(nil, (2...3), (3...4)),
            NilNode(6...9)(),
            (4...6)
          )]
       ),
       nil,
       nil,
       "p"
     )]
  )
)
