ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [CallNode(0...7)(
       nil,
       nil,
       IDENTIFIER(0...1)("x"),
       nil,
       nil,
       nil,
       BlockNode(1...7)(
         ScopeNode(1...2)([IDENTIFIER(3...4)("a")]),
         BlockParametersNode(2...6)(
           ParametersNode(3...5)(
             [RequiredParameterNode(3...4)()],
             [],
             [],
             RestParameterNode(4...5)(COMMA(4...5)(","), nil),
             [],
             nil,
             nil
           ),
           [],
           (2...3),
           (5...6)
         ),
         nil,
         (1...2),
         (6...7)
       ),
       "x"
     ),
     CallNode(9...15)(
       nil,
       nil,
       IDENTIFIER(9...10)("x"),
       nil,
       nil,
       nil,
       BlockNode(10...15)(
         ScopeNode(10...11)([IDENTIFIER(12...13)("a")]),
         BlockParametersNode(11...14)(
           ParametersNode(12...13)(
             [RequiredParameterNode(12...13)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (11...12),
           (13...14)
         ),
         nil,
         (10...11),
         (14...15)
       ),
       "x"
     )]
  )
)
