ProgramNode(6...94)(
  ScopeNode(0...0)([]),
  StatementsNode(6...94)(
    [DefNode(6...39)(
       IDENTIFIER(10...11)("f"),
       nil,
       nil,
       StatementsNode(20...29)(
         [CallNode(20...29)(
            nil,
            nil,
            IDENTIFIER(20...21)("g"),
            nil,
            ArgumentsNode(22...29)(
              [ParenthesesNode(22...26)(
                 StatementsNode(24...25)([IntegerNode(24...25)()]),
                 (22...23),
                 (25...26)
               ),
               IntegerNode(28...29)()]
            ),
            nil,
            nil,
            "g"
          )]
       ),
       ScopeNode(6...9)([]),
       (6...9),
       nil,
       nil,
       nil,
       nil,
       (36...39)
     ),
     DefNode(48...82)(
       IDENTIFIER(52...53)("f"),
       nil,
       nil,
       StatementsNode(64...72)(
         [CallNode(64...72)(
            nil,
            nil,
            IDENTIFIER(64...65)("g"),
            nil,
            ArgumentsNode(66...72)(
              [ParenthesesNode(66...69)(
                 StatementsNode(67...68)([IntegerNode(67...68)()]),
                 (66...67),
                 (68...69)
               ),
               IntegerNode(71...72)()]
            ),
            nil,
            nil,
            "g"
          )]
       ),
       ScopeNode(48...51)([]),
       (48...51),
       nil,
       (53...54),
       (54...55),
       nil,
       (79...82)
     ),
     CallNode(85...94)(
       nil,
       nil,
       IDENTIFIER(85...86)("g"),
       nil,
       ArgumentsNode(87...94)(
         [ParenthesesNode(87...91)(
            StatementsNode(89...90)([IntegerNode(89...90)()]),
            (87...88),
            (90...91)
          ),
          IntegerNode(93...94)()]
       ),
       nil,
       nil,
       "g"
     )]
  )
)
