ProgramNode(0...24)(
  ScopeNode(0...0)([]),
  StatementsNode(0...24)(
    [IfNode(0...24)(
       KEYWORD_IF(0...2)("if"),
       CallNode(3...15)(
         nil,
         nil,
         IDENTIFIER(3...7)("test"),
         nil,
         ArgumentsNode(8...15)(
           [StringNode(8...10)(
              STRING_BEGIN(8...9)("?"),
              STRING_CONTENT(9...10)("d"),
              nil,
              "d"
            ),
            CallNode(12...15)(
              nil,
              nil,
              IDENTIFIER(12...15)("dir"),
              nil,
              nil,
              nil,
              nil,
              "dir"
            )]
         ),
         nil,
         nil,
         "test"
       ),
       nil,
       nil,
       KEYWORD_END(21...24)("end")
     )]
  )
)
