ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [CallNode(0...16)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...16)(
         ScopeNode(2...3)([IDENTIFIER(6...7)("a"), IDENTIFIER(9...10)("b")]),
         BlockParametersNode(4...12)(
           ParametersNode(5...11)(
             [RequiredDestructuredParameterNode(5...11)(
                [RequiredParameterNode(6...7)(),
                 RequiredParameterNode(9...10)()],
                PARENTHESIS_LEFT(5...6)("("),
                PARENTHESIS_RIGHT(10...11)(")")
              )],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (11...12)
         ),
         StatementsNode(13...14)(
           [CallNode(13...14)(
              nil,
              nil,
              IDENTIFIER(13...14)("d"),
              nil,
              nil,
              nil,
              nil,
              "d"
            )]
         ),
         (2...3),
         (15...16)
       ),
       "f"
     )]
  )
)
