ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [CallNode(0...6)(
       IntegerNode(4...6)(),
       nil,
       KEYWORD_NOT(0...3)("not"),
       nil,
       nil,
       nil,
       nil,
       "!"
     )]
  )
)
