ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [CallNode(0...7)(
       CallNode(0...4)(
         CallNode(0...1)(
           nil,
           nil,
           IDENTIFIER(0...1)("a"),
           nil,
           nil,
           nil,
           nil,
           "a"
         ),
         DOT(1...2)("."),
         IDENTIFIER(3...4)("b"),
         nil,
         nil,
         nil,
         nil,
         "b"
       ),
       DOT(4...5)("."),
       IDENTIFIER(6...7)("c"),
       nil,
       nil,
       nil,
       nil,
       "c"
     )]
  )
)
