ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...11)(
         [ArrayNode(2...11)(
            [LambdaNode(3...7)(
               ScopeNode(3...5)([]),
               MINUS_GREATER(3...5)("->"),
               BlockParametersNode(5...7)(nil, [], (5...6), (6...7)),
               nil
             )],
            BRACKET_LEFT_ARRAY(2...3)("["),
            BRACKET_RIGHT(10...11)("]")
          )]
       ),
       nil,
       BlockNode(12...18)(
         ScopeNode(12...14)([]),
         nil,
         nil,
         (12...14),
         (15...18)
       ),
       "a"
     )]
  )
)
