ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [CallNode(0...19)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...19)(
         [ArrayNode(2...19)(
            [NilNode(4...7)(),
             CallNode(9...17)(
               nil,
               nil,
               IDENTIFIER(9...10)("b"),
               nil,
               nil,
               nil,
               BlockNode(11...17)(
                 ScopeNode(11...13)([]),
                 nil,
                 nil,
                 (11...13),
                 (14...17)
               ),
               "b"
             )],
            BRACKET_LEFT_ARRAY(2...3)("["),
            BRACKET_RIGHT(18...19)("]")
          )]
       ),
       nil,
       nil,
       "a"
     )]
  )
)
