ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [CallNode(0...10)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...9)(
         [IntegerNode(2...3)(),
          HashNode(5...9)(
            nil,
            [AssocNode(5...9)(
               IntegerNode(5...6)(),
               IntegerNode(8...9)(),
               EQUAL_GREATER(6...8)("=>")
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(9...10)(")"),
       nil,
       "f"
     )]
  )
)
