ProgramNode(0...22)(
  ScopeNode(0...0)([]),
  StatementsNode(0...22)(
    [CallNode(0...22)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...9)(
         [LambdaNode(2...9)(
            ScopeNode(2...4)([]),
            MINUS_GREATER(2...4)("->"),
            nil,
            StatementsNode(8...9)([IntegerNode(8...9)()])
          )]
       ),
       nil,
       BlockNode(14...22)(
         ScopeNode(14...16)([]),
         nil,
         StatementsNode(17...18)([IntegerNode(17...18)()]),
         (14...16),
         (19...22)
       ),
       "a"
     )]
  )
)
