ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [CallNode(0...6)(
       IntegerNode(0...1)(),
       nil,
       BANG_TILDE(2...4)("!~"),
       nil,
       ArgumentsNode(5...6)([IntegerNode(5...6)()]),
       nil,
       nil,
       "!~"
     )]
  )
)
