ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [CallNode(0...6)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...5)(
         [HashNode(2...5)(
            nil,
            [AssocSplatNode(2...5)(IntegerNode(4...5)(), (2...4))],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(5...6)(")"),
       nil,
       "a"
     )]
  )
)
