ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [CallNode(0...19)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...8)(
         [LambdaNode(2...8)(
            ScopeNode(2...4)([]),
            MINUS_GREATER(2...4)("->"),
            nil,
            StatementsNode(7...8)([IntegerNode(7...8)()])
          )]
       ),
       nil,
       BlockNode(11...19)(
         ScopeNode(11...13)([]),
         nil,
         StatementsNode(14...15)([IntegerNode(14...15)()]),
         (11...13),
         (16...19)
       ),
       "a"
     )]
  )
)
