ProgramNode(0...5)(
  ScopeNode(0...0)([]),
  StatementsNode(0...5)(
    [CallNode(0...5)(
       IntegerNode(0...1)(),
       nil,
       CARET(2...3)("^"),
       nil,
       ArgumentsNode(4...5)([IntegerNode(4...5)()]),
       nil,
       nil,
       "^"
     )]
  )
)
