ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [CallNode(0...7)(
       IntegerNode(0...1)(),
       nil,
       LESS_EQUAL_GREATER(2...5)("<=>"),
       nil,
       ArgumentsNode(6...7)([IntegerNode(6...7)()]),
       nil,
       nil,
       "<=>"
     )]
  )
)
