ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [CallNode(0...7)(
       nil,
       nil,
       IDENTIFIER(0...1)("x"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...6)(
         [BlockArgumentNode(2...6)(
            CallNode(3...6)(
              nil,
              nil,
              IDENTIFIER(3...6)("blk"),
              nil,
              nil,
              nil,
              nil,
              "blk"
            ),
            (2...3)
          )]
       ),
       PARENTHESIS_RIGHT(6...7)(")"),
       nil,
       "x"
     )]
  )
)
