ProgramNode(0...5)(
  ScopeNode(0...0)([]),
  StatementsNode(0...5)(
    [CallNode(0...5)(
       IntegerNode(0...1)(),
       COLON_COLON(1...3)("::"),
       nil,
       PARENTHESIS_LEFT(3...4)("("),
       nil,
       PARENTHESIS_RIGHT(4...5)(")"),
       nil,
       "call"
     )]
  )
)
