ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       ConstantReadNode(0...1)(),
       COLON_COLON(1...3)("::"),
       IDENTIFIER(3...4)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
