ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [CallNode(0...7)(
       SelfNode(0...4)(),
       nil,
       BRACKET_LEFT_RIGHT(4...5)("["),
       BRACKET_LEFT(4...5)("["),
       ArgumentsNode(5...6)([IntegerNode(5...6)()]),
       BRACKET_RIGHT(6...7)("]"),
       nil,
       "[]"
     )]
  )
)
