ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       IntegerNode(0...1)(),
       DOT(1...2)("."),
       nil,
       PARENTHESIS_LEFT(2...3)("("),
       nil,
       PARENTHESIS_RIGHT(3...4)(")"),
       nil,
       "call"
     )]
  )
)
