ProgramNode(0...2)(
  ScopeNode(0...0)([]),
  StatementsNode(0...2)(
    [CallNode(0...2)(
       IntegerNode(1...2)(),
       nil,
       BANG(0...1)("!"),
       nil,
       nil,
       nil,
       nil,
       "!"
     )]
  )
)
