ProgramNode(0...5)(
  ScopeNode(0...0)([]),
  StatementsNode(0...5)(
    [CallNode(0...5)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...3)([IntegerNode(2...3)()]),
       PARENTHESIS_RIGHT(4...5)(")"),
       nil,
       "f"
     )]
  )
)
