ProgramNode(0...28)(
  ScopeNode(0...0)([]),
  StatementsNode(0...28)(
    [CaseNode(0...28)(
       SymbolNode(5...7)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...7)("a"),
         nil,
         "a"
       ),
       [InNode(8...24)(
          HashPatternNode(11...19)(
            ConstantReadNode(11...12)(),
            [AssocNode(13...18)(
               SymbolNode(13...15)(
                 nil,
                 LABEL(13...14)("a"),
                 LABEL_END(14...15)(":"),
                 "a"
               ),
               IntegerNode(16...18)(),
               nil
             )],
            nil,
            (12...13),
            (18...19)
          ),
          StatementsNode(22...24)(
            [SymbolNode(22...24)(
               SYMBOL_BEGIN(22...23)(":"),
               IDENTIFIER(23...24)("d"),
               nil,
               "d"
             )]
          ),
          (8...10),
          nil
        )],
       nil,
       (0...4),
       (25...28)
     )]
  )
)
