ProgramNode(0...43)(
  ScopeNode(0...0)([]),
  StatementsNode(0...43)(
    [CaseNode(0...43)(
       SymbolNode(5...7)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...7)("a"),
         nil,
         "a"
       ),
       [InNode(8...34)(
          HashPatternNode(11...29)(
            nil,
            [AssocNode(13...19)(
               SymbolNode(13...15)(
                 nil,
                 LABEL(13...14)("b"),
                 LABEL_END(14...15)(":"),
                 "b"
               ),
               StringNode(16...19)(
                 STRING_BEGIN(16...17)("'"),
                 STRING_CONTENT(17...18)("c"),
                 STRING_END(18...19)("'"),
                 "c"
               ),
               nil
             ),
             AssocNode(21...27)(
               SymbolNode(21...23)(
                 nil,
                 LABEL(21...22)("d"),
                 LABEL_END(22...23)(":"),
                 "d"
               ),
               StringNode(24...27)(
                 STRING_BEGIN(24...25)("\""),
                 STRING_CONTENT(25...26)("e"),
                 STRING_END(26...27)("\""),
                 "e"
               ),
               nil
             )],
            nil,
            (11...12),
            (28...29)
          ),
          StatementsNode(37...39)(
            [SymbolNode(37...39)(
               SYMBOL_BEGIN(37...38)(":"),
               IDENTIFIER(38...39)("f"),
               nil,
               "f"
             )]
          ),
          (8...10),
          (30...34)
        )],
       nil,
       (0...4),
       (40...43)
     )]
  )
)
