ProgramNode(0...29)(
  ScopeNode(0...0)([IDENTIFIER(18...19)("d")]),
  StatementsNode(0...29)(
    [CaseNode(0...29)(
       SymbolNode(5...7)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...7)("a"),
         nil,
         "a"
       ),
       [InNode(8...25)(
          ArrayPatternNode(11...20)(
            ConstantReadNode(11...12)(),
            [CapturePatternNode(13...19)(
               ConstantReadNode(13...14)(),
               LocalVariableWriteNode(18...19)((18...19), nil, nil, 0),
               (15...17)
             )],
            nil,
            [],
            (12...13),
            (19...20)
          ),
          StatementsNode(23...25)(
            [SymbolNode(23...25)(
               SYMBOL_BEGIN(23...24)(":"),
               IDENTIFIER(24...25)("d"),
               nil,
               "d"
             )]
          ),
          (8...10),
          nil
        )],
       nil,
       (0...4),
       (26...29)
     )]
  )
)
