ProgramNode(0...31)(
  ScopeNode(0...0)([]),
  StatementsNode(0...31)(
    [CaseNode(0...31)(
       SymbolNode(5...7)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...7)("a"),
         nil,
         "a"
       ),
       [InNode(8...27)(
          ArrayPatternNode(11...22)(
            nil,
            [],
            SplatNode(12...13)(USTAR(12...13)("*"), nil),
            [SymbolNode(15...17)(
               SYMBOL_BEGIN(15...16)(":"),
               IDENTIFIER(16...17)("b"),
               nil,
               "b"
             ),
             SymbolNode(19...21)(
               SYMBOL_BEGIN(19...20)(":"),
               IDENTIFIER(20...21)("c"),
               nil,
               "c"
             )],
            (11...12),
            (21...22)
          ),
          StatementsNode(25...27)(
            [SymbolNode(25...27)(
               SYMBOL_BEGIN(25...26)(":"),
               IDENTIFIER(26...27)("d"),
               nil,
               "d"
             )]
          ),
          (8...10),
          nil
        )],
       nil,
       (0...4),
       (28...31)
     )]
  )
)
