ProgramNode(0...32)(
  ScopeNode(0...0)([]),
  StatementsNode(0...32)(
    [CaseNode(0...32)(
       SymbolNode(5...7)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...7)("a"),
         nil,
         "a"
       ),
       [InNode(8...23)(
          HashPatternNode(11...18)(
            nil,
            [AssocNode(11...18)(
               SymbolNode(11...13)(
                 nil,
                 LABEL(11...12)("b"),
                 LABEL_END(12...13)(":"),
                 "b"
               ),
               TrueNode(14...18)(),
               nil
             )],
            nil,
            nil,
            nil
          ),
          StatementsNode(26...28)(
            [SymbolNode(26...28)(
               SYMBOL_BEGIN(26...27)(":"),
               IDENTIFIER(27...28)("c"),
               nil,
               "c"
             )]
          ),
          (8...10),
          (19...23)
        )],
       nil,
       (0...4),
       (29...32)
     )]
  )
)
