ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [IfNode(0...10)(
       KEYWORD_IF(0...2)("if"),
       CallNode(3...5)(
         IntegerNode(4...5)(),
         nil,
         UMINUS_NUM(3...4)("-"),
         nil,
         nil,
         nil,
         nil,
         "-@"
       ),
       nil,
       nil,
       KEYWORD_END(7...10)("end")
     )]
  )
)
