ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [DefinedNode(0...12)(
       PARENTHESIS_LEFT(8...9)("("),
       IntegerNode(9...11)(),
       PARENTHESIS_RIGHT(11...12)(")"),
       (0...8)
     )]
  )
)
