ProgramNode(0...26)(
  ScopeNode(0...0)([]),
  StatementsNode(0...26)(
    [DefNode(0...26)(
       IDENTIFIER(4...7)("fun"),
       nil,
       ParametersNode(8...16)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(8...16)(
            LABEL(8...11)("kw:"),
            SymbolNode(12...16)(
              SYMBOL_BEGIN(12...13)(":"),
              IDENTIFIER(13...16)("val"),
              nil,
              "val"
            )
          )],
         nil,
         nil
       ),
       StatementsNode(19...21)([LocalVariableReadNode(19...21)(0)]),
       ScopeNode(0...3)([LABEL(8...10)("kw")]),
       (0...3),
       nil,
       (7...8),
       (16...17),
       nil,
       (23...26)
     )]
  )
)
