ProgramNode(0...41)(
  ScopeNode(0...0)([]),
  StatementsNode(0...41)(
    [DefNode(0...41)(
       IDENTIFIER(4...5)("a"),
       nil,
       ParametersNode(6...18)(
         [RequiredParameterNode(6...7)(),
          RequiredParameterNode(9...10)(),
          RequiredParameterNode(12...13)()],
         [],
         [],
         nil,
         [],
         ForwardingParameterNode(15...18)(),
         nil
       ),
       StatementsNode(21...36)(
         [CallNode(21...36)(
            nil,
            nil,
            IDENTIFIER(21...22)("b"),
            PARENTHESIS_LEFT(22...23)("("),
            ArgumentsNode(23...35)(
              [SymbolNode(23...27)(
                 SYMBOL_BEGIN(23...24)(":"),
                 IDENTIFIER(24...27)("get"),
                 nil,
                 "get"
               ),
               LocalVariableReadNode(29...30)(0),
               ForwardingArgumentsNode(32...35)()]
            ),
            PARENTHESIS_RIGHT(35...36)(")"),
            nil,
            "b"
          )]
       ),
       ScopeNode(0...3)(
         [IDENTIFIER(6...7)("x"),
          IDENTIFIER(9...10)("y"),
          IDENTIFIER(12...13)("z"),
          UDOT_DOT_DOT(15...18)("...")]
       ),
       (0...3),
       nil,
       (5...6),
       (18...19),
       nil,
       (38...41)
     )]
  )
)
