ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [DefNode(0...19)(
       IDENTIFIER(4...5)("a"),
       nil,
       ParametersNode(6...14)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(6...10)(
            LABEL(6...8)("b:"),
            IntegerNode(9...10)()
          )],
         KeywordRestParameterNode(12...14)(USTAR_STAR(12...14)("**"), nil),
         nil
       ),
       nil,
       ScopeNode(0...3)([LABEL(6...7)("b"), USTAR_STAR(12...14)("**")]),
       (0...3),
       nil,
       (5...6),
       (14...15),
       nil,
       (16...19)
     )]
  )
)
