ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [DefNode(0...19)(
       IDENTIFIER(4...8)("exec"),
       nil,
       nil,
       StatementsNode(13...19)(
         [CallNode(13...19)(
            nil,
            nil,
            IDENTIFIER(13...19)("system"),
            nil,
            nil,
            nil,
            nil,
            "system"
          )]
       ),
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       (8...9),
       (9...10),
       (11...12),
       nil
     )]
  )
)
