ProgramNode(0...17)(
  ScopeNode(0...0)([]),
  StatementsNode(0...17)(
    [DefNode(0...17)(
       IDENTIFIER(4...5)("x"),
       nil,
       ParametersNode(6...11)(
         [],
         [],
         [],
         nil,
         [],
         NoKeywordsParameterNode(6...11)((6...8), (8...11)),
         nil
       ),
       nil,
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       (5...6),
       (11...12),
       nil,
       (14...17)
     )]
  )
)
