ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [DefNode(0...19)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...14)(
         [],
         [OptionalParameterNode(6...11)(
            IDENTIFIER(6...7)("a"),
            EQUAL(7...8)("="),
            NilNode(8...11)()
          )],
         [RequiredParameterNode(13...14)()],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([IDENTIFIER(6...7)("a"), IDENTIFIER(13...14)("b")]),
       (0...3),
       nil,
       (5...6),
       (14...15),
       nil,
       (16...19)
     )]
  )
)
