ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [DefNode(0...23)(
       IDENTIFIER(4...5)("a"),
       nil,
       ParametersNode(6...9)(
         [],
         [],
         [],
         nil,
         [],
         ForwardingParameterNode(6...9)(),
         nil
       ),
       StatementsNode(12...18)(
         [CallNode(12...18)(
            nil,
            nil,
            IDENTIFIER(12...13)("b"),
            PARENTHESIS_LEFT(13...14)("("),
            ArgumentsNode(14...17)([ForwardingArgumentsNode(14...17)()]),
            PARENTHESIS_RIGHT(17...18)(")"),
            nil,
            "b"
          )]
       ),
       ScopeNode(0...3)([UDOT_DOT_DOT(6...9)("...")]),
       (0...3),
       nil,
       (5...6),
       (9...10),
       nil,
       (20...23)
     )]
  )
)
