ProgramNode(0...17)(
  ScopeNode(0...0)([]),
  StatementsNode(0...17)(
    [DefNode(0...17)(
       IDENTIFIER(4...8)("exec"),
       nil,
       nil,
       StatementsNode(11...17)(
         [CallNode(11...17)(
            nil,
            nil,
            IDENTIFIER(11...17)("system"),
            nil,
            nil,
            nil,
            nil,
            "system"
          )]
       ),
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       nil,
       nil,
       (9...10),
       nil
     )]
  )
)
