ProgramNode(0...24)(
  ScopeNode(0...0)([]),
  StatementsNode(0...24)(
    [DefNode(0...24)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...19)(
         [RequiredParameterNode(6...7)()],
         [],
         [],
         nil,
         [KeywordParameterNode(9...13)(
            LABEL(9...11)("b:"),
            IntegerNode(12...13)()
          ),
          KeywordParameterNode(15...19)(
            LABEL(15...17)("c:"),
            IntegerNode(18...19)()
          )],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)(
         [IDENTIFIER(6...7)("a"), LABEL(9...10)("b"), LABEL(15...16)("c")]
       ),
       (0...3),
       nil,
       (5...6),
       (19...20),
       nil,
       (21...24)
     )]
  )
)
