ProgramNode(0...14)(
  ScopeNode(0...0)([]),
  StatementsNode(0...14)(
    [DefNode(0...14)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...10)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(6...10)(
            LABEL(6...8)("a:"),
            IntegerNode(9...10)()
          )],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([LABEL(6...7)("a")]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (11...14)
     )]
  )
)
