ProgramNode(0...28)(
  ScopeNode(0...0)([]),
  StatementsNode(0...28)(
    [ClassNode(0...28)(
       ScopeNode(0...5)([]),
       KEYWORD_CLASS(0...5)("class"),
       ConstantReadNode(6...7)(),
       nil,
       nil,
       StatementsNode(10...24)(
         [DefNode(10...24)(
            EQUAL_EQUAL(14...16)("=="),
            nil,
            ParametersNode(17...18)(
              [RequiredParameterNode(17...18)()],
              [],
              [],
              nil,
              [],
              nil,
              nil
            ),
            StatementsNode(22...24)([IntegerNode(22...24)()]),
            ScopeNode(10...13)([IDENTIFIER(17...18)("o")]),
            (10...13),
            nil,
            (16...17),
            (18...19),
            (20...21),
            nil
          )]
       ),
       KEYWORD_END(25...28)("end")
     )]
  )
)
