ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [DefNode(0...19)(
       IDENTIFIER(9...10)("a"),
       SelfNode(4...8)(),
       ParametersNode(11...15)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(11...15)(
            LABEL(11...13)("b:"),
            IntegerNode(14...15)()
          )],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([LABEL(11...12)("b")]),
       (0...3),
       (8...9),
       nil,
       nil,
       nil,
       (16...19)
     )]
  )
)
