ProgramNode(0...30)(
  ScopeNode(0...0)([]),
  StatementsNode(0...30)(
    [CallNode(0...30)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       nil,
       ArgumentsNode(2...30)(
         [DefNode(2...30)(
            IDENTIFIER(11...12)("b"),
            SelfNode(6...10)(),
            nil,
            StatementsNode(14...25)(
              [CallNode(14...25)(
                 CallNode(14...15)(
                   nil,
                   nil,
                   IDENTIFIER(14...15)("x"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "x"
                 ),
                 DOT(15...16)("."),
                 IDENTIFIER(16...17)("y"),
                 nil,
                 nil,
                 nil,
                 BlockNode(18...25)(
                   ScopeNode(18...20)([]),
                   nil,
                   StatementsNode(0...0)([]),
                   (18...20),
                   (22...25)
                 ),
                 "y"
               )]
            ),
            ScopeNode(2...5)([]),
            (2...5),
            (10...11),
            nil,
            nil,
            nil,
            (27...30)
          )]
       ),
       nil,
       nil,
       "p"
     )]
  )
)
