ProgramNode(0...33)(
  ScopeNode(0...0)([]),
  StatementsNode(0...33)(
    [ClassNode(0...33)(
       ScopeNode(0...5)([]),
       KEYWORD_CLASS(0...5)("class"),
       ConstantReadNode(6...7)(),
       nil,
       nil,
       StatementsNode(10...29)(
         [DefNode(10...29)(
            EQUAL_EQUAL(19...21)("=="),
            SelfNode(14...18)(),
            ParametersNode(22...23)(
              [RequiredParameterNode(22...23)()],
              [],
              [],
              nil,
              [],
              nil,
              nil
            ),
            StatementsNode(27...29)([IntegerNode(27...29)()]),
            ScopeNode(10...13)([IDENTIFIER(22...23)("o")]),
            (10...13),
            (18...19),
            (21...22),
            (23...24),
            (25...26),
            nil
          )]
       ),
       KEYWORD_END(30...33)("end")
     )]
  )
)
