ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [InterpolatedStringNode(0...12)(
       STRING_BEGIN(0...1)("\""),
       [StringInterpolatedNode(1...7)(
          EMBEXPR_BEGIN(1...3)("\#{"),
          StatementsNode(3...6)(
            [StringNode(3...6)(
               STRING_BEGIN(3...4)("'"),
               STRING_CONTENT(4...5)("a"),
               STRING_END(5...6)("'"),
               "a"
             )]
          ),
          EMBEXPR_END(6...7)("}")
        ),
        StringInterpolatedNode(7...11)(
          EMBEXPR_BEGIN(7...9)("\#{"),
          StatementsNode(9...10)(
            [CallNode(9...10)(
               nil,
               nil,
               IDENTIFIER(9...10)("b"),
               nil,
               nil,
               nil,
               nil,
               "b"
             )]
          ),
          EMBEXPR_END(10...11)("}")
        )],
       STRING_END(11...12)("\"")
     )]
  )
)
