ProgramNode(0...32)(
  ScopeNode(0...0)([]),
  StatementsNode(0...32)(
    [AliasNode(0...17)(
       InterpolatedSymbolNode(6...11)(
         SYMBOL_BEGIN(6...8)(":\""),
         [StringNode(8...10)(nil, STRING_CONTENT(8...10)("<<"), nil, "<<")],
         STRING_END(10...11)("\"")
       ),
       InterpolatedSymbolNode(12...17)(
         SYMBOL_BEGIN(12...14)(":\""),
         [StringNode(14...16)(nil, STRING_CONTENT(14...16)(">>"), nil, ">>")],
         STRING_END(16...17)("\"")
       ),
       (0...5)
     ),
     AliasNode(19...32)(
       SymbolNode(25...28)(
         SYMBOL_BEGIN(25...26)(":"),
         LESS_LESS(26...28)("<<"),
         nil,
         "<<"
       ),
       SymbolNode(29...32)(
         SYMBOL_BEGIN(29...30)(":"),
         GREATER_GREATER(30...32)(">>"),
         nil,
         ">>"
       ),
       (19...24)
     )]
  )
)
