ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [DefNode(0...15)(
       IDENTIFIER(4...5)("x"),
       nil,
       ParametersNode(6...10)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(6...10)(
            LABEL(6...8)("k:"),
            IntegerNode(8...10)()
          )],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([LABEL(6...7)("k")]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (12...15)
     )]
  )
)
