ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [IfNode(0...16)(
       KEYWORD_IF(0...2)("if"),
       RangeNode(3...7)(
         CallNode(3...4)(
           nil,
           nil,
           IDENTIFIER(3...4)("a"),
           nil,
           nil,
           nil,
           nil,
           "a"
         ),
         CallNode(6...7)(
           nil,
           nil,
           IDENTIFIER(6...7)("b"),
           nil,
           nil,
           nil,
           nil,
           "b"
         ),
         (4...6)
       ),
       nil,
       nil,
       KEYWORD_END(13...16)("end")
     )]
  )
)
