ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [IfNode(0...10)(
       KEYWORD_IF_MODIFIER(3...5)("if"),
       TrueNode(6...10)(),
       StatementsNode(0...3)([FloatNode(0...3)()]),
       nil,
       nil
     )]
  )
)
