ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [InterpolatedStringNode(0...19)(
       HEREDOC_START(0...7)("<<'eot'"),
       [StringNode(9...15)(
          nil,
          STRING_CONTENT(9...15)("body\r\n"),
          nil,
          "body\r\n"
        )],
       HEREDOC_END(15...19)("eot\n")
     )]
  )
)
