ProgramNode(0...22)(
  ScopeNode(0...0)([]),
  StatementsNode(0...22)(
    [CallNode(0...22)(
       InterpolatedStringNode(0...16)(
         HEREDOC_START(0...5)("<<END"),
         [StringNode(7...12)(
            nil,
            STRING_CONTENT(7...12)("blah\n"),
            nil,
            "blah\n"
          )],
         HEREDOC_END(12...16)("END\n")
       ),
       DOT(16...17)("."),
       IDENTIFIER(17...22)("strip"),
       nil,
       nil,
       nil,
       nil,
       "strip"
     )]
  )
)
