ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [InterpolatedStringNode(0...7)(
       HEREDOC_START(0...4)("<<~A"),
       [],
       HEREDOC_END(5...7)("A\n")
     )]
  )
)
