ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [InterpolatedStringNode(0...23)(
       HEREDOC_START(0...10)("<<-HEREDOC"),
       [StringNode(11...15)(
          nil,
          STRING_CONTENT(11...15)("\#${\n"),
          nil,
          "\#${\n"
        )],
       HEREDOC_END(15...23)("HEREDOC\n")
     )]
  )
)
