ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [MatchPredicateNode(0...16)(
       StringNode(0...6)(
         STRING_BEGIN(0...1)("'"),
         STRING_CONTENT(1...5)("woot"),
         STRING_END(5...6)("'"),
         "woot"
       ),
       ConstantReadNode(10...16)(),
       (7...9)
     )]
  )
)
