ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [IfNode(0...12)(
       KEYWORD_IF_MODIFIER(5...7)("if"),
       TrueNode(8...12)(),
       StatementsNode(0...5)([IntegerNode(0...5)()]),
       nil,
       nil
     )]
  )
)
