ProgramNode(0...17)(
  ScopeNode(0...0)([]),
  StatementsNode(0...17)(
    [CallNode(0...17)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...17)(
         ScopeNode(2...3)([LABEL(5...6)("b"), IDENTIFIER(13...14)("c")]),
         BlockParametersNode(4...15)(
           ParametersNode(5...14)(
             [],
             [],
             [],
             nil,
             [KeywordParameterNode(5...9)(
                LABEL(5...7)("b:"),
                IntegerNode(8...9)()
              )],
             KeywordRestParameterNode(11...14)(
               USTAR_STAR(11...13)("**"),
               IDENTIFIER(13...14)("c")
             ),
             nil
           ),
           [],
           (4...5),
           (14...15)
         ),
         nil,
         (2...3),
         (16...17)
       ),
       "a"
     )]
  )
)
