ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...18)(
         ScopeNode(2...3)([IDENTIFIER(5...6)("a"), IDENTIFIER(14...15)("b")]),
         BlockParametersNode(4...16)(
           ParametersNode(5...15)(
             [],
             [OptionalParameterNode(5...11)(
                IDENTIFIER(5...6)("a"),
                EQUAL(7...8)("="),
                IntegerNode(9...11)()
              )],
             [],
             RestParameterNode(13...15)(
               USTAR(13...14)("*"),
               IDENTIFIER(14...15)("b")
             ),
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (15...16)
         ),
         nil,
         (2...3),
         (17...18)
       ),
       "f"
     )]
  )
)
