ProgramNode(0...25)(
  ScopeNode(0...0)([]),
  StatementsNode(0...25)(
    [CallNode(0...25)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...25)(
         ScopeNode(2...3)(
           [IDENTIFIER(5...6)("a"),
            IDENTIFIER(14...15)("b"),
            IDENTIFIER(17...18)("c"),
            IDENTIFIER(21...22)("d")]
         ),
         BlockParametersNode(4...23)(
           ParametersNode(5...22)(
             [],
             [OptionalParameterNode(5...11)(
                IDENTIFIER(5...6)("a"),
                EQUAL(7...8)("="),
                IntegerNode(9...11)()
              )],
             [RequiredParameterNode(17...18)()],
             RestParameterNode(13...15)(
               USTAR(13...14)("*"),
               IDENTIFIER(14...15)("b")
             ),
             [],
             nil,
             BlockParameterNode(20...22)(IDENTIFIER(21...22)("d"), (20...21))
           ),
           [],
           (4...5),
           (22...23)
         ),
         nil,
         (2...3),
         (24...25)
       ),
       "f"
     )]
  )
)
