ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...18)(
         ScopeNode(2...3)(
           [IDENTIFIER(5...6)("a"),
            IDENTIFIER(8...9)("b"),
            IDENTIFIER(14...15)("c")]
         ),
         BlockParametersNode(4...16)(
           ParametersNode(5...15)(
             [RequiredParameterNode(5...6)()],
             [OptionalParameterNode(8...12)(
                IDENTIFIER(8...9)("b"),
                EQUAL(9...10)("="),
                IntegerNode(10...12)()
              )],
             [RequiredParameterNode(14...15)()],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (15...16)
         ),
         nil,
         (2...3),
         (17...18)
       ),
       "f"
     )]
  )
)
