ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [CallNode(0...11)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...11)(
         ScopeNode(2...3)([IDENTIFIER(5...6)("a"), IDENTIFIER(7...8)("b")]),
         BlockParametersNode(4...9)(
           ParametersNode(5...8)(
             [RequiredParameterNode(5...6)(), RequiredParameterNode(7...8)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (8...9)
         ),
         nil,
         (2...3),
         (10...11)
       ),
       "f"
     )]
  )
)
