ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [CallNode(0...12)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...12)(
         ScopeNode(2...3)([LABEL(5...6)("b")]),
         BlockParametersNode(4...10)(
           ParametersNode(5...9)(
             [],
             [],
             [],
             nil,
             [KeywordParameterNode(5...9)(
                LABEL(5...7)("b:"),
                IntegerNode(8...9)()
              )],
             nil,
             nil
           ),
           [],
           (4...5),
           (9...10)
         ),
         nil,
         (2...3),
         (11...12)
       ),
       "a"
     )]
  )
)
