ProgramNode(0...17)(
  ScopeNode(0...0)([]),
  StatementsNode(0...17)(
    [CallNode(0...17)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...17)(
         ScopeNode(2...3)([IDENTIFIER(5...6)("a"), IDENTIFIER(9...10)("b")]),
         BlockParametersNode(4...15)(
           ParametersNode(5...14)(
             [RequiredParameterNode(5...6)(),
              RequiredDestructuredParameterNode(8...14)(
                [RequiredParameterNode(9...10)(),
                 SplatNode(12...13)(USTAR(12...13)("*"), nil)],
                PARENTHESIS_LEFT(8...9)("("),
                PARENTHESIS_RIGHT(13...14)(")")
              )],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (14...15)
         ),
         nil,
         (2...3),
         (16...17)
       ),
       "f"
     )]
  )
)
