ProgramNode(0...21)(
  ScopeNode(0...0)([]),
  StatementsNode(0...21)(
    [CallNode(0...21)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...21)(
         ScopeNode(2...3)(
           [IDENTIFIER(5...6)("a"),
            IDENTIFIER(9...10)("b"),
            IDENTIFIER(13...14)("c"),
            IDENTIFIER(16...17)("d")]
         ),
         BlockParametersNode(4...19)(
           ParametersNode(5...18)(
             [RequiredParameterNode(5...6)(),
              RequiredDestructuredParameterNode(8...18)(
                [RequiredParameterNode(9...10)(),
                 SplatNode(12...14)(
                   USTAR(12...13)("*"),
                   RequiredParameterNode(13...14)()
                 ),
                 RequiredParameterNode(16...17)()],
                PARENTHESIS_LEFT(8...9)("("),
                PARENTHESIS_RIGHT(17...18)(")")
              )],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (18...19)
         ),
         nil,
         (2...3),
         (20...21)
       ),
       "f"
     )]
  )
)
