ProgramNode(0...43)(
  ScopeNode(0...0)([]),
  StatementsNode(0...43)(
    [CallNode(0...4)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       ArgumentsNode(2...4)(
         [LambdaNode(2...4)(
            ScopeNode(2...4)([]),
            MINUS_GREATER(2...4)("->"),
            nil,
            nil
          )]
       ),
       nil,
       nil,
       "f"
     ),
     CallNode(13...17)(
       nil,
       nil,
       IDENTIFIER(13...14)("f"),
       nil,
       ArgumentsNode(15...17)(
         [LambdaNode(15...17)(
            ScopeNode(15...17)([]),
            MINUS_GREATER(15...17)("->"),
            nil,
            nil
          )]
       ),
       nil,
       nil,
       "f"
     ),
     CallNode(22...28)(
       nil,
       nil,
       IDENTIFIER(22...23)("f"),
       nil,
       ArgumentsNode(24...28)(
         [LambdaNode(24...28)(
            ScopeNode(24...26)([]),
            MINUS_GREATER(24...26)("->"),
            BlockParametersNode(26...28)(nil, [], (26...27), (27...28)),
            nil
          )]
       ),
       nil,
       nil,
       "f"
     ),
     CallNode(37...43)(
       nil,
       nil,
       IDENTIFIER(37...38)("f"),
       nil,
       ArgumentsNode(39...43)(
         [LambdaNode(39...43)(
            ScopeNode(39...41)([]),
            MINUS_GREATER(39...41)("->"),
            BlockParametersNode(41...43)(nil, [], (41...42), (42...43)),
            nil
          )]
       ),
       nil,
       nil,
       "f"
     )]
  )
)
