ProgramNode(0...14)(
  ScopeNode(0...0)([IDENTIFIER(0...1)("a")]),
  StatementsNode(0...14)(
    [LocalVariableWriteNode(0...14)(
       (0...1),
       RescueModifierNode(4...14)(
         IntegerNode(4...5)(),
         KEYWORD_RESCUE_MODIFIER(6...12)("rescue"),
         IntegerNode(13...14)()
       ),
       (2...3),
       0
     )]
  )
)
