ProgramNode(0...9)(
  ScopeNode(0...0)([IDENTIFIER(0...1)("a")]),
  StatementsNode(0...9)(
    [LocalVariableWriteNode(0...9)(
       (0...1),
       CallNode(4...9)(
         CallNode(4...5)(
           nil,
           nil,
           IDENTIFIER(4...5)("b"),
           nil,
           nil,
           nil,
           nil,
           "b"
         ),
         DOT(5...6)("."),
         IDENTIFIER(6...7)("c"),
         nil,
         ArgumentsNode(8...9)([IntegerNode(8...9)()]),
         nil,
         nil,
         "c"
       ),
       (2...3),
       0
     )]
  )
)
