ProgramNode(18...90)(
  ScopeNode(0...0)([]),
  StatementsNode(18...90)(
    [ClassNode(18...90)(
       ScopeNode(18...23)([]),
       KEYWORD_CLASS(18...23)("class"),
       ConstantReadNode(24...52)(),
       nil,
       nil,
       StatementsNode(54...86)(
         [DefNode(54...86)(
            IDENTIFIER(63...65)("è"),
            SelfNode(58...62)(),
            nil,
            StatementsNode(67...81)(
              [LocalVariableWriteNode(67...81)(
                 (67...72),
                 SymbolNode(75...81)(
                   SYMBOL_BEGIN(75...76)(":"),
                   IDENTIFIER(76...81)("però"),
                   nil,
                   "però"
                 ),
                 (73...74),
                 0
               )]
            ),
            ScopeNode(54...57)([IDENTIFIER(67...72)("così")]),
            (54...57),
            (62...63),
            nil,
            nil,
            nil,
            (83...86)
          )]
       ),
       KEYWORD_END(87...90)("end")
     )]
  )
)
