ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [CallNode(0...7)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(1...2)("."),
       IDENTIFIER(2...3)("f"),
       PARENTHESIS_LEFT(3...4)("("),
       ArgumentsNode(4...5)([IntegerNode(4...5)()]),
       PARENTHESIS_RIGHT(6...7)(")"),
       nil,
       "f"
     )]
  )
)
