ProgramNode(24...77)(
  ScopeNode(0...0)([]),
  StatementsNode(24...77)(
    [ModuleNode(24...77)(
       ScopeNode(24...30)([]),
       KEYWORD_MODULE(24...30)("module"),
       ConstantReadNode(31...32)(),
       StatementsNode(46...73)(
         [DefNode(46...73)(
            IDENTIFIER(50...54)("blah"),
            nil,
            nil,
            nil,
            ScopeNode(46...49)([]),
            (46...49),
            nil,
            nil,
            nil,
            nil,
            (70...73)
          )]
       ),
       KEYWORD_END(74...77)("end")
     )]
  )
)
