ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(2...3)("."),
       IDENTIFIER(3...4)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
