ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [OperatorAssignmentNode(0...9)(
       CallNode(0...4)(
         ConstantReadNode(0...1)(),
         COLON_COLON(1...3)("::"),
         IDENTIFIER(3...4)("b"),
         nil,
         nil,
         nil,
         nil,
         "b="
       ),
       PLUS_EQUAL(5...7)("+="),
       IntegerNode(8...9)()
     )]
  )
)
