ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [OperatorOrAssignmentNode(0...11)(
       CallNode(0...3)(
         CallNode(0...1)(
           nil,
           nil,
           IDENTIFIER(0...1)("a"),
           nil,
           nil,
           nil,
           nil,
           "a"
         ),
         DOT(1...2)("."),
         IDENTIFIER(2...3)("b"),
         nil,
         nil,
         nil,
         nil,
         "b="
       ),
       CallNode(8...11)(
         nil,
         nil,
         IDENTIFIER(8...9)("c"),
         nil,
         ArgumentsNode(10...11)([IntegerNode(10...11)()]),
         nil,
         nil,
         "c"
       ),
       (4...7)
     )]
  )
)
