ProgramNode(0...26)(
  ScopeNode(0...0)([]),
  StatementsNode(0...26)(
    [IfNode(0...26)(
       KEYWORD_IF(0...2)("if"),
       CallNode(3...15)(
         CallNode(7...15)(
           CallNode(7...10)(
             nil,
             nil,
             IDENTIFIER(7...10)("var"),
             nil,
             nil,
             nil,
             nil,
             "var"
           ),
           DOT(10...11)("."),
           IDENTIFIER(11...15)("nil?"),
           nil,
           nil,
           nil,
           nil,
           "nil?"
         ),
         nil,
         KEYWORD_NOT(3...6)("not"),
         nil,
         nil,
         nil,
         nil,
         "!"
       ),
       StatementsNode(21...26)(
         [StringNode(21...26)(
            STRING_BEGIN(21...22)("'"),
            STRING_CONTENT(22...25)("foo"),
            STRING_END(25...26)("'"),
            "foo"
          )]
       ),
       ElseNode(27...41)(
         KEYWORD_ELSE(27...31)("else"),
         StatementsNode(32...37)(
           [StringNode(32...37)(
              STRING_BEGIN(32...33)("'"),
              STRING_CONTENT(33...36)("bar"),
              STRING_END(36...37)("'"),
              "bar"
            )]
         ),
         KEYWORD_END(38...41)("end")
       ),
       KEYWORD_END(38...41)("end")
     )]
  )
)
