ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [RangeNode(0...4)(IntegerNode(0...1)(), nil, (1...4)),
     RangeNode(7...11)(
       CallNode(7...8)(
         nil,
         nil,
         IDENTIFIER(7...8)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       nil,
       (8...11)
     ),
     CallNode(14...15)(
       nil,
       nil,
       IDENTIFIER(14...15)("c"),
       nil,
       nil,
       nil,
       nil,
       "c"
     )]
  )
)
