ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [DefNode(0...11)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...7)(
         [RequiredParameterNode(6...7)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([IDENTIFIER(6...7)("a")]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (8...11)
     )]
  )
)
