ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [CallNode(0...6)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...4)([InstanceVariableReadNode(2...4)()]),
       PARENTHESIS_RIGHT(5...6)(")"),
       nil,
       "a"
     )]
  )
)
