ProgramNode(0...26)(
  ScopeNode(0...0)([]),
  StatementsNode(0...26)(
    [CaseNode(0...26)(
       IntegerNode(5...6)(),
       [InNode(7...22)(
          RangeNode(10...15)(
            CallNode(10...12)(
              IntegerNode(11...12)(),
              nil,
              UMINUS_NUM(10...11)("-"),
              nil,
              nil,
              nil,
              nil,
              "-@"
            ),
            IntegerNode(14...15)(),
            (12...14)
          ),
          StatementsNode(18...22)([TrueNode(18...22)()]),
          (7...9),
          nil
        )],
       nil,
       (0...4),
       (23...26)
     )]
  )
)
