ProgramNode(0...5)(
  ScopeNode(0...0)([]),
  StatementsNode(0...5)(
    [CallNode(0...5)(
       IntegerNode(0...1)(),
       nil,
       BRACKET_LEFT_RIGHT(1...2)("["),
       BRACKET_LEFT(1...2)("["),
       ArgumentsNode(2...3)([IntegerNode(2...3)()]),
       BRACKET_RIGHT(4...5)("]"),
       nil,
       "[]"
     )]
  )
)
