ProgramNode(0...31)(
  ScopeNode(0...0)([]),
  StatementsNode(0...31)(
    [CaseNode(0...31)(
       SymbolNode(5...7)(
         SYMBOL_BEGIN(5...6)(":"),
         IDENTIFIER(6...7)("a"),
         nil,
         "a"
       ),
       [InNode(8...27)(
          HashPatternNode(11...23)(
            ConstantReadNode(11...17)(),
            [AssocNode(18...22)(
               SymbolNode(18...20)(
                 nil,
                 LABEL(18...19)("b"),
                 LABEL_END(19...20)(":"),
                 "b"
               ),
               IntegerNode(21...22)(),
               nil
             )],
            nil,
            (17...18),
            (22...23)
          ),
          StatementsNode(26...27)([IntegerNode(26...27)()]),
          (8...10),
          nil
        )],
       nil,
       (0...4),
       (28...31)
     )]
  )
)
