ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [PreExecutionNode(0...13)(
       StatementsNode(8...11)(
         [CallNode(8...11)(
            nil,
            nil,
            IDENTIFIER(8...11)("foo"),
            nil,
            nil,
            nil,
            nil,
            "foo"
          )]
       ),
       (0...5),
       (6...7),
       (12...13)
     )]
  )
)
