ProgramNode(0...33)(
  ScopeNode(0...0)([]),
  StatementsNode(0...33)(
    [CallNode(0...1)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       nil,
       "a"
     ),
     CallNode(2...3)(
       nil,
       nil,
       IDENTIFIER(2...3)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     ),
     CallNode(32...33)(
       nil,
       nil,
       IDENTIFIER(32...33)("c"),
       nil,
       nil,
       nil,
       nil,
       "c"
     )]
  )
)
