ProgramNode(0...40)(
  ScopeNode(0...0)([]),
  StatementsNode(0...40)(
    [DefNode(0...40)(
       IDENTIFIER(4...5)("x"),
       nil,
       ParametersNode(6...7)(
         [RequiredParameterNode(6...7)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(11...35)(
         [CallNode(11...15)(
            nil,
            nil,
            IDENTIFIER(11...12)("p"),
            PARENTHESIS_LEFT(12...13)("("),
            ArgumentsNode(13...14)([LocalVariableReadNode(13...14)(0)]),
            PARENTHESIS_RIGHT(14...15)(")"),
            nil,
            "p"
          ),
          OperatorAssignmentNode(18...24)(
            LocalVariableWriteNode(18...19)((18...19), nil, nil, 0),
            STAR_EQUAL(20...22)("*="),
            IntegerNode(23...24)()
          ),
          ReturnNode(27...35)(
            KEYWORD_RETURN(27...33)("return"),
            ArgumentsNode(34...35)([LocalVariableReadNode(34...35)(0)])
          )]
       ),
       ScopeNode(0...3)([IDENTIFIER(6...7)("y")]),
       (0...3),
       nil,
       (5...6),
       (7...8),
       nil,
       (37...40)
     )]
  )
)
