ProgramNode(0...35)(
  ScopeNode(0...0)([]),
  StatementsNode(0...35)(
    [BeginNode(0...35)(
       KEYWORD_BEGIN(0...5)("begin"),
       StatementsNode(8...9)(
         [CallNode(8...9)(
            nil,
            nil,
            IDENTIFIER(8...9)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(10...20)(
         KEYWORD_RESCUE(10...16)("rescue"),
         [],
         nil,
         nil,
         StatementsNode(19...20)(
           [CallNode(19...20)(
              nil,
              nil,
              IDENTIFIER(19...20)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         RescueNode(21...31)(
           KEYWORD_RESCUE(21...27)("rescue"),
           [],
           nil,
           nil,
           StatementsNode(30...31)(
             [CallNode(30...31)(
                nil,
                nil,
                IDENTIFIER(30...31)("c"),
                nil,
                nil,
                nil,
                nil,
                "c"
              )]
           ),
           nil
         )
       ),
       nil,
       nil,
       KEYWORD_END(32...35)("end")
     )]
  )
)
