ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [PostExecutionNode(0...11)(
       StatementsNode(6...9)(
         [CallNode(6...9)(
            nil,
            nil,
            IDENTIFIER(6...9)("foo"),
            nil,
            nil,
            nil,
            nil,
            "foo"
          )]
       ),
       (0...3),
       (4...5),
       (10...11)
     )]
  )
)
