ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [RangeNode(0...6)(IntegerNode(0...1)(), IntegerNode(5...6)(), (1...4)),
     RangeNode(7...13)(
       CallNode(7...8)(
         nil,
         nil,
         IDENTIFIER(7...8)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       CallNode(12...13)(
         nil,
         nil,
         IDENTIFIER(12...13)("b"),
         nil,
         nil,
         nil,
         nil,
         "b"
       ),
       (8...11)
     ),
     CallNode(14...15)(
       nil,
       nil,
       IDENTIFIER(14...15)("c"),
       nil,
       nil,
       nil,
       nil,
       "c"
     )]
  )
)
