ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [CallNode(0...18)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(1...2)("."),
       IDENTIFIER(2...3)("b"),
       nil,
       nil,
       nil,
       BlockNode(4...18)(
         ScopeNode(4...6)([IDENTIFIER(11...12)("c")]),
         BlockParametersNode(7...14)(
           nil,
           [IDENTIFIER(11...12)("c")],
           (7...8),
           (13...14)
         ),
         nil,
         (4...6),
         (15...18)
       ),
       "b"
     )]
  )
)
