ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [CallNode(0...12)(
       nil,
       nil,
       IDENTIFIER(0...4)("puts"),
       nil,
       ArgumentsNode(5...12)(
         [HashNode(5...12)(
            nil,
            [AssocNode(5...12)(
               SymbolNode(5...9)(
                 STRING_BEGIN(5...6)("'"),
                 STRING_CONTENT(6...7)("a"),
                 LABEL_END(7...9)("':"),
                 "a"
               ),
               HashNode(10...12)(
                 BRACE_LEFT(10...11)("{"),
                 [],
                 BRACE_RIGHT(11...12)("}")
               ),
               nil
             )],
            nil
          )]
       ),
       nil,
       nil,
       "puts"
     )]
  )
)
