ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [HashNode(0...11)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(2...9)(
          SymbolNode(2...6)(
            STRING_BEGIN(2...3)("'"),
            STRING_CONTENT(3...4)("a"),
            LABEL_END(4...6)("':"),
            "a"
          ),
          SymbolNode(7...9)(
            SYMBOL_BEGIN(7...8)(":"),
            IDENTIFIER(8...9)("b"),
            nil,
            "b"
          ),
          nil
        )],
       BRACE_RIGHT(10...11)("}")
     )]
  )
)
