ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [StringNode(0...7)(
       STRING_BEGIN(0...3)("%q("),
       STRING_CONTENT(3...6)("\u0001\\'"),
       STRING_END(6...7)(")"),
       "\u0001'"
     )]
  )
)
