ProgramNode(0...45)(
  ScopeNode(0...0)([]),
  StatementsNode(0...45)(
    [RegularExpressionNode(0...5)(
       REGEXP_BEGIN(0...1)("/"),
       STRING_CONTENT(1...4)("wtf"),
       REGEXP_END(4...5)("/"),
       "wtf"
     ),
     RegularExpressionNode(7...13)(
       REGEXP_BEGIN(7...8)("/"),
       STRING_CONTENT(8...11)("wtf"),
       REGEXP_END(11...13)("/m"),
       "wtf"
     ),
     RegularExpressionNode(15...21)(
       REGEXP_BEGIN(15...16)("/"),
       STRING_CONTENT(16...19)("wtf"),
       REGEXP_END(19...21)("/n"),
       "wtf"
     ),
     RegularExpressionNode(23...30)(
       REGEXP_BEGIN(23...24)("/"),
       STRING_CONTENT(24...27)("wtf"),
       REGEXP_END(27...30)("/nm"),
       "wtf"
     ),
     RegularExpressionNode(32...45)(
       REGEXP_BEGIN(32...33)("/"),
       STRING_CONTENT(33...36)("wtf"),
       REGEXP_END(36...45)("/nmnmnmnm"),
       "wtf"
     )]
  )
)
