ProgramNode(0...14)(
  ScopeNode(0...0)([]),
  StatementsNode(0...14)(
    [CallNode(0...14)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...14)(
         [ParenthesesNode(2...14)(
            StatementsNode(3...13)(
              [RescueModifierNode(3...13)(
                 CallNode(3...4)(
                   nil,
                   nil,
                   IDENTIFIER(3...4)("b"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "b"
                 ),
                 KEYWORD_RESCUE_MODIFIER(5...11)("rescue"),
                 CallNode(12...13)(
                   nil,
                   nil,
                   IDENTIFIER(12...13)("c"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "c"
                 )
               )]
            ),
            (2...3),
            (13...14)
          )]
       ),
       nil,
       nil,
       "a"
     )]
  )
)
