ProgramNode(0...26)(
  ScopeNode(0...0)([]),
  StatementsNode(0...26)(
    [CallNode(0...26)(
       nil,
       nil,
       IDENTIFIER(0...4)("blah"),
       nil,
       nil,
       nil,
       BlockNode(5...26)(
         ScopeNode(5...7)([]),
         nil,
         BeginNode(0...26)(
           nil,
           nil,
           RescueNode(8...22)(
             KEYWORD_RESCUE(8...14)("rescue"),
             [],
             nil,
             nil,
             StatementsNode(17...22)(
               [CallNode(17...22)(
                  nil,
                  nil,
                  IDENTIFIER(17...22)("stuff"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "stuff"
                )]
             ),
             nil
           ),
           nil,
           nil,
           KEYWORD_END(23...26)("end")
         ),
         (5...7),
         (23...26)
       ),
       "blah"
     )]
  )
)
