ProgramNode(0...65)(
  ScopeNode(0...0)([]),
  StatementsNode(0...65)(
    [CallNode(0...65)(
       nil,
       nil,
       IDENTIFIER(0...3)("tap"),
       nil,
       nil,
       nil,
       BlockNode(4...65)(
         ScopeNode(4...6)([]),
         nil,
         BeginNode(0...65)(
           nil,
           StatementsNode(9...14)(
             [CallNode(9...14)(
                nil,
                nil,
                IDENTIFIER(9...14)("raise"),
                nil,
                nil,
                nil,
                nil,
                "raise"
              )]
           ),
           RescueNode(15...31)(
             KEYWORD_RESCUE(15...21)("rescue"),
             [],
             nil,
             nil,
             StatementsNode(24...31)(
               [SymbolNode(24...31)(
                  SYMBOL_BEGIN(24...25)(":"),
                  KEYWORD_RESCUE(25...31)("rescue"),
                  nil,
                  "rescue"
                )]
             ),
             nil
           ),
           ElseNode(32...51)(
             KEYWORD_ELSE(32...36)("else"),
             StatementsNode(39...44)(
               [SymbolNode(39...44)(
                  SYMBOL_BEGIN(39...40)(":"),
                  KEYWORD_ELSE(40...44)("else"),
                  nil,
                  "else"
                )]
             ),
             KEYWORD_ENSURE(45...51)("ensure")
           ),
           EnsureNode(45...65)(
             KEYWORD_ENSURE(45...51)("ensure"),
             StatementsNode(54...61)(
               [SymbolNode(54...61)(
                  SYMBOL_BEGIN(54...55)(":"),
                  KEYWORD_ENSURE(55...61)("ensure"),
                  nil,
                  "ensure"
                )]
             ),
             KEYWORD_END(62...65)("end")
           ),
           KEYWORD_END(62...65)("end")
         ),
         (4...6),
         (62...65)
       ),
       "tap"
     )]
  )
)
