ProgramNode(0...106)(
  ScopeNode(0...0)([]),
  StatementsNode(0...106)(
    [ReturnNode(0...17)(
       KEYWORD_RETURN(0...6)("return"),
       ArgumentsNode(7...17)(
         [IntegerNode(7...8)(),
          HashNode(10...17)(
            nil,
            [AssocNode(10...17)(
               SymbolNode(10...12)(
                 SYMBOL_BEGIN(10...11)(":"),
                 IDENTIFIER(11...12)("z"),
                 nil,
                 "z"
               ),
               IntegerNode(16...17)(),
               EQUAL_GREATER(13...15)("=>")
             )],
            nil
          )]
       )
     ),
     ReturnNode(19...45)(
       KEYWORD_RETURN(19...25)("return"),
       ArgumentsNode(26...45)(
         [IntegerNode(26...27)(),
          HashNode(29...45)(
            nil,
            [AssocNode(29...36)(
               SymbolNode(29...31)(
                 SYMBOL_BEGIN(29...30)(":"),
                 IDENTIFIER(30...31)("z"),
                 nil,
                 "z"
               ),
               IntegerNode(35...36)(),
               EQUAL_GREATER(32...34)("=>")
             ),
             AssocNode(38...45)(
               SymbolNode(38...40)(
                 SYMBOL_BEGIN(38...39)(":"),
                 IDENTIFIER(39...40)("w"),
                 nil,
                 "w"
               ),
               IntegerNode(44...45)(),
               EQUAL_GREATER(41...43)("=>")
             )],
            nil
          )]
       )
     ),
     ReturnNode(47...61)(
       KEYWORD_RETURN(47...53)("return"),
       ArgumentsNode(54...61)(
         [CallNode(54...61)(
            nil,
            nil,
            IDENTIFIER(54...55)("y"),
            nil,
            ArgumentsNode(56...61)(
              [HashNode(56...61)(
                 nil,
                 [AssocNode(56...61)(
                    SymbolNode(56...58)(
                      SYMBOL_BEGIN(56...57)(":"),
                      IDENTIFIER(57...58)("z"),
                      nil,
                      "z"
                    ),
                    IntegerNode(60...61)(),
                    EQUAL_GREATER(58...60)("=>")
                  )],
                 nil
               )]
            ),
            nil,
            nil,
            "y"
          )]
       )
     ),
     ReturnNode(63...75)(
       KEYWORD_RETURN(63...69)("return"),
       ArgumentsNode(70...75)(
         [CallNode(70...75)(
            nil,
            nil,
            IDENTIFIER(70...71)("y"),
            nil,
            ArgumentsNode(72...75)(
              [HashNode(72...75)(
                 nil,
                 [AssocNode(72...75)(
                    SymbolNode(72...74)(
                      nil,
                      LABEL(72...73)("z"),
                      LABEL_END(73...74)(":"),
                      "z"
                    ),
                    IntegerNode(74...75)(),
                    nil
                  )],
                 nil
               )]
            ),
            nil,
            nil,
            "y"
          )]
       )
     ),
     ReturnNode(77...90)(
       KEYWORD_RETURN(77...83)("return"),
       ArgumentsNode(84...90)(
         [CallNode(84...90)(
            nil,
            nil,
            IDENTIFIER(84...85)("y"),
            PARENTHESIS_LEFT(85...86)("("),
            ArgumentsNode(86...89)(
              [HashNode(86...89)(
                 nil,
                 [AssocNode(86...89)(
                    SymbolNode(86...88)(
                      nil,
                      LABEL(86...87)("z"),
                      LABEL_END(87...88)(":"),
                      "z"
                    ),
                    IntegerNode(88...89)(),
                    nil
                  )],
                 nil
               )]
            ),
            PARENTHESIS_RIGHT(89...90)(")"),
            nil,
            "y"
          )]
       )
     ),
     ReturnNode(92...106)(
       KEYWORD_RETURN(92...98)("return"),
       ArgumentsNode(99...106)(
         [CallNode(99...106)(
            nil,
            nil,
            IDENTIFIER(99...100)("y"),
            PARENTHESIS_LEFT(100...101)("("),
            ArgumentsNode(101...105)(
              [HashNode(101...105)(
                 nil,
                 [AssocNode(101...105)(
                    CallNode(101...102)(
                      nil,
                      nil,
                      IDENTIFIER(101...102)("z"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "z"
                    ),
                    IntegerNode(104...105)(),
                    EQUAL_GREATER(102...104)("=>")
                  )],
                 nil
               )]
            ),
            PARENTHESIS_RIGHT(105...106)(")"),
            nil,
            "y"
          )]
       )
     )]
  )
)
