ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [ArrayNode(0...13)(
       [ImaginaryNode(1...3)(IntegerNode(1...2)()),
        RationalNode(5...7)(IntegerNode(5...6)()),
        ImaginaryNode(9...12)(RationalNode(9...11)(IntegerNode(9...10)()))],
       BRACKET_LEFT_ARRAY(0...1)("["),
       BRACKET_RIGHT(12...13)("]")
     )]
  )
)
