ProgramNode(0...5)(
  ScopeNode(0...0)([]),
  StatementsNode(0...5)(
    [CallNode(0...5)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       AMPERSAND_DOT(2...4)("&."),
       IDENTIFIER(4...5)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
