ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [LambdaNode(0...8)(
       ScopeNode(0...2)([IDENTIFIER(3...4)("a"), IDENTIFIER(6...7)("b")]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(2...8)(
         ParametersNode(3...4)(
           [RequiredParameterNode(3...4)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [IDENTIFIER(6...7)("b")],
         (2...3),
         (7...8)
       ),
       nil
     )]
  )
)
