ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [LambdaNode(0...7)(
       ScopeNode(0...2)([LABEL(4...5)("k")]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(3...7)(
         ParametersNode(4...6)(
           [],
           [],
           [],
           nil,
           [KeywordParameterNode(4...6)(LABEL(4...6)("k:"), nil)],
           nil,
           nil
         ),
         [],
         (3...4),
         (6...7)
       ),
       nil
     )]
  )
)
