ProgramNode(0...7)(
  ScopeNode(0...0)([]),
  StatementsNode(0...7)(
    [CallNode(0...5)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...5)(
         [StringNode(2...5)(
            STRING_BEGIN(2...3)("\""),
            STRING_CONTENT(3...4)("\n"),
            STRING_END(4...5)("\""),
            "\n"
          )]
       ),
       nil,
       nil,
       "a"
     ),
     CallNode(6...7)(
       nil,
       nil,
       IDENTIFIER(6...7)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
