ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [CallNode(0...7)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...7)(
         [StringNode(2...7)(
            STRING_BEGIN(2...3)("\""),
            STRING_CONTENT(3...6)("\\\\n"),
            STRING_END(6...7)("\""),
            "\\n"
          )]
       ),
       nil,
       nil,
       "a"
     ),
     CallNode(8...9)(
       nil,
       nil,
       IDENTIFIER(8...9)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
