ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [CallNode(0...6)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...6)(
         [StringNode(2...6)(
            STRING_BEGIN(2...3)("\""),
            STRING_CONTENT(3...5)("\\n"),
            STRING_END(5...6)("\""),
            "\n"
          )]
       ),
       nil,
       nil,
       "a"
     ),
     CallNode(7...8)(
       nil,
       nil,
       IDENTIFIER(7...8)("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     )]
  )
)
