ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [InterpolatedStringNode(0...23)(
       STRING_BEGIN(0...1)("\""),
       [StringInterpolatedNode(1...22)(
          EMBEXPR_BEGIN(1...3)("\#{"),
          StatementsNode(8...21)(
            [IfNode(8...21)(
               QUESTION_MARK(8...9)("?"),
               CallNode(3...7)(
                 CallNode(3...4)(
                   nil,
                   nil,
                   IDENTIFIER(3...4)("a"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "a"
                 ),
                 DOT(4...5)("."),
                 IDENTIFIER(5...7)("b?"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "b?"
               ),
               StatementsNode(10...17)(
                 [CallNode(10...17)(
                    CallNode(10...14)(
                      StringNode(10...12)(
                        STRING_BEGIN(10...11)("\""),
                        STRING_CONTENT(11...11)(""),
                        STRING_END(11...12)("\""),
                        ""
                      ),
                      nil,
                      PLUS(12...13)("+"),
                      nil,
                      ArgumentsNode(13...14)(
                        [CallNode(13...14)(
                           nil,
                           nil,
                           IDENTIFIER(13...14)("a"),
                           nil,
                           nil,
                           nil,
                           nil,
                           "a"
                         )]
                      ),
                      nil,
                      nil,
                      "+"
                    ),
                    nil,
                    PLUS(14...15)("+"),
                    nil,
                    ArgumentsNode(15...17)(
                      [StringNode(15...17)(
                         STRING_BEGIN(15...16)("\""),
                         STRING_CONTENT(16...16)(""),
                         STRING_END(16...17)("\""),
                         ""
                       )]
                    ),
                    nil,
                    nil,
                    "+"
                  )]
               ),
               ElseNode(17...21)(
                 COLON(17...18)(":"),
                 StatementsNode(19...21)(
                   [StringNode(19...21)(
                      STRING_BEGIN(19...20)("\""),
                      STRING_CONTENT(20...20)(""),
                      STRING_END(20...21)("\""),
                      ""
                    )]
                 ),
                 nil
               ),
               nil
             )]
          ),
          EMBEXPR_END(21...22)("}")
        )],
       STRING_END(22...23)("\"")
     )]
  )
)
