ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [SuperNode(0...8)(
       KEYWORD_SUPER(0...5)("super"),
       nil,
       ArgumentsNode(6...8)([IntegerNode(6...8)()]),
       nil,
       nil
     )]
  )
)
