ProgramNode(0...3)(
  ScopeNode(0...0)([]),
  StatementsNode(0...3)(
    [SymbolNode(0...3)(
       SYMBOL_BEGIN(0...2)(":'"),
       STRING_CONTENT(2...2)(""),
       STRING_END(2...3)("'"),
       ""
     )]
  )
)
