ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [CallNode(0...6)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("f"),
         nil,
         nil,
         nil,
         nil,
         "f"
       ),
       DOT(1...2)("."),
       nil,
       PARENTHESIS_LEFT(2...3)("("),
       ArgumentsNode(3...5)([IntegerNode(3...5)()]),
       PARENTHESIS_RIGHT(5...6)(")"),
       nil,
       "call"
     ),
     CallNode(8...15)(
       CallNode(8...9)(
         nil,
         nil,
         IDENTIFIER(8...9)("f"),
         nil,
         nil,
         nil,
         nil,
         "f"
       ),
       COLON_COLON(9...11)("::"),
       nil,
       PARENTHESIS_LEFT(11...12)("("),
       ArgumentsNode(12...14)([IntegerNode(12...14)()]),
       PARENTHESIS_RIGHT(14...15)(")"),
       nil,
       "call"
     )]
  )
)
