ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       FloatNode(1...4)(),
       nil,
       UMINUS_NUM(0...1)("-"),
       nil,
       nil,
       nil,
       nil,
       "-@"
     )]
  )
)
