ProgramNode(0...2)(
  ScopeNode(0...0)([]),
  StatementsNode(0...2)(
    [CallNode(0...2)(
       CallNode(1...2)(
         nil,
         nil,
         IDENTIFIER(1...2)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       nil,
       UMINUS(0...1)("-"),
       nil,
       nil,
       nil,
       nil,
       "-@"
     )]
  )
)
