ProgramNode(26...29)(
  ScopeNode(0...0)([]),
  StatementsNode(26...29)(
    [CallNode(26...29)(
       nil,
       nil,
       IDENTIFIER(26...27)("p"),
       nil,
       ArgumentsNode(28...29)([IntegerNode(28...29)()]),
       nil,
       nil,
       "p"
     )]
  )
)
