ProgramNode(0...25)(
  ScopeNode(0...0)([]),
  StatementsNode(0...25)(
    [CaseNode(0...25)(
       CallNode(5...6)(
         nil,
         nil,
         IDENTIFIER(5...6)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       [WhenNode(8...15)(
          KEYWORD_WHEN(8...12)("when"),
          [SplatNode(13...15)(
             USTAR(13...14)("*"),
             CallNode(14...15)(
               nil,
               nil,
               IDENTIFIER(14...15)("b"),
               nil,
               nil,
               nil,
               nil,
               "b"
             )
           )],
          StatementsNode(0...0)([])
        )],
       nil,
       (0...4),
       (22...25)
     )]
  )
)
