ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [ArrayNode(0...9)(
       [InterpolatedStringNode(0...8)(
          nil,
          [StringInterpolatedNode(3...7)(
             EMBEXPR_BEGIN(3...5)("\#{"),
             StatementsNode(5...6)([IntegerNode(5...6)()]),
             EMBEXPR_END(6...7)("}")
           ),
           StringNode(7...8)(nil, STRING_CONTENT(7...8)("b"), nil, "b")],
          nil
        )],
       PERCENT_UPPER_W(0...3)("%W("),
       STRING_END(8...9)(")")
     )]
  )
)
