ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [CallNode(0...11)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(1...2)("."),
       IDENTIFIER(2...3)("b"),
       nil,
       ArgumentsNode(4...7)(
         [ParenthesesNode(4...7)(
            StatementsNode(5...6)([IntegerNode(5...6)()]),
            (4...5),
            (6...7)
          )]
       ),
       nil,
       BlockNode(8...11)(
         ScopeNode(8...9)([]),
         nil,
         StatementsNode(9...10)(
           [CallNode(9...10)(
              nil,
              nil,
              IDENTIFIER(9...10)("c"),
              nil,
              nil,
              nil,
              nil,
              "c"
            )]
         ),
         (8...9),
         (10...11)
       ),
       "b"
     )]
  )
)
