ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [YieldNode(0...8)(
       KEYWORD_YIELD(0...5)("yield"),
       nil,
       ArgumentsNode(6...8)([IntegerNode(6...8)()]),
       nil
     )]
  )
)
