ProgramNode(6...66)(
  ScopeNode(0...0)([]),
  StatementsNode(6...66)(
    [HashNode(6...66)(
       BRACE_LEFT(6...7)("{"),
       [AssocNode(16...41)(
          SymbolNode(16...18)(
            nil,
            LABEL(16...17)("a"),
            LABEL_END(17...18)(":"),
            "a"
          ),
          CallNode(19...41)(
            nil,
            nil,
            IDENTIFIER(19...25)("lambda"),
            nil,
            nil,
            nil,
            BlockNode(26...41)(
              ScopeNode(26...27)([]),
              nil,
              StatementsNode(30...39)(
                [IfNode(30...39)(
                   QUESTION_MARK(30...31)("?"),
                   CallNode(28...29)(
                     nil,
                     nil,
                     IDENTIFIER(28...29)("b"),
                     nil,
                     nil,
                     nil,
                     nil,
                     "b"
                   ),
                   StatementsNode(32...35)(
                     [CallNode(32...35)(
                        nil,
                        nil,
                        IDENTIFIER(32...33)("c"),
                        PARENTHESIS_LEFT(33...34)("("),
                        nil,
                        PARENTHESIS_RIGHT(34...35)(")"),
                        nil,
                        "c"
                      )]
                   ),
                   ElseNode(36...39)(
                     COLON(36...37)(":"),
                     StatementsNode(38...39)(
                       [CallNode(38...39)(
                          nil,
                          nil,
                          IDENTIFIER(38...39)("d"),
                          nil,
                          nil,
                          nil,
                          nil,
                          "d"
                        )]
                     ),
                     nil
                   ),
                   nil
                 )]
              ),
              (26...27),
              (40...41)
            ),
            "lambda"
          ),
          nil
        ),
        AssocNode(51...57)(
          SymbolNode(51...53)(
            nil,
            LABEL(51...52)("e"),
            LABEL_END(52...53)(":"),
            "e"
          ),
          NilNode(54...57)(),
          nil
        )],
       BRACE_RIGHT(65...66)("}")
     )]
  )
)
