# Makefile for ripper developpers
# !!! This file requires GNU make !!!

include Makefile

lib/ripper.rb: $(srcdir)/ripper.rb.in ids1 ids2 $(srcdir)/tools/generate-ripper_rb.rb
	$(RUBY) $(srcdir)/tools/generate-ripper_rb.rb $(srcdir)/ripper.rb.in ids1 ids2 > $@

test:
	$(RUBY) test/check-event-arity.rb $(hdrdir)/parse.y
	sh test/check-event-coverage.sh
	$(RUBY) test/check-scanner-event-coverage.rb
	$(RUBY) test/validate.rb > /dev/null
	@echo OK

preproc: ripper.E
ripper.E: ripper.c
	$(CC) -E $(CPPFLAGS) ripper.c | ruby $(srcdir)/tools/strip.rb > $@
