#!/bin/sh

[ "$1" -a -d "$1" ] && { cd "$1" || exit $?; } && shift
[ "$#" = 0 ] && set enc/trans/*.erb.c
for erb; do
    case "$erb" in
    *.erb.c)
	src=`expr "$erb" | sed 's/\.erb\.c$/.c/'`
	${BASERUBY-ruby} tool/transcode-tblgen.rb -vo "$src" "$erb"
	;;
    *)
	echo "$0: don' know how to deal with $erb"
	continue
	;;
    esac
done
