#!/usr/bin/ruby
require File.expand_path('../downloader', __FILE__)
ARGV.each {|n|
  STDOUT.print "Downloading #{n}..."; STDOUT.flush
  begin
    Downloader.download(n)
    STDOUT.puts
  rescue => e
    STDOUT.puts
    abort("#{$0}: #{e.message}")
  end
}
