#!/bin/sh
# usage: ifchange target temporary

unset timestamp
if [ "$1" = --timestamp ]; then
    timestamp=yes
    shift
fi
target="$1"
temp="$2"
if [ "$temp" = - ]; then
    temp="tmpdata$$.tmp~"
    cat > "$temp" || exit $?
    trap 'rm -f "$temp"' 0
fi
if cmp "$target" "$temp" >/dev/null 2>&1; then
    echo "$target unchanged"
    rm -f "$temp"
else
    echo "$target updated"
    mv -f "$temp" "$target"
fi
if [ $timestamp ]; then
    touch `dirname "$target"`/.time.`basename "$target"`
fi
