#!/bin/bash

# Assumes all commits have been synchronized to https://github.com/ruby/spec
# See spec/mspec/tool/sync/sync-rubyspec.rb

rm -rf spec/mspec
git clone --depth 1 https://github.com/ruby/mspec.git spec/mspec
commit=$(git -C spec/mspec log -n 1 --format='%h')
rm -rf spec/mspec/.git
git add spec/mspec
git commit -m "Update to ruby/mspec@${commit}"

rm -rf spec/rubyspec
git clone --depth 1 https://github.com/ruby/spec.git spec/rubyspec
commit=$(git -C spec/rubyspec log -n 1 --format='%h')
rm -rf spec/rubyspec/.git
git add spec/rubyspec
git commit -m "Update to ruby/spec@${commit}"
