#!ruby

# TODO: We should load rdoc from gemspec, but it is not easy to do because
# rdoc depends psych. We cannot load psych from gemspec.
rdoc_path = Dir.glob("#{ARGV[0]}/.bundle/gems/rdoc-*").first
$LOAD_PATH.unshift("#{rdoc_path}/lib")

require 'rdoc/rdoc'

# Make only the output directory relative to the invoked directory.
invoked = Dir.pwd

# Load options and parse files from srcdir.
Dir.chdir(File.dirname(__dir__))

options = RDoc::Options.load_options
options.parse ARGV

options.singleton_class.define_method(:finish) do
  super()
  @op_dir = File.expand_path(@op_dir, invoked)
end

# Do not hide errors when generating documents of Ruby itself.
RDoc::RDoc.new.document options
