.\" generated with nRonn/v0.11.1
.\" https://github.com/n-ronn/nronn/tree/0.11.1
.TH "BUNDLE\-LICENSES" "1" "December 2024" ""
.SH "NAME"
\fBbundle\-licenses\fR \- Print the license of all gems in the bundle
.SH "SYNOPSIS"
\fBbundle licenses\fR
.SH "DESCRIPTION"
Prints the license of all gems in the bundle\.
