.\" generated with nRonn/v0.11.1
.\" https://github.com/n-ronn/nronn/tree/0.11.1
.TH "BUNDLE\-FUND" "1" "December 2024" ""
.SH "NAME"
\fBbundle\-fund\fR \- Lists information about gems seeking funding assistance
.SH "SYNOPSIS"
\fBbundle fund\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
\fBbundle fund\fR lists information about gems seeking funding assistance\.
.SH "OPTIONS"
.TP
\fB\-\-group=<list>\fR, \fB\-g=<list>\fR
Fetch funding information for a specific group\.
.SH "EXAMPLES"
.nf
# Lists funding information for all gems
bundle fund

# Lists funding information for a specific group
bundle fund \-\-group=security
.fi

