.\" generated with nRonn/v0.11.1
.\" https://github.com/n-ronn/nronn/tree/0.11.1
.TH "BUNDLE\-ENV" "1" "December 2024" ""
.SH "NAME"
\fBbundle\-env\fR \- Print information about the environment Bundler is running under
.SH "SYNOPSIS"
\fBbundle env\fR
.SH "DESCRIPTION"
Prints information about the environment Bundler is running under\.
