.\" generated with nRonn/v0.11.1
.\" https://github.com/n-ronn/nronn/tree/0.11.1
.TH "BUNDLE\-VERSION" "1" "February 2024" ""
.SH "NAME"
\fBbundle\-version\fR \- Prints Bundler version information
.SH "SYNOPSIS"
\fBbundle version\fR
.SH "DESCRIPTION"
Prints Bundler version information\.
.SH "OPTIONS"
No options\.
.SH "EXAMPLE"
Print the version of Bundler with build date and commit hash of the in the Git source\.
.IP "" 4
.nf
bundle version
.fi
.IP "" 0
.P
shows \fBBundler version 2\.3\.21 (2022\-08\-24 commit d54be5fdd8)\fR for example\.
.P
cf\. \fBbundle \-\-version\fR shows \fBBundler version 2\.3\.21\fR\.
