extension Integer (Prime)
  # Iterates the given block over all prime numbers.
  #
  # See Prime#each for more details.
  #
  def self.each_prime: (Integer) { (Integer) -> void } -> void

  # Re-composes a prime factorization and returns the product.
  #
  # See Prime#int_from_prime_division for more details.
  #
  def self.from_prime_division: (Array[[ String ]]) -> Integer

  # Returns the factorization of `self`.
  #
  # See Prime#prime_division for more details.
  #
  def prime_division: (?Prime::PseudoPrimeGenerator) -> Array[[ Integer, Integer ]]

  # Returns true if `self` is a prime number, else returns false.
  #
  def prime?: () -> bool
end
