exclude(:test_def_method_with_fname, "incorrect line number")
exclude(:test_def_method_without_filename, "incorrect line number")
exclude(:test_eval_input_with_exception, "incorrect line number")
exclude(:test_keep_lineno, "incorrect line number")
exclude(:test_multi_line_comment_lineno, "incorrect line number")
exclude(:test_multi_line_comment_lineno, "incorrect line number")
