exclude(:test_error_def_in_argument, "unknown")
exclude(:test_global_variable, "unknown")
exclude(:test_invalid_char, "unknown")
exclude(:test_location_of_invalid_token, "unknown")
exclude(:test_percent, "unknown")
exclude(:test_question, "unknown")
exclude(:test_string, "unknown")
exclude(:test_truncated_source_line, "unknown")
exclude(:test_unexpected_eof, "unknown")
exclude(:test_unexpected_token_after_numeric, "unknown")
exclude(:test_unused_variable, "missing warning")
exclude(:test_void_value_in_rhs, "unknown")
