exclude(:test_each_child, "unknown")
exclude(:test_frozen_string_literal_compile_option, "unknown")
exclude(:test_syntax_error_message, "unknown")
exclude(:test_to_binary_class_tracepoint, "unknown")
exclude(:test_to_binary_end_tracepoint, "unknown")
exclude(:test_trace_points, "unknown")
exclude(:test_unreachable_syntax_error, "unknown")
