exclude(:test_dregexp, "unknown")
exclude(:test_dstring_encoding, "incorrect encoding")
exclude(:test_float, "numbered parameters inside evals")
exclude(:test_frozen_string_in_array_literal, "incorrect frozen value")
exclude(:test_hash_duplicated_key, "missing warning")
exclude(:test_integer, "numbered parameters inside evals")
exclude(:test_string, "https://github.com/ruby/prism/issues/2331")
