exclude(:test__END___cr, "error message format")
exclude(:test_argument_forwarding_with_super, "error message format")
exclude(:test_argument_forwarding, "error message format")
exclude(:test_dedented_heredoc_continued_line, "heredoc line continuation dedent calculation")
exclude(:test_duplicated_when, "error message format")
exclude(:test_error_message_encoding, "syntax error message encoding")
exclude(:test_it, "https://github.com/ruby/prism/issues/2323")
exclude(:test_numbered_parameter, "should raise syntax error for numbered parameters in inner blocks")
exclude(:test_syntax_error_at_newline, "error message format")
exclude(:test_unterminated_heredoc_cr, "quoted \r heredoc terminators should not match \r\n")
exclude(:test_warn_balanced, "missing warning for ** being interpreted as a binary operator")

exclude(:test_optional_self_reference, "https://bugs.ruby-lang.org/issues/20478")
exclude(:test_keyword_self_reference, "https://bugs.ruby-lang.org/issues/20478")
