exclude(:test_array_pattern, "duplicated variable error missing")
exclude(:test_find_pattern, "duplicated variable error missing")
exclude(:test_hash_pattern, "useless literal warning missing")
exclude(:test_invalid_syntax, "duplicated variable error missing")
exclude(:test_var_pattern, "duplicated variable error missing")
