exclude(:test_invalid_escape_error, "unknown")
exclude(:test_invalid_fragment, "https://github.com/ruby/prism/issues/2664")
exclude(:test_unescape, "unknown")
exclude(:test_unicode_age_14_0, "https://github.com/ruby/prism/issues/2664")
exclude(:test_unicode_age_15_0, "https://github.com/ruby/prism/issues/2664")
exclude(:test_unicode_age, "https://github.com/ruby/prism/issues/2664")
