exclude(:test_dynamic_constant_assignment, "unknown")
exclude(:test_else_without_rescue, "unknown")
exclude(:test_error_def_in_argument, "unknown")
exclude(:test_float, "unknown")
exclude(:test_global_variable, "unknown")
exclude(:test_here_document, "unknown")
exclude(:test_heredoc_unterminated_interpolation, "unknown")
exclude(:test_invalid_char, "unknown")
exclude(:test_location_of_invalid_token, "unknown")
exclude(:test_no_blockarg, "unknown")
exclude(:test_op_asgn1_with_block, "unknown")
exclude(:test_parse_string, "unknown")
exclude(:test_percent, "unknown")
exclude(:test_question, "unknown")
exclude(:test_shareable_constant_value_ignored, "unknown")
exclude(:test_shareable_constant_value_nested, "ractor support")
exclude(:test_shareable_constant_value_nonliteral, "ractor support")
exclude(:test_shareable_constant_value_simple, "ractor support")
exclude(:test_shareable_constant_value_unfrozen, "ractor support")
exclude(:test_shareable_constant_value_unshareable_literal, "ractor support")
exclude(:test_string, "unknown")
exclude(:test_truncated_source_line, "unknown")
exclude(:test_unassignable, "unknown")
exclude(:test_unexpected_eof, "unknown")
exclude(:test_unexpected_token_after_numeric, "unknown")
exclude(:test_unterminated_regexp_error, "unknown")
exclude(:test_unused_variable, "missing warning")
exclude(:test_void_value_in_rhs, "unknown")
exclude(:test_words, "unknown")
