exclude(:test_debug_frozen_string_in_array_literal, "unknown")
exclude(:test_debug_frozen_string, "unknown")
exclude(:test_dregexp, "https://github.com/ruby/prism/issues/2664")
exclude(:test_hash_value_omission, "unknown")
exclude(:test_string, "https://github.com/ruby/prism/issues/2331")
