exclude(:test_clear_with_branches, "unknown")
exclude(:test_eval, "unknown")
exclude(:test_branch_coverage_for_while_statement, "branch coverage in while")
exclude(:test_coverage_optimized_branch, "branch coverage in &.")
exclude(:test_branch_coverage_for_if_statement, "branch coverage in if")
exclude(:test_branch_coverage_for_safe_method_invocation, "branch coverage in &.")
exclude(:test_branch_coverage_for_pattern_matching, "branch coverage in pattern matching")
exclude(:test_tag_break_with_branch_coverage, "branch coverage in &.")
exclude(:test_branch_coverage_for_case_statement, "branch coverage in case")
exclude(:test_coverage_ensure_if_return, "branch coverage in if")
exclude(:test_branch_coverage_in_ensure_clause, "branch coverage in ensure")
