exclude(:test_each_child, "https://github.com/ruby/prism/issues/2660")
exclude(:test_frozen_string_literal_compile_option, "https://github.com/ruby/prism/issues/2661")
exclude(:test_syntax_error_message, "Assertion checks against specific error format")
exclude(:test_to_binary_class_tracepoint, "https://github.com/ruby/prism/issues/2662")
exclude(:test_to_binary_end_tracepoint, "https://github.com/ruby/prism/issues/2663")
exclude(:test_trace_points, "https://github.com/ruby/prism/issues/2660")
exclude(:test_unreachable_syntax_error, "https://github.com/ruby/prism/issues/1604")
