exclude(:test_dynamic_eucjp_regexp, "https://github.com/ruby/prism/issues/2664")
exclude(:test_dynamic_sjis_regexp, "https://github.com/ruby/prism/issues/2664")
exclude(:test_dynamic_utf8_regexp, "https://github.com/ruby/prism/issues/2664")
exclude(:test_regexp_ascii, "https://github.com/ruby/prism/issues/2664")
exclude(:test_regexp_embed, "https://github.com/ruby/prism/issues/2664")
exclude(:test_regexp_usascii, "unknown")
exclude(:test_string_mixed_unicode, "unknown")
