ProgramNode(2...15)(
  ScopeNode(0...0)([]),
  StatementsNode(2...15)(
    [IfNode(2...15)(
       QUESTION_MARK(2...3)("?"),
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       StatementsNode(4...10)(
         [CallNode(4...10)(
            CallNode(4...5)(
              nil,
              nil,
              IDENTIFIER(4...5)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            ),
            nil,
            AMPERSAND(6...7)("&"),
            nil,
            ArgumentsNode(8...10)(
              [StringNode(8...10)(
                 STRING_BEGIN(8...9)("'"),
                 STRING_CONTENT(9...9)(""),
                 STRING_END(9...10)("'"),
                 ""
               )]
            ),
            nil,
            nil,
            "&"
          )]
       ),
       ElseNode(10...15)(
         COLON(10...11)(":"),
         StatementsNode(12...15)([NilNode(12...15)()]),
         nil
       ),
       nil
     )]
  )
)
