ProgramNode(0...40)(
  ScopeNode(0...0)([]),
  StatementsNode(0...40)(
    [DefNode(0...18)(
       IDENTIFIER(4...7)("foo"),
       nil,
       ParametersNode(8...12)(
         [RequiredParameterNode(8...9)(), RequiredParameterNode(11...12)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([IDENTIFIER(8...9)("_")]),
       (0...3),
       nil,
       (7...8),
       (12...13),
       nil,
       (15...18)
     ),
     DefNode(20...40)(
       IDENTIFIER(24...27)("foo"),
       nil,
       ParametersNode(28...34)(
         [RequiredParameterNode(28...30)(), RequiredParameterNode(32...34)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(20...23)([IDENTIFIER(28...30)("_a")]),
       (20...23),
       nil,
       (27...28),
       (34...35),
       nil,
       (37...40)
     )]
  )
)
