ProgramNode(0...26)(
  ScopeNode(0...0)([]),
  StatementsNode(0...26)(
    [CallNode(0...9)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       PARENTHESIS_LEFT(3...4)("("),
       ArgumentsNode(4...8)(
         [SplatNode(4...8)(
            USTAR(4...5)("*"),
            CallNode(5...8)(
              nil,
              nil,
              IDENTIFIER(5...8)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            )
          )]
       ),
       PARENTHESIS_RIGHT(8...9)(")"),
       nil,
       "fun"
     ),
     CallNode(11...26)(
       nil,
       nil,
       IDENTIFIER(11...14)("fun"),
       PARENTHESIS_LEFT(14...15)("("),
       ArgumentsNode(15...25)(
         [SplatNode(15...19)(
            USTAR(15...16)("*"),
            CallNode(16...19)(
              nil,
              nil,
              IDENTIFIER(16...19)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            )
          ),
          BlockArgumentNode(21...25)(
            CallNode(22...25)(
              nil,
              nil,
              IDENTIFIER(22...25)("baz"),
              nil,
              nil,
              nil,
              nil,
              "baz"
            ),
            (21...22)
          )]
       ),
       PARENTHESIS_RIGHT(25...26)(")"),
       nil,
       "fun"
     )]
  )
)
