ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [CallNode(0...9)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       PARENTHESIS_LEFT(3...4)("("),
       ArgumentsNode(4...8)(
         [BlockArgumentNode(4...8)(
            CallNode(5...8)(
              nil,
              nil,
              IDENTIFIER(5...8)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            ),
            (4...5)
          )]
       ),
       PARENTHESIS_RIGHT(8...9)(")"),
       nil,
       "fun"
     )]
  )
)
