ProgramNode(0...25)(
  ScopeNode(0...0)([]),
  StatementsNode(0...25)(
    [ArrayNode(0...10)(
       [HashNode(2...8)(
          nil,
          [AssocNode(2...8)(
             IntegerNode(2...3)(),
             IntegerNode(7...8)(),
             EQUAL_GREATER(4...6)("=>")
           )],
          nil
        )],
       BRACKET_LEFT_ARRAY(0...1)("["),
       BRACKET_RIGHT(9...10)("]")
     ),
     ArrayNode(12...25)(
       [IntegerNode(14...15)(),
        HashNode(17...23)(
          nil,
          [AssocNode(17...23)(
             IntegerNode(17...18)(),
             IntegerNode(22...23)(),
             EQUAL_GREATER(19...21)("=>")
           )],
          nil
        )],
       BRACKET_LEFT_ARRAY(12...13)("["),
       BRACKET_RIGHT(24...25)("]")
     )]
  )
)
