ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [ArrayNode(0...4)(
       [],
       PERCENT_UPPER_I(0...3)("%I("),
       STRING_END(3...4)(")")
     ),
     ArrayNode(6...10)(
       [],
       PERCENT_LOWER_I(6...9)("%i["),
       STRING_END(9...10)("]")
     )]
  )
)
