ProgramNode(0...30)(
  ScopeNode(0...0)([IDENTIFIER(0...3)("foo"), IDENTIFIER(6...9)("bar")]),
  StatementsNode(0...30)(
    [LocalVariableWriteNode(0...17)(
       (0...3),
       LocalVariableWriteNode(6...17)(
         (6...9),
         CallNode(12...17)(
           nil,
           nil,
           IDENTIFIER(12...13)("m"),
           nil,
           ArgumentsNode(14...17)([LocalVariableReadNode(14...17)(0)]),
           nil,
           nil,
           "m"
         ),
         (10...11),
         0
       ),
       (4...5),
       0
     ),
     LocalVariableWriteNode(19...30)(
       (19...22),
       CallNode(25...30)(
         nil,
         nil,
         IDENTIFIER(25...26)("m"),
         nil,
         ArgumentsNode(27...30)([LocalVariableReadNode(27...30)(0)]),
         nil,
         nil,
         "m"
       ),
       (23...24),
       0
     )]
  )
)
