ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       CallNode(1...4)(
         nil,
         nil,
         IDENTIFIER(1...4)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       BANG(0...1)("!"),
       nil,
       nil,
       nil,
       nil,
       "!"
     )]
  )
)
