ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [DefNode(0...18)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...12)(
         [],
         [],
         [],
         nil,
         [],
         nil,
         BlockParameterNode(6...12)(IDENTIFIER(7...12)("block"), (6...7))
       ),
       nil,
       ScopeNode(0...3)([IDENTIFIER(7...12)("block")]),
       (0...3),
       nil,
       (5...6),
       (12...13),
       nil,
       (15...18)
     )]
  )
)
