ProgramNode(0...5)(
  ScopeNode(0...0)([]),
  StatementsNode(0...5)(
    [RegularExpressionNode(0...5)(
       REGEXP_BEGIN(0...1)("/"),
       STRING_CONTENT(1...3)("#)"),
       REGEXP_END(3...5)("/x"),
       "#)"
     )]
  )
)
