ProgramNode(0...37)(
  ScopeNode(0...0)([]),
  StatementsNode(0...37)(
    [CallNode(0...21)(
       nil,
       nil,
       IDENTIFIER(0...2)("td"),
       nil,
       ArgumentsNode(3...21)(
         [CallNode(3...21)(
            ParenthesesNode(3...10)(
              StatementsNode(4...9)([IntegerNode(4...9)()]),
              (3...4),
              (9...10)
            ),
            DOT(10...11)("."),
            IDENTIFIER(11...19)("toString"),
            PARENTHESIS_LEFT(19...20)("("),
            nil,
            PARENTHESIS_RIGHT(20...21)(")"),
            nil,
            "toString"
          )]
       ),
       nil,
       nil,
       "td"
     ),
     CallNode(23...37)(
       CallNode(23...25)(
         nil,
         nil,
         IDENTIFIER(23...25)("td"),
         nil,
         nil,
         nil,
         nil,
         "td"
       ),
       DOT(25...26)("."),
       IDENTIFIER(26...29)("num"),
       nil,
       nil,
       nil,
       BlockNode(30...37)(
         ScopeNode(30...32)([]),
         nil,
         StatementsNode(0...0)([]),
         (30...32),
         (34...37)
       ),
       "num"
     )]
  )
)
