ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [DefNode(0...23)(
       IDENTIFIER(4...7)("foo"),
       nil,
       nil,
       nil,
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (20...23)
     )]
  )
)
