ProgramNode(0...34)(
  ScopeNode(0...0)([]),
  StatementsNode(0...34)(
    [BeginNode(0...34)(
       KEYWORD_BEGIN(0...5)("begin"),
       nil,
       RescueNode(7...13)(
         KEYWORD_RESCUE(7...13)("rescue"),
         [ConstantReadNode(14...23)()],
         nil,
         nil,
         nil,
         nil
       ),
       ElseNode(25...34)(
         KEYWORD_ELSE(25...29)("else"),
         nil,
         KEYWORD_END(31...34)("end")
       ),
       nil,
       KEYWORD_END(31...34)("end")
     )]
  )
)
