ProgramNode(0...225)(
  ScopeNode(0...0)([]),
  StatementsNode(0...225)(
    [CallNode(0...42)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       nil,
       ArgumentsNode(2...42)(
         [SymbolNode(2...6)(
            SYMBOL_BEGIN(2...3)(":"),
            IDENTIFIER(3...6)("foo"),
            nil,
            "foo"
          ),
          HashNode(8...42)(
            BRACE_LEFT(8...9)("{"),
            [AssocNode(9...25)(
               SymbolNode(9...13)(
                 STRING_BEGIN(9...10)("\""),
                 STRING_CONTENT(10...11)("a"),
                 LABEL_END(11...13)("\":"),
                 "a"
               ),
               CallNode(14...25)(
                 nil,
                 nil,
                 IDENTIFIER(14...18)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(19...25)(
                   ScopeNode(19...21)([]),
                   nil,
                   nil,
                   (19...21),
                   (22...25)
                 ),
                 "proc"
               ),
               nil
             ),
             AssocNode(27...41)(
               SymbolNode(27...29)(
                 nil,
                 LABEL(27...28)("b"),
                 LABEL_END(28...29)(":"),
                 "b"
               ),
               CallNode(30...41)(
                 nil,
                 nil,
                 IDENTIFIER(30...34)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(35...41)(
                   ScopeNode(35...37)([]),
                   nil,
                   nil,
                   (35...37),
                   (38...41)
                 ),
                 "proc"
               ),
               nil
             )],
            BRACE_RIGHT(41...42)("}")
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(44...84)(
       nil,
       nil,
       IDENTIFIER(44...45)("p"),
       nil,
       ArgumentsNode(46...84)(
         [SymbolNode(46...50)(
            SYMBOL_BEGIN(46...47)(":"),
            IDENTIFIER(47...50)("foo"),
            nil,
            "foo"
          ),
          HashNode(52...84)(
            BRACE_LEFT(52...53)("{"),
            [AssocSplatNode(53...67)(
               CallNode(56...67)(
                 nil,
                 nil,
                 IDENTIFIER(56...60)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(61...67)(
                   ScopeNode(61...63)([]),
                   nil,
                   nil,
                   (61...63),
                   (64...67)
                 ),
                 "proc"
               ),
               (53...55)
             ),
             AssocNode(69...83)(
               SymbolNode(69...71)(
                 nil,
                 LABEL(69...70)("b"),
                 LABEL_END(70...71)(":"),
                 "b"
               ),
               CallNode(72...83)(
                 nil,
                 nil,
                 IDENTIFIER(72...76)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(77...83)(
                   ScopeNode(77...79)([]),
                   nil,
                   nil,
                   (77...79),
                   (80...83)
                 ),
                 "proc"
               ),
               nil
             )],
            BRACE_RIGHT(83...84)("}")
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(86...129)(
       nil,
       nil,
       IDENTIFIER(86...87)("p"),
       nil,
       ArgumentsNode(88...129)(
         [SymbolNode(88...92)(
            SYMBOL_BEGIN(88...89)(":"),
            IDENTIFIER(89...92)("foo"),
            nil,
            "foo"
          ),
          HashNode(94...129)(
            BRACE_LEFT(94...95)("{"),
            [AssocNode(95...112)(
               SymbolNode(95...97)(
                 SYMBOL_BEGIN(95...96)(":"),
                 IDENTIFIER(96...97)("a"),
                 nil,
                 "a"
               ),
               CallNode(101...112)(
                 nil,
                 nil,
                 IDENTIFIER(101...105)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(106...112)(
                   ScopeNode(106...108)([]),
                   nil,
                   nil,
                   (106...108),
                   (109...112)
                 ),
                 "proc"
               ),
               EQUAL_GREATER(98...100)("=>")
             ),
             AssocNode(114...128)(
               SymbolNode(114...116)(
                 nil,
                 LABEL(114...115)("b"),
                 LABEL_END(115...116)(":"),
                 "b"
               ),
               CallNode(117...128)(
                 nil,
                 nil,
                 IDENTIFIER(117...121)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(122...128)(
                   ScopeNode(122...124)([]),
                   nil,
                   nil,
                   (122...124),
                   (125...128)
                 ),
                 "proc"
               ),
               nil
             )],
            BRACE_RIGHT(128...129)("}")
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(131...171)(
       nil,
       nil,
       IDENTIFIER(131...132)("p"),
       nil,
       ArgumentsNode(133...171)(
         [SymbolNode(133...137)(
            SYMBOL_BEGIN(133...134)(":"),
            IDENTIFIER(134...137)("foo"),
            nil,
            "foo"
          ),
          HashNode(139...171)(
            BRACE_LEFT(139...140)("{"),
            [AssocNode(140...154)(
               SymbolNode(140...142)(
                 nil,
                 LABEL(140...141)("a"),
                 LABEL_END(141...142)(":"),
                 "a"
               ),
               CallNode(143...154)(
                 nil,
                 nil,
                 IDENTIFIER(143...147)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(148...154)(
                   ScopeNode(148...150)([]),
                   nil,
                   nil,
                   (148...150),
                   (151...154)
                 ),
                 "proc"
               ),
               nil
             ),
             AssocNode(156...170)(
               SymbolNode(156...158)(
                 nil,
                 LABEL(156...157)("b"),
                 LABEL_END(157...158)(":"),
                 "b"
               ),
               CallNode(159...170)(
                 nil,
                 nil,
                 IDENTIFIER(159...163)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(164...170)(
                   ScopeNode(164...166)([]),
                   nil,
                   nil,
                   (164...166),
                   (167...170)
                 ),
                 "proc"
               ),
               nil
             )],
            BRACE_RIGHT(170...171)("}")
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(173...225)(
       nil,
       nil,
       IDENTIFIER(173...174)("p"),
       nil,
       ArgumentsNode(175...225)(
         [SymbolNode(175...179)(
            SYMBOL_BEGIN(175...176)(":"),
            IDENTIFIER(176...179)("foo"),
            nil,
            "foo"
          ),
          HashNode(181...225)(
            BRACE_LEFT(181...182)("{"),
            [AssocNode(182...208)(
               CallNode(182...193)(
                 nil,
                 nil,
                 IDENTIFIER(182...186)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(187...193)(
                   ScopeNode(187...189)([]),
                   nil,
                   nil,
                   (187...189),
                   (190...193)
                 ),
                 "proc"
               ),
               CallNode(197...208)(
                 nil,
                 nil,
                 IDENTIFIER(197...201)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(202...208)(
                   ScopeNode(202...204)([]),
                   nil,
                   nil,
                   (202...204),
                   (205...208)
                 ),
                 "proc"
               ),
               EQUAL_GREATER(194...196)("=>")
             ),
             AssocNode(210...224)(
               SymbolNode(210...212)(
                 nil,
                 LABEL(210...211)("b"),
                 LABEL_END(211...212)(":"),
                 "b"
               ),
               CallNode(213...224)(
                 nil,
                 nil,
                 IDENTIFIER(213...217)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(218...224)(
                   ScopeNode(218...220)([]),
                   nil,
                   nil,
                   (218...220),
                   (221...224)
                 ),
                 "proc"
               ),
               nil
             )],
            BRACE_RIGHT(224...225)("}")
          )]
       ),
       nil,
       nil,
       "p"
     )]
  )
)
