ProgramNode(0...17)(
  ScopeNode(0...0)([]),
  StatementsNode(0...17)(
    [CallNode(0...17)(
       nil,
       nil,
       IDENTIFIER(0...3)("tap"),
       nil,
       ArgumentsNode(4...17)(
         [ParenthesesNode(4...17)(
            StatementsNode(5...16)(
              [CallNode(5...16)(
                 nil,
                 nil,
                 IDENTIFIER(5...9)("proc"),
                 nil,
                 nil,
                 nil,
                 BlockNode(10...16)(
                   ScopeNode(10...12)([]),
                   nil,
                   nil,
                   (10...12),
                   (13...16)
                 ),
                 "proc"
               )]
            ),
            (4...5),
            (16...17)
          )]
       ),
       nil,
       nil,
       "tap"
     )]
  )
)
