ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [CallNode(0...23)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       ArgumentsNode(2...20)(
         [InterpolatedStringNode(2...20)(
            HEREDOC_START(2...10)("<<-TABLE"),
            [],
            HEREDOC_END(14...20)("TABLE\n")
          )]
       ),
       nil,
       BlockNode(11...23)(
         ScopeNode(11...13)([]),
         nil,
         nil,
         (11...13),
         (20...23)
       ),
       "f"
     )]
  )
)
