ProgramNode(0...27)(
  ScopeNode(0...0)([]),
  StatementsNode(0...27)(
    [CallNode(0...27)(
       nil,
       nil,
       IDENTIFIER(0...3)("foo"),
       nil,
       ArgumentsNode(4...19)(
         [InterpolatedStringNode(4...19)(
            STRING_BEGIN(4...5)("\""),
            [StringInterpolatedNode(5...18)(
               EMBEXPR_BEGIN(5...7)("\#{"),
               StatementsNode(7...17)(
                 [CallNode(7...17)(
                    ParenthesesNode(7...12)(
                      StatementsNode(8...11)(
                        [CallNode(8...11)(
                           IntegerNode(8...9)(),
                           nil,
                           PLUS(9...10)("+"),
                           nil,
                           ArgumentsNode(10...11)([IntegerNode(10...11)()]),
                           nil,
                           nil,
                           "+"
                         )]
                      ),
                      (7...8),
                      (11...12)
                    ),
                    DOT(12...13)("."),
                    IDENTIFIER(13...17)("to_i"),
                    nil,
                    nil,
                    nil,
                    nil,
                    "to_i"
                  )]
               ),
               EMBEXPR_END(17...18)("}")
             )],
            STRING_END(18...19)("\"")
          )]
       ),
       nil,
       BlockNode(20...27)(
         ScopeNode(20...22)([]),
         nil,
         StatementsNode(0...0)([]),
         (20...22),
         (24...27)
       ),
       "foo"
     )]
  )
)
