ProgramNode(0...38)(
  ScopeNode(0...0)([]),
  StatementsNode(0...38)(
    [CaseNode(0...38)(
       nil,
       [WhenNode(6...21)(
          KEYWORD_WHEN(6...10)("when"),
          [CallNode(11...14)(
             nil,
             nil,
             IDENTIFIER(11...14)("foo"),
             nil,
             nil,
             nil,
             nil,
             "foo"
           )],
          StatementsNode(16...21)(
            [StringNode(16...21)(
               STRING_BEGIN(16...17)("'"),
               STRING_CONTENT(17...20)("foo"),
               STRING_END(20...21)("'"),
               "foo"
             )]
          )
        )],
       ElseNode(23...38)(
         KEYWORD_ELSE(23...27)("else"),
         StatementsNode(28...33)(
           [StringNode(28...33)(
              STRING_BEGIN(28...29)("'"),
              STRING_CONTENT(29...32)("bar"),
              STRING_END(32...33)("'"),
              "bar"
            )]
         ),
         KEYWORD_END(35...38)("end")
       ),
       (0...4),
       (35...38)
     )]
  )
)
