ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [ConstantPathWriteNode(0...13)(
       ConstantPathNode(0...8)(
         ConstantReadNode(0...3)(),
         ConstantReadNode(5...8)(),
         (3...5)
       ),
       EQUAL(9...10)("="),
       IntegerNode(11...13)()
     )]
  )
)
