ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [ConstantPathWriteNode(0...8)(
       ConstantReadNode(0...3)(),
       EQUAL(4...5)("="),
       IntegerNode(6...8)()
     )]
  )
)
