ProgramNode(0...20)(
  ScopeNode(0...0)([]),
  StatementsNode(0...20)(
    [ClassNode(0...20)(
       ScopeNode(0...5)([]),
       KEYWORD_CLASS(0...5)("class"),
       ConstantReadNode(6...9)(),
       LESS(10...11)("<"),
       ConstantReadNode(12...15)(),
       nil,
       KEYWORD_END(17...20)("end")
     )]
  )
)
