ProgramNode(0...55)(
  ScopeNode(0...0)([]),
  StatementsNode(0...55)(
    [CallNode(0...13)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       AMPERSAND_DOT(8...10)("&."),
       IDENTIFIER(10...13)("foo"),
       nil,
       nil,
       nil,
       nil,
       "foo"
     ),
     CallNode(16...28)(
       CallNode(16...17)(
         nil,
         nil,
         IDENTIFIER(16...17)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(24...25)("."),
       IDENTIFIER(25...28)("foo"),
       nil,
       nil,
       nil,
       nil,
       "foo"
     ),
     CallNode(31...42)(
       CallNode(31...32)(
         nil,
         nil,
         IDENTIFIER(31...32)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       AMPERSAND_DOT(37...39)("&."),
       IDENTIFIER(39...42)("foo"),
       nil,
       nil,
       nil,
       nil,
       "foo"
     ),
     CallNode(45...55)(
       CallNode(45...46)(
         nil,
         nil,
         IDENTIFIER(45...46)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       DOT(51...52)("."),
       IDENTIFIER(52...55)("foo"),
       nil,
       nil,
       nil,
       nil,
       "foo"
     )]
  )
)
