ProgramNode(0...31)(
  ScopeNode(0...0)([]),
  StatementsNode(0...31)(
    [CallNode(0...12)(
       ParenthesesNode(1...12)(
         StatementsNode(2...11)(
           [RangeNode(2...11)(
              CallNode(2...5)(
                nil,
                nil,
                IDENTIFIER(2...5)("foo"),
                nil,
                nil,
                nil,
                nil,
                "foo"
              ),
              CallNode(8...11)(
                nil,
                nil,
                IDENTIFIER(8...11)("bar"),
                nil,
                nil,
                nil,
                nil,
                "bar"
              ),
              (5...8)
            )]
         ),
         (1...2),
         (11...12)
       ),
       nil,
       BANG(0...1)("!"),
       nil,
       nil,
       nil,
       nil,
       "!"
     ),
     IfNode(14...31)(
       KEYWORD_IF(14...16)("if"),
       RangeNode(17...26)(
         CallNode(17...20)(
           nil,
           nil,
           IDENTIFIER(17...20)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         CallNode(23...26)(
           nil,
           nil,
           IDENTIFIER(23...26)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         ),
         (20...23)
       ),
       nil,
       nil,
       KEYWORD_END(28...31)("end")
     )]
  )
)
