ProgramNode(0...77)(
  ScopeNode(0...0)([]),
  StatementsNode(0...77)(
    [OperatorAssignmentNode(0...8)(
       ConstantPathWriteNode(0...3)(
         ConstantPathNode(0...3)(nil, ConstantReadNode(2...3)(), (0...2)),
         nil,
         nil
       ),
       PLUS_EQUAL(4...6)("+="),
       IntegerNode(7...8)()
     ),
     OperatorAssignmentNode(10...16)(
       ConstantPathWriteNode(10...11)(ConstantReadNode(10...11)(), nil, nil),
       PLUS_EQUAL(12...14)("+="),
       IntegerNode(15...16)()
     ),
     OperatorAssignmentNode(18...27)(
       ConstantPathWriteNode(18...22)(
         ConstantPathNode(18...22)(
           ConstantReadNode(18...19)(),
           ConstantReadNode(21...22)(),
           (19...21)
         ),
         nil,
         nil
       ),
       PLUS_EQUAL(23...25)("+="),
       IntegerNode(26...27)()
     ),
     DefNode(29...50)(
       IDENTIFIER(33...34)("x"),
       nil,
       nil,
       StatementsNode(36...45)(
         [OperatorOrAssignmentNode(36...45)(
            ConstantPathWriteNode(36...39)(
              ConstantPathNode(36...39)(
                nil,
                ConstantReadNode(38...39)(),
                (36...38)
              ),
              nil,
              nil
            ),
            IntegerNode(44...45)(),
            (40...43)
          )]
       ),
       ScopeNode(29...32)([]),
       (29...32),
       nil,
       nil,
       nil,
       nil,
       (47...50)
     ),
     DefNode(52...77)(
       IDENTIFIER(56...57)("x"),
       nil,
       nil,
       StatementsNode(59...72)(
         [OperatorOrAssignmentNode(59...72)(
            ConstantPathWriteNode(59...66)(
              ConstantPathNode(59...66)(
                SelfNode(59...63)(),
                ConstantReadNode(65...66)(),
                (63...65)
              ),
              nil,
              nil
            ),
            IntegerNode(71...72)(),
            (67...70)
          )]
       ),
       ScopeNode(52...55)([]),
       (52...55),
       nil,
       nil,
       nil,
       nil,
       (74...77)
     )]
  )
)
