ProgramNode(0...93)(
  ScopeNode(0...0)([]),
  StatementsNode(0...93)(
    [DefNode(0...14)(
       KEYWORD_BEGIN_UPCASE(4...9)("BEGIN"),
       nil,
       nil,
       nil,
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (11...14)
     ),
     DefNode(16...28)(
       KEYWORD_END_UPCASE(20...23)("END"),
       nil,
       nil,
       nil,
       ScopeNode(16...19)([]),
       (16...19),
       nil,
       nil,
       nil,
       nil,
       (25...28)
     ),
     DefNode(30...45)(
       CONSTANT(34...40)("String"),
       nil,
       nil,
       nil,
       ScopeNode(30...33)([]),
       (30...33),
       nil,
       nil,
       nil,
       nil,
       (42...45)
     ),
     DefNode(47...63)(
       IDENTIFIER(51...58)("String="),
       nil,
       nil,
       nil,
       ScopeNode(47...50)([]),
       (47...50),
       nil,
       nil,
       nil,
       nil,
       (60...63)
     ),
     DefNode(65...77)(
       IDENTIFIER(69...72)("foo"),
       nil,
       nil,
       nil,
       ScopeNode(65...68)([]),
       (65...68),
       nil,
       nil,
       nil,
       nil,
       (74...77)
     ),
     DefNode(79...93)(
       KEYWORD_UNTIL(83...88)("until"),
       nil,
       nil,
       nil,
       ScopeNode(79...82)([]),
       (79...82),
       nil,
       nil,
       nil,
       nil,
       (90...93)
     )]
  )
)
