ProgramNode(0...179)(
  ScopeNode(0...0)([]),
  StatementsNode(0...179)(
    [DefNode(0...28)(
       BANG_EQUAL(4...6)("!="),
       nil,
       ParametersNode(7...12)(
         [RequiredParameterNode(7...12)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(16...28)(
         [CallNode(16...28)(
            nil,
            nil,
            IDENTIFIER(16...28)("do_something"),
            nil,
            nil,
            nil,
            nil,
            "do_something"
          )]
       ),
       ScopeNode(0...3)([IDENTIFIER(7...12)("other")]),
       (0...3),
       nil,
       (6...7),
       (12...13),
       (14...15),
       nil
     ),
     DefNode(30...58)(
       BANG_EQUAL(34...36)("!="),
       nil,
       ParametersNode(37...42)(
         [RequiredParameterNode(37...42)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(46...58)(
         [CallNode(46...58)(
            nil,
            nil,
            IDENTIFIER(46...58)("do_something"),
            nil,
            nil,
            nil,
            nil,
            "do_something"
          )]
       ),
       ScopeNode(30...33)([IDENTIFIER(37...42)("other")]),
       (30...33),
       nil,
       (36...37),
       (42...43),
       (44...45),
       nil
     ),
     DefNode(60...88)(
       LESS_EQUAL(64...66)("<="),
       nil,
       ParametersNode(67...72)(
         [RequiredParameterNode(67...72)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(76...88)(
         [CallNode(76...88)(
            nil,
            nil,
            IDENTIFIER(76...88)("do_something"),
            nil,
            nil,
            nil,
            nil,
            "do_something"
          )]
       ),
       ScopeNode(60...63)([IDENTIFIER(67...72)("other")]),
       (60...63),
       nil,
       (66...67),
       (72...73),
       (74...75),
       nil
     ),
     DefNode(90...118)(
       EQUAL_EQUAL(94...96)("=="),
       nil,
       ParametersNode(97...102)(
         [RequiredParameterNode(97...102)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(106...118)(
         [CallNode(106...118)(
            nil,
            nil,
            IDENTIFIER(106...118)("do_something"),
            nil,
            nil,
            nil,
            nil,
            "do_something"
          )]
       ),
       ScopeNode(90...93)([IDENTIFIER(97...102)("other")]),
       (90...93),
       nil,
       (96...97),
       (102...103),
       (104...105),
       nil
     ),
     DefNode(120...149)(
       EQUAL_EQUAL_EQUAL(124...127)("==="),
       nil,
       ParametersNode(128...133)(
         [RequiredParameterNode(128...133)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(137...149)(
         [CallNode(137...149)(
            nil,
            nil,
            IDENTIFIER(137...149)("do_something"),
            nil,
            nil,
            nil,
            nil,
            "do_something"
          )]
       ),
       ScopeNode(120...123)([IDENTIFIER(128...133)("other")]),
       (120...123),
       nil,
       (127...128),
       (133...134),
       (135...136),
       nil
     ),
     DefNode(151...179)(
       GREATER_EQUAL(155...157)(">="),
       nil,
       ParametersNode(158...163)(
         [RequiredParameterNode(158...163)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(167...179)(
         [CallNode(167...179)(
            nil,
            nil,
            IDENTIFIER(167...179)("do_something"),
            nil,
            nil,
            nil,
            nil,
            "do_something"
          )]
       ),
       ScopeNode(151...154)([IDENTIFIER(158...163)("other")]),
       (151...154),
       nil,
       (157...158),
       (163...164),
       (165...166),
       nil
     )]
  )
)
