ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [CallNode(0...5)(
       FloatNode(1...5)(),
       nil,
       UMINUS_NUM(0...1)("-"),
       nil,
       nil,
       nil,
       nil,
       "-@"
     ),
     FloatNode(7...11)()]
  )
)
