ProgramNode(0...27)(
  ScopeNode(0...0)([]),
  StatementsNode(0...27)(
    [DefNode(0...27)(
       IDENTIFIER(4...7)("foo"),
       nil,
       ParametersNode(8...11)(
         [],
         [],
         [],
         nil,
         [],
         ForwardingParameterNode(8...11)(),
         nil
       ),
       StatementsNode(14...22)(
         [CallNode(14...22)(
            nil,
            nil,
            IDENTIFIER(14...17)("bar"),
            PARENTHESIS_LEFT(17...18)("("),
            ArgumentsNode(18...21)([ForwardingArgumentsNode(18...21)()]),
            PARENTHESIS_RIGHT(21...22)(")"),
            nil,
            "bar"
          )]
       ),
       ScopeNode(0...3)([UDOT_DOT_DOT(8...11)("...")]),
       (0...3),
       nil,
       (7...8),
       (11...12),
       nil,
       (24...27)
     )]
  )
)
