ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [GlobalVariableWriteNode(0...9)(
       GLOBAL_VARIABLE(0...4)("$var"),
       EQUAL(5...6)("="),
       IntegerNode(7...9)()
     )]
  )
)
