ProgramNode(0...25)(
  ScopeNode(0...0)([]),
  StatementsNode(0...25)(
    [HashNode(0...6)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(1...5)(
          SymbolNode(1...5)(
            nil,
            LABEL(1...4)("BAR"),
            LABEL_END(4...5)(":"),
            "BAR"
          ),
          nil,
          nil
        )],
       BRACE_RIGHT(5...6)("}")
     ),
     HashNode(8...16)(
       BRACE_LEFT(8...9)("{"),
       [AssocNode(9...11)(
          SymbolNode(9...11)(
            nil,
            LABEL(9...10)("a"),
            LABEL_END(10...11)(":"),
            "a"
          ),
          nil,
          nil
        ),
        AssocNode(13...15)(
          SymbolNode(13...15)(
            nil,
            LABEL(13...14)("b"),
            LABEL_END(14...15)(":"),
            "b"
          ),
          nil,
          nil
        )],
       BRACE_RIGHT(15...16)("}")
     ),
     HashNode(18...25)(
       BRACE_LEFT(18...19)("{"),
       [AssocNode(19...24)(
          SymbolNode(19...24)(
            nil,
            LABEL(19...23)("puts"),
            LABEL_END(23...24)(":"),
            "puts"
          ),
          nil,
          nil
        )],
       BRACE_RIGHT(24...25)("}")
     )]
  )
)
