ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [HashNode(0...10)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(2...8)(
          SymbolNode(2...6)(
            nil,
            LABEL(2...5)("foo"),
            LABEL_END(5...6)(":"),
            "foo"
          ),
          IntegerNode(7...8)(),
          nil
        )],
       BRACE_RIGHT(9...10)("}")
     )]
  )
)
