ProgramNode(0...43)(
  ScopeNode(0...0)([]),
  StatementsNode(0...43)(
    [IfNode(0...15)(
       KEYWORD_IF(0...2)("if"),
       CallNode(3...6)(
         nil,
         nil,
         IDENTIFIER(3...6)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(12...15)(
         [CallNode(12...15)(
            nil,
            nil,
            IDENTIFIER(12...15)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       ElseNode(17...30)(
         KEYWORD_ELSE(17...21)("else"),
         StatementsNode(22...25)(
           [CallNode(22...25)(
              nil,
              nil,
              IDENTIFIER(22...25)("baz"),
              nil,
              nil,
              nil,
              nil,
              "baz"
            )]
         ),
         KEYWORD_END(27...30)("end")
       ),
       KEYWORD_END(27...30)("end")
     ),
     IfNode(32...43)(
       KEYWORD_IF(32...34)("if"),
       CallNode(35...38)(
         nil,
         nil,
         IDENTIFIER(35...38)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(40...43)(
         [CallNode(40...43)(
            nil,
            nil,
            IDENTIFIER(40...43)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       ElseNode(45...58)(
         KEYWORD_ELSE(45...49)("else"),
         StatementsNode(50...53)(
           [CallNode(50...53)(
              nil,
              nil,
              IDENTIFIER(50...53)("baz"),
              nil,
              nil,
              nil,
              nil,
              "baz"
            )]
         ),
         KEYWORD_END(55...58)("end")
       ),
       KEYWORD_END(55...58)("end")
     )]
  )
)
