ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [IfNode(0...11)(
       KEYWORD_IF(0...2)("if"),
       CallNode(3...6)(
         nil,
         nil,
         IDENTIFIER(3...6)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(8...11)(
         [CallNode(8...11)(
            nil,
            nil,
            IDENTIFIER(8...11)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       IfNode(13...25)(
         KEYWORD_ELSIF(13...18)("elsif"),
         CallNode(19...22)(
           nil,
           nil,
           IDENTIFIER(19...22)("baz"),
           nil,
           nil,
           nil,
           nil,
           "baz"
         ),
         StatementsNode(24...25)([IntegerNode(24...25)()]),
         ElseNode(27...38)(
           KEYWORD_ELSE(27...31)("else"),
           StatementsNode(32...33)([IntegerNode(32...33)()]),
           KEYWORD_END(35...38)("end")
         ),
         nil
       ),
       KEYWORD_END(35...38)("end")
     )]
  )
)
