ProgramNode(0...12)(
  ScopeNode(0...0)([]),
  StatementsNode(0...12)(
    [IntegerNode(0...3)(),
     CallNode(5...8)(
       IntegerNode(6...8)(),
       nil,
       UMINUS_NUM(5...6)("-"),
       nil,
       nil,
       nil,
       nil,
       "-@"
     ),
     IntegerNode(10...12)()]
  )
)
