ProgramNode(0...46)(
  ScopeNode(0...0)([]),
  StatementsNode(0...46)(
    [LambdaNode(0...9)(
       ScopeNode(0...2)([]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(2...9)(
         ParametersNode(3...8)(
           [],
           [],
           [],
           nil,
           [],
           NoKeywordsParameterNode(3...8)((3...5), (5...8)),
           nil
         ),
         [],
         (2...3),
         (8...9)
       ),
       nil
     ),
     DefNode(14...31)(
       IDENTIFIER(18...19)("f"),
       nil,
       ParametersNode(20...25)(
         [],
         [],
         [],
         nil,
         [],
         NoKeywordsParameterNode(20...25)((20...22), (22...25)),
         nil
       ),
       nil,
       ScopeNode(14...17)([]),
       (14...17),
       nil,
       (19...20),
       (25...26),
       nil,
       (28...31)
     ),
     CallNode(33...46)(
       nil,
       nil,
       IDENTIFIER(33...34)("m"),
       nil,
       nil,
       nil,
       BlockNode(35...46)(
         ScopeNode(35...36)([]),
         BlockParametersNode(37...44)(
           ParametersNode(38...43)(
             [],
             [],
             [],
             nil,
             [],
             NoKeywordsParameterNode(38...43)((38...40), (40...43)),
             nil
           ),
           [],
           (37...38),
           (43...44)
         ),
         nil,
         (35...36),
         (45...46)
       ),
       "m"
     )]
  )
)
