ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [DefNode(0...18)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...12)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(6...12)(
            LABEL(6...10)("foo:"),
            IntegerNode(11...12)()
          )],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([LABEL(6...9)("foo")]),
       (0...3),
       nil,
       (5...6),
       (12...13),
       nil,
       (15...18)
     )]
  )
)
