ProgramNode(0...31)(
  ScopeNode(0...0)([]),
  StatementsNode(0...31)(
    [CallNode(0...14)(
       nil,
       nil,
       IDENTIFIER(0...3)("foo"),
       nil,
       ArgumentsNode(4...14)(
         [CallNode(4...14)(
            ParenthesesNode(4...10)(
              StatementsNode(5...9)(
                [CallNode(5...9)(
                   FloatNode(6...9)(),
                   nil,
                   UMINUS_NUM(5...6)("-"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "-@"
                 )]
              ),
              (4...5),
              (9...10)
            ),
            DOT(10...11)("."),
            IDENTIFIER(11...14)("abs"),
            nil,
            nil,
            nil,
            nil,
            "abs"
          )]
       ),
       nil,
       nil,
       "foo"
     ),
     CallNode(16...31)(
       nil,
       nil,
       IDENTIFIER(16...20)("meth"),
       nil,
       ArgumentsNode(21...31)(
         [CallNode(21...31)(
            ParenthesesNode(21...27)(
              StatementsNode(22...26)(
                [CallNode(22...26)(
                   FloatNode(23...26)(),
                   nil,
                   UMINUS_NUM(22...23)("-"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "-@"
                 )]
              ),
              (21...22),
              (26...27)
            ),
            DOT(27...28)("."),
            IDENTIFIER(28...31)("abs"),
            nil,
            nil,
            nil,
            nil,
            "abs"
          )]
       ),
       nil,
       nil,
       "meth"
     )]
  )
)
