ProgramNode(0...52)(
  ScopeNode(0...0)([]),
  StatementsNode(0...52)(
    [MatchRequiredNode(0...12)(
       HashNode(0...6)(
         BRACE_LEFT(0...1)("{"),
         [AssocNode(1...5)(
            SymbolNode(1...3)(
              nil,
              LABEL(1...2)("a"),
              LABEL_END(2...3)(":"),
              "a"
            ),
            IntegerNode(4...5)(),
            nil
          )],
         BRACE_RIGHT(5...6)("}")
       ),
       HashPatternNode(10...12)(
         nil,
         [AssocNode(10...12)(
            SymbolNode(10...12)(
              nil,
              LABEL(10...11)("a"),
              LABEL_END(11...12)(":"),
              "a"
            ),
            nil,
            nil
          )],
         nil,
         nil,
         nil
       ),
       (7...9)
     ),
     MatchRequiredNode(13...25)(
       HashNode(13...19)(
         BRACE_LEFT(13...14)("{"),
         [AssocNode(14...18)(
            SymbolNode(14...16)(
              nil,
              LABEL(14...15)("a"),
              LABEL_END(15...16)(":"),
              "a"
            ),
            IntegerNode(17...18)(),
            nil
          )],
         BRACE_RIGHT(18...19)("}")
       ),
       HashPatternNode(23...25)(
         nil,
         [AssocNode(23...25)(
            SymbolNode(23...25)(
              nil,
              LABEL(23...24)("a"),
              LABEL_END(24...25)(":"),
              "a"
            ),
            nil,
            nil
          )],
         nil,
         nil,
         nil
       ),
       (20...22)
     ),
     MatchPredicateNode(27...39)(
       HashNode(27...33)(
         BRACE_LEFT(27...28)("{"),
         [AssocNode(28...32)(
            SymbolNode(28...30)(
              nil,
              LABEL(28...29)("a"),
              LABEL_END(29...30)(":"),
              "a"
            ),
            IntegerNode(31...32)(),
            nil
          )],
         BRACE_RIGHT(32...33)("}")
       ),
       HashPatternNode(37...39)(
         nil,
         [AssocNode(37...39)(
            SymbolNode(37...39)(
              nil,
              LABEL(37...38)("a"),
              LABEL_END(38...39)(":"),
              "a"
            ),
            nil,
            nil
          )],
         nil,
         nil,
         nil
       ),
       (34...36)
     ),
     MatchPredicateNode(40...52)(
       HashNode(40...46)(
         BRACE_LEFT(40...41)("{"),
         [AssocNode(41...45)(
            SymbolNode(41...43)(
              nil,
              LABEL(41...42)("a"),
              LABEL_END(42...43)(":"),
              "a"
            ),
            IntegerNode(44...45)(),
            nil
          )],
         BRACE_RIGHT(45...46)("}")
       ),
       HashPatternNode(50...52)(
         nil,
         [AssocNode(50...52)(
            SymbolNode(50...52)(
              nil,
              LABEL(50...51)("a"),
              LABEL_END(51...52)(":"),
              "a"
            ),
            nil,
            nil
          )],
         nil,
         nil,
         nil
       ),
       (47...49)
     )]
  )
)
