ProgramNode(0...74)(
  ScopeNode(0...0)([]),
  StatementsNode(0...74)(
    [CaseNode(0...40)(
       CallNode(5...8)(
         nil,
         nil,
         IDENTIFIER(5...8)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       [InNode(9...21)(
          HashPatternNode(12...14)(
            nil,
            [AssocNode(12...14)(
               SymbolNode(12...14)(
                 nil,
                 LABEL(12...13)("a"),
                 LABEL_END(13...14)(":"),
                 "a"
               ),
               nil,
               nil
             )],
            nil,
            nil,
            nil
          ),
          StatementsNode(15...21)(
            [IntegerNode(15...16)(), TrueNode(17...21)()]
          ),
          (9...11),
          nil
        ),
        InNode(22...36)(
          HashPatternNode(25...29)(
            nil,
            [AssocNode(25...29)(
               SymbolNode(25...29)(
                 STRING_BEGIN(25...26)("\""),
                 STRING_CONTENT(26...27)("b"),
                 LABEL_END(27...29)("\":"),
                 "b"
               ),
               nil,
               nil
             )],
            nil,
            nil,
            nil
          ),
          StatementsNode(30...36)(
            [IntegerNode(30...31)(), TrueNode(32...36)()]
          ),
          (22...24),
          nil
        )],
       nil,
       (0...4),
       (37...40)
     ),
     CallNode(42...58)(
       CallNode(42...45)(
         nil,
         nil,
         IDENTIFIER(42...45)("obj"),
         nil,
         nil,
         nil,
         nil,
         "obj"
       ),
       DOT(45...46)("."),
       IDENTIFIER(46...49)("set"),
       nil,
       ArgumentsNode(50...58)(
         [HashNode(50...58)(
            nil,
            [AssocNode(50...58)(
               SymbolNode(50...56)(
                 STRING_BEGIN(50...51)("\""),
                 STRING_CONTENT(51...54)("foo"),
                 LABEL_END(54...56)("\":"),
                 "foo"
               ),
               IntegerNode(57...58)(),
               nil
             )],
            nil
          )]
       ),
       nil,
       nil,
       "set"
     ),
     CallNode(60...74)(
       CallNode(60...63)(
         nil,
         nil,
         IDENTIFIER(60...63)("obj"),
         nil,
         nil,
         nil,
         nil,
         "obj"
       ),
       DOT(63...64)("."),
       IDENTIFIER(64...67)("set"),
       nil,
       ArgumentsNode(68...74)(
         [HashNode(68...74)(
            nil,
            [AssocNode(68...74)(
               SymbolNode(68...72)(
                 nil,
                 LABEL(68...71)("foo"),
                 LABEL_END(71...72)(":"),
                 "foo"
               ),
               IntegerNode(73...74)(),
               nil
             )],
            nil
          )]
       ),
       nil,
       nil,
       "set"
     )]
  )
)
