ProgramNode(0...65)(
  ScopeNode(0...0)([]),
  StatementsNode(0...65)(
    [LambdaNode(0...13)(
       ScopeNode(0...2)([]),
       MINUS_GREATER(0...2)("->"),
       nil,
       StatementsNode(6...13)(
         [CallNode(6...13)(
            CallNode(6...8)(
              nil,
              nil,
              IDENTIFIER(6...8)("_1"),
              nil,
              nil,
              nil,
              nil,
              "_1"
            ),
            nil,
            PLUS(9...10)("+"),
            nil,
            ArgumentsNode(11...13)(
              [CallNode(11...13)(
                 nil,
                 nil,
                 IDENTIFIER(11...13)("_9"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "_9"
               )]
            ),
            nil,
            nil,
            "+"
          )]
       )
     ),
     LambdaNode(19...31)(
       ScopeNode(19...21)([]),
       MINUS_GREATER(19...21)("->"),
       nil,
       StatementsNode(24...31)(
         [CallNode(24...31)(
            CallNode(24...26)(
              nil,
              nil,
              IDENTIFIER(24...26)("_1"),
              nil,
              nil,
              nil,
              nil,
              "_1"
            ),
            nil,
            PLUS(27...28)("+"),
            nil,
            ArgumentsNode(29...31)(
              [CallNode(29...31)(
                 nil,
                 nil,
                 IDENTIFIER(29...31)("_9"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "_9"
               )]
            ),
            nil,
            nil,
            "+"
          )]
       )
     ),
     CallNode(34...50)(
       nil,
       nil,
       IDENTIFIER(34...35)("m"),
       nil,
       nil,
       nil,
       BlockNode(36...50)(
         ScopeNode(36...38)([]),
         nil,
         StatementsNode(39...46)(
           [CallNode(39...46)(
              CallNode(39...41)(
                nil,
                nil,
                IDENTIFIER(39...41)("_1"),
                nil,
                nil,
                nil,
                nil,
                "_1"
              ),
              nil,
              PLUS(42...43)("+"),
              nil,
              ArgumentsNode(44...46)(
                [CallNode(44...46)(
                   nil,
                   nil,
                   IDENTIFIER(44...46)("_9"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "_9"
                 )]
              ),
              nil,
              nil,
              "+"
            )]
         ),
         (36...38),
         (47...50)
       ),
       "m"
     ),
     CallNode(52...65)(
       nil,
       nil,
       IDENTIFIER(52...53)("m"),
       nil,
       nil,
       nil,
       BlockNode(54...65)(
         ScopeNode(54...55)([]),
         nil,
         StatementsNode(56...63)(
           [CallNode(56...63)(
              CallNode(56...58)(
                nil,
                nil,
                IDENTIFIER(56...58)("_1"),
                nil,
                nil,
                nil,
                nil,
                "_1"
              ),
              nil,
              PLUS(59...60)("+"),
              nil,
              ArgumentsNode(61...63)(
                [CallNode(61...63)(
                   nil,
                   nil,
                   IDENTIFIER(61...63)("_9"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "_9"
                 )]
              ),
              nil,
              nil,
              "+"
            )]
         ),
         (54...55),
         (64...65)
       ),
       "m"
     )]
  )
)
