ProgramNode(0...83)(
  ScopeNode(0...0)([]),
  StatementsNode(0...83)(
    [CallNode(0...2)(
       nil,
       nil,
       IDENTIFIER(0...2)("_1"),
       nil,
       nil,
       nil,
       nil,
       "_1"
     ),
     SingletonClassNode(4...25)(
       ScopeNode(4...9)([]),
       KEYWORD_CLASS(4...9)("class"),
       LESS_LESS(10...12)("<<"),
       CallNode(13...16)(
         nil,
         nil,
         IDENTIFIER(13...16)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(18...20)(
         [CallNode(18...20)(
            nil,
            nil,
            IDENTIFIER(18...20)("_1"),
            nil,
            nil,
            nil,
            nil,
            "_1"
          )]
       ),
       KEYWORD_END(22...25)("end")
     ),
     ClassNode(27...43)(
       ScopeNode(27...32)([]),
       KEYWORD_CLASS(27...32)("class"),
       ConstantReadNode(33...34)(),
       nil,
       nil,
       StatementsNode(36...38)(
         [CallNode(36...38)(
            nil,
            nil,
            IDENTIFIER(36...38)("_1"),
            nil,
            nil,
            nil,
            nil,
            "_1"
          )]
       ),
       KEYWORD_END(40...43)("end")
     ),
     DefNode(45...64)(
       IDENTIFIER(54...55)("m"),
       SelfNode(49...53)(),
       nil,
       StatementsNode(57...59)(
         [CallNode(57...59)(
            nil,
            nil,
            IDENTIFIER(57...59)("_1"),
            nil,
            nil,
            nil,
            nil,
            "_1"
          )]
       ),
       ScopeNode(45...48)([]),
       (45...48),
       (53...54),
       nil,
       nil,
       nil,
       (61...64)
     ),
     ModuleNode(66...83)(
       ScopeNode(66...72)([]),
       KEYWORD_MODULE(66...72)("module"),
       ConstantReadNode(73...74)(),
       StatementsNode(76...78)(
         [CallNode(76...78)(
            nil,
            nil,
            IDENTIFIER(76...78)("_1"),
            nil,
            nil,
            nil,
            nil,
            "_1"
          )]
       ),
       KEYWORD_END(80...83)("end")
     )]
  )
)
