ProgramNode(0...35)(
  ScopeNode(0...0)([]),
  StatementsNode(0...35)(
    [OperatorAssignmentNode(0...10)(
       CallNode(0...5)(
         CallNode(0...3)(
           nil,
           nil,
           IDENTIFIER(0...3)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         DOT(3...4)("."),
         CONSTANT(4...5)("A"),
         nil,
         nil,
         nil,
         nil,
         "A="
       ),
       PLUS_EQUAL(6...8)("+="),
       IntegerNode(9...10)()
     ),
     OperatorAssignmentNode(12...22)(
       CallNode(12...17)(
         CallNode(12...15)(
           nil,
           nil,
           IDENTIFIER(12...15)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         DOT(15...16)("."),
         IDENTIFIER(16...17)("a"),
         nil,
         nil,
         nil,
         nil,
         "a="
       ),
       PLUS_EQUAL(18...20)("+="),
       IntegerNode(21...22)()
     ),
     OperatorAssignmentNode(24...35)(
       CallNode(24...30)(
         CallNode(24...27)(
           nil,
           nil,
           IDENTIFIER(24...27)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         COLON_COLON(27...29)("::"),
         IDENTIFIER(29...30)("a"),
         nil,
         nil,
         nil,
         nil,
         "a="
       ),
       PLUS_EQUAL(31...33)("+="),
       IntegerNode(34...35)()
     )]
  )
)
