ProgramNode(0...14)(
  ScopeNode(0...0)([]),
  StatementsNode(0...14)(
    [OperatorAssignmentNode(0...14)(
       CallNode(0...9)(
         CallNode(0...3)(
           nil,
           nil,
           IDENTIFIER(0...3)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         ),
         nil,
         BRACKET_LEFT_RIGHT_EQUAL(3...4)("["),
         BRACKET_LEFT(3...4)("["),
         ArgumentsNode(4...8)([IntegerNode(4...5)(), IntegerNode(7...8)()]),
         BRACKET_RIGHT(8...9)("]"),
         nil,
         "[]="
       ),
       PLUS_EQUAL(10...12)("+="),
       IntegerNode(13...14)()
     )]
  )
)
