ProgramNode(0...44)(
  ScopeNode(0...0)([]),
  StatementsNode(0...44)(
    [DefNode(0...18)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...13)(
         [],
         [OptionalParameterNode(6...13)(
            IDENTIFIER(6...9)("foo"),
            EQUAL(10...11)("="),
            IntegerNode(12...13)()
          )],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([IDENTIFIER(6...9)("foo")]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (15...18)
     ),
     DefNode(20...44)(
       IDENTIFIER(24...25)("f"),
       nil,
       ParametersNode(26...38)(
         [],
         [OptionalParameterNode(26...31)(
            IDENTIFIER(26...29)("foo"),
            EQUAL(29...30)("="),
            IntegerNode(30...31)()
          ),
          OptionalParameterNode(33...38)(
            IDENTIFIER(33...36)("bar"),
            EQUAL(36...37)("="),
            IntegerNode(37...38)()
          )],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(20...23)(
         [IDENTIFIER(26...29)("foo"), IDENTIFIER(33...36)("bar")]
       ),
       (20...23),
       nil,
       (25...26),
       (38...39),
       nil,
       (41...44)
     )]
  )
)
