ProgramNode(0...22)(
  ScopeNode(0...0)([]),
  StatementsNode(0...22)(
    [OrNode(0...10)(
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       CallNode(7...10)(
         nil,
         nil,
         IDENTIFIER(7...10)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       (4...6)
     ),
     OrNode(12...22)(
       CallNode(12...15)(
         nil,
         nil,
         IDENTIFIER(12...15)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       CallNode(19...22)(
         nil,
         nil,
         IDENTIFIER(19...22)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       (16...18)
     )]
  )
)
