ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [ClassNode(0...15)(
       ScopeNode(0...5)([]),
       KEYWORD_CLASS(0...5)("class"),
       ConstantReadNode(6...7)(),
       LESS(8...9)("<"),
       ConstantReadNode(10...11)(),
       nil,
       KEYWORD_END(12...15)("end")
     )]
  )
)
