ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [LambdaNode(0...11)(
       ScopeNode(0...2)([IDENTIFIER(4...7)("arg")]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(3...11)(
         ParametersNode(4...10)(
           [],
           [OptionalParameterNode(4...10)(
              IDENTIFIER(4...7)("arg"),
              EQUAL(7...8)("="),
              HashNode(8...10)(
                BRACE_LEFT(8...9)("{"),
                [],
                BRACE_RIGHT(9...10)("}")
              )
            )],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (3...4),
         (10...11)
       ),
       nil
     )]
  )
)
