ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [CallNode(0...15)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...4)([InstanceVariableReadNode(2...4)()]),
       nil,
       BlockNode(5...15)(
         ScopeNode(5...7)([IDENTIFIER(9...10)("c")]),
         BlockParametersNode(8...11)(
           ParametersNode(9...10)(
             [RequiredParameterNode(9...10)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (8...9),
           (10...11)
         ),
         StatementsNode(0...0)([]),
         (5...7),
         (12...15)
       ),
       "a"
     )]
  )
)
