ProgramNode(0...14)(
  ScopeNode(0...0)([]),
  StatementsNode(0...14)(
    [CallNode(0...14)(
       nil,
       nil,
       IDENTIFIER(0...1)("m"),
       nil,
       ArgumentsNode(2...7)(
         [CallNode(2...7)(
            CallNode(2...3)(
              nil,
              nil,
              IDENTIFIER(2...3)("a"),
              nil,
              nil,
              nil,
              nil,
              "a"
            ),
            nil,
            PLUS(4...5)("+"),
            nil,
            ArgumentsNode(6...7)(
              [CallNode(6...7)(
                 nil,
                 nil,
                 IDENTIFIER(6...7)("b"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "b"
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       BlockNode(8...14)(ScopeNode(8...10)([]), nil, nil, (8...10), (11...14)),
       "m"
     )]
  )
)
