ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [RegularExpressionNode(0...4)(
       REGEXP_BEGIN(0...1)("/"),
       STRING_CONTENT(1...3)("\\("),
       REGEXP_END(3...4)("/"),
       "("
     )]
  )
)
