ProgramNode(0...132)(
  ScopeNode(0...0)([]),
  StatementsNode(0...132)(
    [DefNode(0...39)(
       IDENTIFIER(4...5)("m"),
       nil,
       nil,
       StatementsNode(7...34)(
         [SingletonClassNode(7...34)(
            ScopeNode(7...12)([]),
            KEYWORD_CLASS(7...12)("class"),
            LESS_LESS(13...15)("<<"),
            SelfNode(16...20)(),
            StatementsNode(22...29)(
              [ConstantPathWriteNode(22...29)(
                 ConstantReadNode(22...23)(),
                 EQUAL(24...25)("="),
                 NilNode(26...29)()
               )]
            ),
            KEYWORD_END(31...34)("end")
          )]
       ),
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (36...39)
     ),
     DefNode(41...85)(
       IDENTIFIER(45...46)("m"),
       nil,
       nil,
       StatementsNode(48...80)(
         [SingletonClassNode(48...80)(
            ScopeNode(48...53)([]),
            KEYWORD_CLASS(48...53)("class"),
            LESS_LESS(54...56)("<<"),
            SelfNode(57...61)(),
            StatementsNode(63...75)(
              [ClassNode(63...75)(
                 ScopeNode(63...68)([]),
                 KEYWORD_CLASS(63...68)("class"),
                 ConstantReadNode(69...70)(),
                 nil,
                 nil,
                 nil,
                 KEYWORD_END(72...75)("end")
               )]
            ),
            KEYWORD_END(77...80)("end")
          )]
       ),
       ScopeNode(41...44)([]),
       (41...44),
       nil,
       nil,
       nil,
       nil,
       (82...85)
     ),
     DefNode(87...132)(
       IDENTIFIER(91...92)("m"),
       nil,
       nil,
       StatementsNode(94...127)(
         [SingletonClassNode(94...127)(
            ScopeNode(94...99)([]),
            KEYWORD_CLASS(94...99)("class"),
            LESS_LESS(100...102)("<<"),
            SelfNode(103...107)(),
            StatementsNode(109...122)(
              [ModuleNode(109...122)(
                 ScopeNode(109...115)([]),
                 KEYWORD_MODULE(109...115)("module"),
                 ConstantReadNode(116...117)(),
                 nil,
                 KEYWORD_END(119...122)("end")
               )]
            ),
            KEYWORD_END(124...127)("end")
          )]
       ),
       ScopeNode(87...90)([]),
       (87...90),
       nil,
       nil,
       nil,
       nil,
       (129...132)
     )]
  )
)
