ProgramNode(8...111)(
  ScopeNode(0...0)([]),
  StatementsNode(8...111)(
    [CaseNode(8...111)(
       ArrayNode(13...51)(
         [SourceFileNode(14...22)("/fixtures/whitequark/pattern_matching__FILE__LINE_literals.rb"),
          CallNode(24...36)(
            SourceLineNode(24...32)(),
            nil,
            PLUS(33...34)("+"),
            nil,
            ArgumentsNode(35...36)([IntegerNode(35...36)()]),
            nil,
            nil,
            "+"
          ),
          SourceEncodingNode(38...50)()],
         BRACKET_LEFT_ARRAY(13...14)("["),
         BRACKET_RIGHT(50...51)("]")
       ),
       [InNode(62...99)(
          ArrayPatternNode(65...99)(
            nil,
            [SourceFileNode(66...74)("/fixtures/whitequark/pattern_matching__FILE__LINE_literals.rb"),
             SourceLineNode(76...84)(),
             SourceEncodingNode(86...98)()],
            nil,
            [],
            (65...66),
            (98...99)
          ),
          nil,
          (62...64),
          nil
        )],
       nil,
       (8...12),
       (108...111)
     )]
  )
)
