ProgramNode(0...10)(
  ScopeNode(0...0)([]),
  StatementsNode(0...10)(
    [RegularExpressionNode(0...10)(
       REGEXP_BEGIN(0...1)("/"),
       STRING_CONTENT(1...7)("source"),
       REGEXP_END(7...10)("/im"),
       "source"
     )]
  )
)
