ProgramNode(0...44)(
  ScopeNode(0...0)([]),
  StatementsNode(0...44)(
    [BeginNode(0...44)(
       KEYWORD_BEGIN(0...5)("begin"),
       StatementsNode(7...11)(
         [CallNode(7...11)(
            nil,
            nil,
            IDENTIFIER(7...11)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       ),
       RescueNode(13...39)(
         KEYWORD_RESCUE(13...19)("rescue"),
         [ConstantReadNode(20...29)(),
          CallNode(31...34)(
            nil,
            nil,
            IDENTIFIER(31...34)("foo"),
            nil,
            nil,
            nil,
            nil,
            "foo"
          )],
         nil,
         nil,
         StatementsNode(36...39)(
           [CallNode(36...39)(
              nil,
              nil,
              IDENTIFIER(36...39)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            )]
         ),
         nil
       ),
       nil,
       nil,
       KEYWORD_END(41...44)("end")
     )]
  )
)
