ProgramNode(0...29)(
  ScopeNode(0...0)([]),
  StatementsNode(0...29)(
    [BeginNode(0...29)(
       KEYWORD_BEGIN(0...5)("begin"),
       StatementsNode(7...11)(
         [CallNode(7...11)(
            nil,
            nil,
            IDENTIFIER(7...11)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       ),
       RescueNode(13...24)(
         KEYWORD_RESCUE(13...19)("rescue"),
         [],
         nil,
         nil,
         StatementsNode(21...24)(
           [CallNode(21...24)(
              nil,
              nil,
              IDENTIFIER(21...24)("foo"),
              nil,
              nil,
              nil,
              nil,
              "foo"
            )]
         ),
         nil
       ),
       nil,
       nil,
       KEYWORD_END(26...29)("end")
     )]
  )
)
