ProgramNode(0...30)(
  ScopeNode(0...0)([]),
  StatementsNode(0...30)(
    [CallNode(0...30)(
       nil,
       nil,
       IDENTIFIER(0...4)("meth"),
       nil,
       nil,
       nil,
       BlockNode(5...30)(
         ScopeNode(5...7)([]),
         nil,
         BeginNode(0...30)(
           nil,
           StatementsNode(9...12)(
             [CallNode(9...12)(
                nil,
                nil,
                IDENTIFIER(9...12)("foo"),
                nil,
                nil,
                nil,
                nil,
                "foo"
              )]
           ),
           RescueNode(14...25)(
             KEYWORD_RESCUE(14...20)("rescue"),
             [],
             nil,
             nil,
             StatementsNode(22...25)(
               [CallNode(22...25)(
                  nil,
                  nil,
                  IDENTIFIER(22...25)("bar"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "bar"
                )]
             ),
             nil
           ),
           nil,
           nil,
           KEYWORD_END(27...30)("end")
         ),
         (5...7),
         (27...30)
       ),
       "meth"
     )]
  )
)
