ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [DefNode(0...16)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...10)(
         [],
         [],
         [],
         RestParameterNode(6...10)(
           USTAR(6...7)("*"),
           IDENTIFIER(7...10)("foo")
         ),
         [],
         nil,
         nil
       ),
       nil,
       ScopeNode(0...3)([IDENTIFIER(7...10)("foo")]),
       (0...3),
       nil,
       (5...6),
       (10...11),
       nil,
       (13...16)
     )]
  )
)
