ProgramNode(0...21)(
  ScopeNode(0...0)([]),
  StatementsNode(0...21)(
    [ReturnNode(0...21)(
       KEYWORD_RETURN(0...6)("return"),
       ArgumentsNode(7...21)(
         [CallNode(7...21)(
            nil,
            nil,
            IDENTIFIER(7...10)("fun"),
            nil,
            ArgumentsNode(11...14)(
              [CallNode(11...14)(
                 nil,
                 nil,
                 IDENTIFIER(11...14)("foo"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "foo"
               )]
            ),
            nil,
            BlockNode(15...21)(
              ScopeNode(15...17)([]),
              nil,
              nil,
              (15...17),
              (18...21)
            ),
            "fun"
          )]
       )
     )]
  )
)
