ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [CallNode(0...23)(
       nil,
       nil,
       IDENTIFIER(0...3)("let"),
       nil,
       ArgumentsNode(4...6)([ParenthesesNode(4...6)(nil, (4...5), (5...6))]),
       nil,
       BlockNode(7...23)(
         ScopeNode(7...8)([]),
         nil,
         StatementsNode(9...21)(
           [CallNode(9...21)(
              nil,
              nil,
              IDENTIFIER(9...10)("m"),
              PARENTHESIS_LEFT(10...11)("("),
              ArgumentsNode(11...12)(
                [CallNode(11...12)(
                   nil,
                   nil,
                   IDENTIFIER(11...12)("a"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "a"
                 )]
              ),
              PARENTHESIS_RIGHT(12...13)(")"),
              BlockNode(14...21)(
                ScopeNode(14...16)([]),
                nil,
                StatementsNode(0...0)([]),
                (14...16),
                (18...21)
              ),
              "m"
            )]
         ),
         (7...8),
         (22...23)
       ),
       "let"
     )]
  )
)
