ProgramNode(0...444)(
  ScopeNode(0...0)([]),
  StatementsNode(0...444)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...11)(
         [CallNode(2...8)(
            nil,
            nil,
            IDENTIFIER(2...3)("b"),
            PARENTHESIS_LEFT(3...4)("("),
            ArgumentsNode(4...7)(
              [CallNode(4...7)(
                 nil,
                 nil,
                 IDENTIFIER(4...5)("c"),
                 nil,
                 ArgumentsNode(6...7)(
                   [CallNode(6...7)(
                      nil,
                      nil,
                      IDENTIFIER(6...7)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(7...8)(")"),
            nil,
            "b"
          ),
          IntegerNode(10...11)()]
       ),
       nil,
       BlockNode(12...18)(
         ScopeNode(12...14)([]),
         nil,
         nil,
         (12...14),
         (15...18)
       ),
       "a"
     ),
     CallNode(20...40)(
       nil,
       nil,
       IDENTIFIER(20...21)("a"),
       nil,
       ArgumentsNode(22...33)(
         [CallNode(22...28)(
            nil,
            nil,
            IDENTIFIER(22...23)("b"),
            PARENTHESIS_LEFT(23...24)("("),
            ArgumentsNode(24...27)(
              [CallNode(24...27)(
                 nil,
                 nil,
                 IDENTIFIER(24...25)("c"),
                 nil,
                 ArgumentsNode(26...27)(
                   [CallNode(26...27)(
                      nil,
                      nil,
                      IDENTIFIER(26...27)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(27...28)(")"),
            nil,
            "b"
          ),
          FloatNode(30...33)()]
       ),
       nil,
       BlockNode(34...40)(
         ScopeNode(34...36)([]),
         nil,
         nil,
         (34...36),
         (37...40)
       ),
       "a"
     ),
     CallNode(42...63)(
       nil,
       nil,
       IDENTIFIER(42...43)("a"),
       nil,
       ArgumentsNode(44...56)(
         [CallNode(44...50)(
            nil,
            nil,
            IDENTIFIER(44...45)("b"),
            PARENTHESIS_LEFT(45...46)("("),
            ArgumentsNode(46...49)(
              [CallNode(46...49)(
                 nil,
                 nil,
                 IDENTIFIER(46...47)("c"),
                 nil,
                 ArgumentsNode(48...49)(
                   [CallNode(48...49)(
                      nil,
                      nil,
                      IDENTIFIER(48...49)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(49...50)(")"),
            nil,
            "b"
          ),
          ImaginaryNode(52...56)(FloatNode(52...55)())]
       ),
       nil,
       BlockNode(57...63)(
         ScopeNode(57...59)([]),
         nil,
         nil,
         (57...59),
         (60...63)
       ),
       "a"
     ),
     CallNode(65...86)(
       nil,
       nil,
       IDENTIFIER(65...66)("a"),
       nil,
       ArgumentsNode(67...79)(
         [CallNode(67...73)(
            nil,
            nil,
            IDENTIFIER(67...68)("b"),
            PARENTHESIS_LEFT(68...69)("("),
            ArgumentsNode(69...72)(
              [CallNode(69...72)(
                 nil,
                 nil,
                 IDENTIFIER(69...70)("c"),
                 nil,
                 ArgumentsNode(71...72)(
                   [CallNode(71...72)(
                      nil,
                      nil,
                      IDENTIFIER(71...72)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(72...73)(")"),
            nil,
            "b"
          ),
          RationalNode(75...79)(FloatNode(75...78)())]
       ),
       nil,
       BlockNode(80...86)(
         ScopeNode(80...82)([]),
         nil,
         nil,
         (80...82),
         (83...86)
       ),
       "a"
     ),
     CallNode(88...107)(
       nil,
       nil,
       IDENTIFIER(88...89)("a"),
       nil,
       ArgumentsNode(90...100)(
         [CallNode(90...96)(
            nil,
            nil,
            IDENTIFIER(90...91)("b"),
            PARENTHESIS_LEFT(91...92)("("),
            ArgumentsNode(92...95)(
              [CallNode(92...95)(
                 nil,
                 nil,
                 IDENTIFIER(92...93)("c"),
                 nil,
                 ArgumentsNode(94...95)(
                   [CallNode(94...95)(
                      nil,
                      nil,
                      IDENTIFIER(94...95)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(95...96)(")"),
            nil,
            "b"
          ),
          SymbolNode(98...100)(
            SYMBOL_BEGIN(98...99)(":"),
            IDENTIFIER(99...100)("e"),
            nil,
            "e"
          )]
       ),
       nil,
       BlockNode(101...107)(
         ScopeNode(101...103)([]),
         nil,
         nil,
         (101...103),
         (104...107)
       ),
       "a"
     ),
     CallNode(109...128)(
       nil,
       nil,
       IDENTIFIER(109...110)("a"),
       nil,
       ArgumentsNode(111...121)(
         [CallNode(111...118)(
            nil,
            nil,
            IDENTIFIER(111...112)("b"),
            PARENTHESIS_LEFT(112...113)("("),
            ArgumentsNode(113...117)(
              [CallNode(113...117)(
                 nil,
                 nil,
                 IDENTIFIER(113...114)("c"),
                 PARENTHESIS_LEFT(114...115)("("),
                 ArgumentsNode(115...116)(
                   [CallNode(115...116)(
                      nil,
                      nil,
                      IDENTIFIER(115...116)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(116...117)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(117...118)(")"),
            nil,
            "b"
          ),
          IntegerNode(120...121)()]
       ),
       nil,
       BlockNode(122...128)(
         ScopeNode(122...124)([]),
         nil,
         nil,
         (122...124),
         (125...128)
       ),
       "a"
     ),
     CallNode(130...151)(
       nil,
       nil,
       IDENTIFIER(130...131)("a"),
       nil,
       ArgumentsNode(132...144)(
         [CallNode(132...139)(
            nil,
            nil,
            IDENTIFIER(132...133)("b"),
            PARENTHESIS_LEFT(133...134)("("),
            ArgumentsNode(134...138)(
              [CallNode(134...138)(
                 nil,
                 nil,
                 IDENTIFIER(134...135)("c"),
                 PARENTHESIS_LEFT(135...136)("("),
                 ArgumentsNode(136...137)(
                   [CallNode(136...137)(
                      nil,
                      nil,
                      IDENTIFIER(136...137)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(137...138)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(138...139)(")"),
            nil,
            "b"
          ),
          FloatNode(141...144)()]
       ),
       nil,
       BlockNode(145...151)(
         ScopeNode(145...147)([]),
         nil,
         nil,
         (145...147),
         (148...151)
       ),
       "a"
     ),
     CallNode(153...175)(
       nil,
       nil,
       IDENTIFIER(153...154)("a"),
       nil,
       ArgumentsNode(155...168)(
         [CallNode(155...162)(
            nil,
            nil,
            IDENTIFIER(155...156)("b"),
            PARENTHESIS_LEFT(156...157)("("),
            ArgumentsNode(157...161)(
              [CallNode(157...161)(
                 nil,
                 nil,
                 IDENTIFIER(157...158)("c"),
                 PARENTHESIS_LEFT(158...159)("("),
                 ArgumentsNode(159...160)(
                   [CallNode(159...160)(
                      nil,
                      nil,
                      IDENTIFIER(159...160)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(160...161)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(161...162)(")"),
            nil,
            "b"
          ),
          ImaginaryNode(164...168)(FloatNode(164...167)())]
       ),
       nil,
       BlockNode(169...175)(
         ScopeNode(169...171)([]),
         nil,
         nil,
         (169...171),
         (172...175)
       ),
       "a"
     ),
     CallNode(177...199)(
       nil,
       nil,
       IDENTIFIER(177...178)("a"),
       nil,
       ArgumentsNode(179...192)(
         [CallNode(179...186)(
            nil,
            nil,
            IDENTIFIER(179...180)("b"),
            PARENTHESIS_LEFT(180...181)("("),
            ArgumentsNode(181...185)(
              [CallNode(181...185)(
                 nil,
                 nil,
                 IDENTIFIER(181...182)("c"),
                 PARENTHESIS_LEFT(182...183)("("),
                 ArgumentsNode(183...184)(
                   [CallNode(183...184)(
                      nil,
                      nil,
                      IDENTIFIER(183...184)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(184...185)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(185...186)(")"),
            nil,
            "b"
          ),
          RationalNode(188...192)(FloatNode(188...191)())]
       ),
       nil,
       BlockNode(193...199)(
         ScopeNode(193...195)([]),
         nil,
         nil,
         (193...195),
         (196...199)
       ),
       "a"
     ),
     CallNode(201...221)(
       nil,
       nil,
       IDENTIFIER(201...202)("a"),
       nil,
       ArgumentsNode(203...214)(
         [CallNode(203...210)(
            nil,
            nil,
            IDENTIFIER(203...204)("b"),
            PARENTHESIS_LEFT(204...205)("("),
            ArgumentsNode(205...209)(
              [CallNode(205...209)(
                 nil,
                 nil,
                 IDENTIFIER(205...206)("c"),
                 PARENTHESIS_LEFT(206...207)("("),
                 ArgumentsNode(207...208)(
                   [CallNode(207...208)(
                      nil,
                      nil,
                      IDENTIFIER(207...208)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(208...209)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(209...210)(")"),
            nil,
            "b"
          ),
          SymbolNode(212...214)(
            SYMBOL_BEGIN(212...213)(":"),
            IDENTIFIER(213...214)("e"),
            nil,
            "e"
          )]
       ),
       nil,
       BlockNode(215...221)(
         ScopeNode(215...217)([]),
         nil,
         nil,
         (215...217),
         (218...221)
       ),
       "a"
     ),
     CallNode(223...241)(
       nil,
       nil,
       IDENTIFIER(223...224)("a"),
       nil,
       ArgumentsNode(225...234)(
         [CallNode(225...231)(
            nil,
            nil,
            IDENTIFIER(225...226)("b"),
            nil,
            nil,
            nil,
            BlockNode(226...231)(
              ScopeNode(226...227)([]),
              nil,
              StatementsNode(227...230)(
                [CallNode(227...230)(
                   nil,
                   nil,
                   IDENTIFIER(227...228)("c"),
                   nil,
                   ArgumentsNode(229...230)(
                     [CallNode(229...230)(
                        nil,
                        nil,
                        IDENTIFIER(229...230)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (226...227),
              (230...231)
            ),
            "b"
          ),
          IntegerNode(233...234)()]
       ),
       nil,
       BlockNode(235...241)(
         ScopeNode(235...237)([]),
         nil,
         nil,
         (235...237),
         (238...241)
       ),
       "a"
     ),
     CallNode(243...263)(
       nil,
       nil,
       IDENTIFIER(243...244)("a"),
       nil,
       ArgumentsNode(245...256)(
         [CallNode(245...251)(
            nil,
            nil,
            IDENTIFIER(245...246)("b"),
            nil,
            nil,
            nil,
            BlockNode(246...251)(
              ScopeNode(246...247)([]),
              nil,
              StatementsNode(247...250)(
                [CallNode(247...250)(
                   nil,
                   nil,
                   IDENTIFIER(247...248)("c"),
                   nil,
                   ArgumentsNode(249...250)(
                     [CallNode(249...250)(
                        nil,
                        nil,
                        IDENTIFIER(249...250)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (246...247),
              (250...251)
            ),
            "b"
          ),
          FloatNode(253...256)()]
       ),
       nil,
       BlockNode(257...263)(
         ScopeNode(257...259)([]),
         nil,
         nil,
         (257...259),
         (260...263)
       ),
       "a"
     ),
     CallNode(265...286)(
       nil,
       nil,
       IDENTIFIER(265...266)("a"),
       nil,
       ArgumentsNode(267...279)(
         [CallNode(267...273)(
            nil,
            nil,
            IDENTIFIER(267...268)("b"),
            nil,
            nil,
            nil,
            BlockNode(268...273)(
              ScopeNode(268...269)([]),
              nil,
              StatementsNode(269...272)(
                [CallNode(269...272)(
                   nil,
                   nil,
                   IDENTIFIER(269...270)("c"),
                   nil,
                   ArgumentsNode(271...272)(
                     [CallNode(271...272)(
                        nil,
                        nil,
                        IDENTIFIER(271...272)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (268...269),
              (272...273)
            ),
            "b"
          ),
          ImaginaryNode(275...279)(FloatNode(275...278)())]
       ),
       nil,
       BlockNode(280...286)(
         ScopeNode(280...282)([]),
         nil,
         nil,
         (280...282),
         (283...286)
       ),
       "a"
     ),
     CallNode(288...309)(
       nil,
       nil,
       IDENTIFIER(288...289)("a"),
       nil,
       ArgumentsNode(290...302)(
         [CallNode(290...296)(
            nil,
            nil,
            IDENTIFIER(290...291)("b"),
            nil,
            nil,
            nil,
            BlockNode(291...296)(
              ScopeNode(291...292)([]),
              nil,
              StatementsNode(292...295)(
                [CallNode(292...295)(
                   nil,
                   nil,
                   IDENTIFIER(292...293)("c"),
                   nil,
                   ArgumentsNode(294...295)(
                     [CallNode(294...295)(
                        nil,
                        nil,
                        IDENTIFIER(294...295)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (291...292),
              (295...296)
            ),
            "b"
          ),
          RationalNode(298...302)(FloatNode(298...301)())]
       ),
       nil,
       BlockNode(303...309)(
         ScopeNode(303...305)([]),
         nil,
         nil,
         (303...305),
         (306...309)
       ),
       "a"
     ),
     CallNode(311...330)(
       nil,
       nil,
       IDENTIFIER(311...312)("a"),
       nil,
       ArgumentsNode(313...323)(
         [CallNode(313...319)(
            nil,
            nil,
            IDENTIFIER(313...314)("b"),
            nil,
            nil,
            nil,
            BlockNode(314...319)(
              ScopeNode(314...315)([]),
              nil,
              StatementsNode(315...318)(
                [CallNode(315...318)(
                   nil,
                   nil,
                   IDENTIFIER(315...316)("c"),
                   nil,
                   ArgumentsNode(317...318)(
                     [CallNode(317...318)(
                        nil,
                        nil,
                        IDENTIFIER(317...318)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (314...315),
              (318...319)
            ),
            "b"
          ),
          SymbolNode(321...323)(
            SYMBOL_BEGIN(321...322)(":"),
            IDENTIFIER(322...323)("e"),
            nil,
            "e"
          )]
       ),
       nil,
       BlockNode(324...330)(
         ScopeNode(324...326)([]),
         nil,
         nil,
         (324...326),
         (327...330)
       ),
       "a"
     ),
     CallNode(332...351)(
       nil,
       nil,
       IDENTIFIER(332...333)("a"),
       nil,
       ArgumentsNode(334...344)(
         [CallNode(334...341)(
            nil,
            nil,
            IDENTIFIER(334...335)("b"),
            nil,
            nil,
            nil,
            BlockNode(335...341)(
              ScopeNode(335...336)([]),
              nil,
              StatementsNode(336...340)(
                [CallNode(336...340)(
                   nil,
                   nil,
                   IDENTIFIER(336...337)("c"),
                   PARENTHESIS_LEFT(337...338)("("),
                   ArgumentsNode(338...339)(
                     [CallNode(338...339)(
                        nil,
                        nil,
                        IDENTIFIER(338...339)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(339...340)(")"),
                   nil,
                   "c"
                 )]
              ),
              (335...336),
              (340...341)
            ),
            "b"
          ),
          IntegerNode(343...344)()]
       ),
       nil,
       BlockNode(345...351)(
         ScopeNode(345...347)([]),
         nil,
         nil,
         (345...347),
         (348...351)
       ),
       "a"
     ),
     CallNode(353...374)(
       nil,
       nil,
       IDENTIFIER(353...354)("a"),
       nil,
       ArgumentsNode(355...367)(
         [CallNode(355...362)(
            nil,
            nil,
            IDENTIFIER(355...356)("b"),
            nil,
            nil,
            nil,
            BlockNode(356...362)(
              ScopeNode(356...357)([]),
              nil,
              StatementsNode(357...361)(
                [CallNode(357...361)(
                   nil,
                   nil,
                   IDENTIFIER(357...358)("c"),
                   PARENTHESIS_LEFT(358...359)("("),
                   ArgumentsNode(359...360)(
                     [CallNode(359...360)(
                        nil,
                        nil,
                        IDENTIFIER(359...360)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(360...361)(")"),
                   nil,
                   "c"
                 )]
              ),
              (356...357),
              (361...362)
            ),
            "b"
          ),
          FloatNode(364...367)()]
       ),
       nil,
       BlockNode(368...374)(
         ScopeNode(368...370)([]),
         nil,
         nil,
         (368...370),
         (371...374)
       ),
       "a"
     ),
     CallNode(376...398)(
       nil,
       nil,
       IDENTIFIER(376...377)("a"),
       nil,
       ArgumentsNode(378...391)(
         [CallNode(378...385)(
            nil,
            nil,
            IDENTIFIER(378...379)("b"),
            nil,
            nil,
            nil,
            BlockNode(379...385)(
              ScopeNode(379...380)([]),
              nil,
              StatementsNode(380...384)(
                [CallNode(380...384)(
                   nil,
                   nil,
                   IDENTIFIER(380...381)("c"),
                   PARENTHESIS_LEFT(381...382)("("),
                   ArgumentsNode(382...383)(
                     [CallNode(382...383)(
                        nil,
                        nil,
                        IDENTIFIER(382...383)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(383...384)(")"),
                   nil,
                   "c"
                 )]
              ),
              (379...380),
              (384...385)
            ),
            "b"
          ),
          ImaginaryNode(387...391)(FloatNode(387...390)())]
       ),
       nil,
       BlockNode(392...398)(
         ScopeNode(392...394)([]),
         nil,
         nil,
         (392...394),
         (395...398)
       ),
       "a"
     ),
     CallNode(400...422)(
       nil,
       nil,
       IDENTIFIER(400...401)("a"),
       nil,
       ArgumentsNode(402...415)(
         [CallNode(402...409)(
            nil,
            nil,
            IDENTIFIER(402...403)("b"),
            nil,
            nil,
            nil,
            BlockNode(403...409)(
              ScopeNode(403...404)([]),
              nil,
              StatementsNode(404...408)(
                [CallNode(404...408)(
                   nil,
                   nil,
                   IDENTIFIER(404...405)("c"),
                   PARENTHESIS_LEFT(405...406)("("),
                   ArgumentsNode(406...407)(
                     [CallNode(406...407)(
                        nil,
                        nil,
                        IDENTIFIER(406...407)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(407...408)(")"),
                   nil,
                   "c"
                 )]
              ),
              (403...404),
              (408...409)
            ),
            "b"
          ),
          RationalNode(411...415)(FloatNode(411...414)())]
       ),
       nil,
       BlockNode(416...422)(
         ScopeNode(416...418)([]),
         nil,
         nil,
         (416...418),
         (419...422)
       ),
       "a"
     ),
     CallNode(424...444)(
       nil,
       nil,
       IDENTIFIER(424...425)("a"),
       nil,
       ArgumentsNode(426...437)(
         [CallNode(426...433)(
            nil,
            nil,
            IDENTIFIER(426...427)("b"),
            nil,
            nil,
            nil,
            BlockNode(427...433)(
              ScopeNode(427...428)([]),
              nil,
              StatementsNode(428...432)(
                [CallNode(428...432)(
                   nil,
                   nil,
                   IDENTIFIER(428...429)("c"),
                   PARENTHESIS_LEFT(429...430)("("),
                   ArgumentsNode(430...431)(
                     [CallNode(430...431)(
                        nil,
                        nil,
                        IDENTIFIER(430...431)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(431...432)(")"),
                   nil,
                   "c"
                 )]
              ),
              (427...428),
              (432...433)
            ),
            "b"
          ),
          SymbolNode(435...437)(
            SYMBOL_BEGIN(435...436)(":"),
            IDENTIFIER(436...437)("e"),
            nil,
            "e"
          )]
       ),
       nil,
       BlockNode(438...444)(
         ScopeNode(438...440)([]),
         nil,
         nil,
         (438...440),
         (441...444)
       ),
       "a"
     )]
  )
)
