ProgramNode(0...25)(
  ScopeNode(0...0)([]),
  StatementsNode(0...25)(
    [CallNode(0...25)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       nil,
       ArgumentsNode(2...18)(
         [CallNode(2...13)(
            nil,
            nil,
            IDENTIFIER(2...3)("p"),
            nil,
            nil,
            nil,
            BlockNode(3...13)(
              ScopeNode(3...4)([]),
              nil,
              StatementsNode(4...12)(
                [CallNode(4...8)(
                   nil,
                   nil,
                   IDENTIFIER(4...5)("p"),
                   PARENTHESIS_LEFT(5...6)("("),
                   ArgumentsNode(6...7)(
                     [CallNode(6...7)(
                        nil,
                        nil,
                        IDENTIFIER(6...7)("p"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "p"
                      )]
                   ),
                   PARENTHESIS_RIGHT(7...8)(")"),
                   nil,
                   "p"
                 ),
                 CallNode(9...12)(
                   nil,
                   nil,
                   IDENTIFIER(9...10)("p"),
                   nil,
                   ArgumentsNode(11...12)(
                     [CallNode(11...12)(
                        nil,
                        nil,
                        IDENTIFIER(11...12)("p"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "p"
                      )]
                   ),
                   nil,
                   nil,
                   "p"
                 )]
              ),
              (3...4),
              (12...13)
            ),
            "p"
          ),
          CallNode(15...18)(
            nil,
            nil,
            IDENTIFIER(15...18)("tap"),
            nil,
            nil,
            nil,
            nil,
            "tap"
          )]
       ),
       nil,
       BlockNode(19...25)(
         ScopeNode(19...21)([]),
         nil,
         nil,
         (19...21),
         (22...25)
       ),
       "p"
     )]
  )
)
