ProgramNode(0...74)(
  ScopeNode(0...0)([IDENTIFIER(0...1)("a"), IDENTIFIER(5...6)("b")]),
  StatementsNode(0...74)(
    [OperatorAssignmentNode(0...18)(
       LocalVariableWriteNode(0...1)((0...1), nil, nil, 0),
       PLUS_EQUAL(2...4)("+="),
       OperatorAssignmentNode(5...18)(
         LocalVariableWriteNode(5...6)((5...6), nil, nil, 0),
         PLUS_EQUAL(7...9)("+="),
         CallNode(10...18)(
           nil,
           nil,
           IDENTIFIER(10...15)("raise"),
           nil,
           ArgumentsNode(16...18)(
             [SymbolNode(16...18)(
                SYMBOL_BEGIN(16...17)(":"),
                IDENTIFIER(17...18)("x"),
                nil,
                "x"
              )]
           ),
           nil,
           nil,
           "raise"
         )
       )
     ),
     OperatorAssignmentNode(20...37)(
       LocalVariableWriteNode(20...21)((20...21), nil, nil, 0),
       PLUS_EQUAL(22...24)("+="),
       LocalVariableWriteNode(25...37)(
         (25...26),
         CallNode(29...37)(
           nil,
           nil,
           IDENTIFIER(29...34)("raise"),
           nil,
           ArgumentsNode(35...37)(
             [SymbolNode(35...37)(
                SYMBOL_BEGIN(35...36)(":"),
                IDENTIFIER(36...37)("x"),
                nil,
                "x"
              )]
           ),
           nil,
           nil,
           "raise"
         ),
         (27...28),
         0
       )
     ),
     LocalVariableWriteNode(39...56)(
       (39...40),
       OperatorAssignmentNode(43...56)(
         LocalVariableWriteNode(43...44)((43...44), nil, nil, 0),
         PLUS_EQUAL(45...47)("+="),
         CallNode(48...56)(
           nil,
           nil,
           IDENTIFIER(48...53)("raise"),
           nil,
           ArgumentsNode(54...56)(
             [SymbolNode(54...56)(
                SYMBOL_BEGIN(54...55)(":"),
                IDENTIFIER(55...56)("x"),
                nil,
                "x"
              )]
           ),
           nil,
           nil,
           "raise"
         )
       ),
       (41...42),
       0
     ),
     LocalVariableWriteNode(58...74)(
       (58...59),
       LocalVariableWriteNode(62...74)(
         (62...63),
         CallNode(66...74)(
           nil,
           nil,
           IDENTIFIER(66...71)("raise"),
           nil,
           ArgumentsNode(72...74)(
             [SymbolNode(72...74)(
                SYMBOL_BEGIN(72...73)(":"),
                IDENTIFIER(73...74)("x"),
                nil,
                "x"
              )]
           ),
           nil,
           nil,
           "raise"
         ),
         (64...65),
         0
       ),
       (60...61),
       0
     )]
  )
)
