ProgramNode(0...20)(
  ScopeNode(0...0)([]),
  StatementsNode(0...20)(
    [CallNode(0...20)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       nil,
       ArgumentsNode(2...20)(
         [LambdaNode(2...20)(
            ScopeNode(2...4)([]),
            MINUS_GREATER(2...4)("->"),
            BlockParametersNode(4...6)(nil, [], (4...5), (5...6)),
            StatementsNode(10...20)(
              [CallNode(10...20)(
                 nil,
                 nil,
                 IDENTIFIER(10...11)("a"),
                 PARENTHESIS_LEFT(11...12)("("),
                 nil,
                 PARENTHESIS_RIGHT(12...13)(")"),
                 BlockNode(14...20)(
                   ScopeNode(14...16)([]),
                   nil,
                   nil,
                   (14...16),
                   (17...20)
                 ),
                 "a"
               )]
            )
          )]
       ),
       nil,
       nil,
       "p"
     )]
  )
)
