ProgramNode(0...24)(
  ScopeNode(0...0)([]),
  StatementsNode(0...24)(
    [HashNode(0...24)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(1...23)(
          SymbolNode(1...3)(
            nil,
            LABEL(1...2)("a"),
            LABEL_END(2...3)(":"),
            "a"
          ),
          IfNode(4...23)(
            KEYWORD_IF(4...6)("if"),
            TrueNode(7...11)(),
            StatementsNode(17...19)([IntegerNode(17...19)()]),
            nil,
            KEYWORD_END(20...23)("end")
          ),
          nil
        )],
       BRACE_RIGHT(23...24)("}")
     )]
  )
)
