ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [CallNode(0...16)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       ArgumentsNode(2...16)(
         [ParenthesesNode(2...16)(
            StatementsNode(3...15)(
              [RescueModifierNode(3...15)(
                 CallNode(3...4)(
                   nil,
                   nil,
                   IDENTIFIER(3...4)("g"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "g"
                 ),
                 KEYWORD_RESCUE_MODIFIER(5...11)("rescue"),
                 NilNode(12...15)()
               )]
            ),
            (2...3),
            (15...16)
          )]
       ),
       nil,
       nil,
       "f"
     )]
  )
)
