ProgramNode(0...272)(
  ScopeNode(0...0)([]),
  StatementsNode(0...272)(
    [CallNode(0...20)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       ArgumentsNode(2...13)(
         [CallNode(2...8)(
            nil,
            nil,
            IDENTIFIER(2...3)("b"),
            PARENTHESIS_LEFT(3...4)("("),
            ArgumentsNode(4...7)(
              [CallNode(4...7)(
                 nil,
                 nil,
                 IDENTIFIER(4...5)("c"),
                 nil,
                 ArgumentsNode(6...7)(
                   [CallNode(6...7)(
                      nil,
                      nil,
                      IDENTIFIER(6...7)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(7...8)(")"),
            nil,
            "b"
          ),
          StringNode(10...13)(
            STRING_BEGIN(10...11)("\""),
            STRING_CONTENT(11...12)("x"),
            STRING_END(12...13)("\""),
            "x"
          )]
       ),
       nil,
       BlockNode(14...20)(
         ScopeNode(14...16)([]),
         nil,
         nil,
         (14...16),
         (17...20)
       ),
       "a"
     ),
     CallNode(22...42)(
       nil,
       nil,
       IDENTIFIER(22...23)("a"),
       nil,
       ArgumentsNode(24...35)(
         [CallNode(24...30)(
            nil,
            nil,
            IDENTIFIER(24...25)("b"),
            PARENTHESIS_LEFT(25...26)("("),
            ArgumentsNode(26...29)(
              [CallNode(26...29)(
                 nil,
                 nil,
                 IDENTIFIER(26...27)("c"),
                 nil,
                 ArgumentsNode(28...29)(
                   [CallNode(28...29)(
                      nil,
                      nil,
                      IDENTIFIER(28...29)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(29...30)(")"),
            nil,
            "b"
          ),
          RegularExpressionNode(32...35)(
            REGEXP_BEGIN(32...33)("/"),
            STRING_CONTENT(33...34)("x"),
            REGEXP_END(34...35)("/"),
            "x"
          )]
       ),
       nil,
       BlockNode(36...42)(
         ScopeNode(36...38)([]),
         nil,
         nil,
         (36...38),
         (39...42)
       ),
       "a"
     ),
     CallNode(44...65)(
       nil,
       nil,
       IDENTIFIER(44...45)("a"),
       nil,
       ArgumentsNode(46...58)(
         [CallNode(46...52)(
            nil,
            nil,
            IDENTIFIER(46...47)("b"),
            PARENTHESIS_LEFT(47...48)("("),
            ArgumentsNode(48...51)(
              [CallNode(48...51)(
                 nil,
                 nil,
                 IDENTIFIER(48...49)("c"),
                 nil,
                 ArgumentsNode(50...51)(
                   [CallNode(50...51)(
                      nil,
                      nil,
                      IDENTIFIER(50...51)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 nil,
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(51...52)(")"),
            nil,
            "b"
          ),
          RegularExpressionNode(54...58)(
            REGEXP_BEGIN(54...55)("/"),
            STRING_CONTENT(55...56)("x"),
            REGEXP_END(56...58)("/m"),
            "x"
          )]
       ),
       nil,
       BlockNode(59...65)(
         ScopeNode(59...61)([]),
         nil,
         nil,
         (59...61),
         (62...65)
       ),
       "a"
     ),
     CallNode(67...88)(
       nil,
       nil,
       IDENTIFIER(67...68)("a"),
       nil,
       ArgumentsNode(69...81)(
         [CallNode(69...76)(
            nil,
            nil,
            IDENTIFIER(69...70)("b"),
            PARENTHESIS_LEFT(70...71)("("),
            ArgumentsNode(71...75)(
              [CallNode(71...75)(
                 nil,
                 nil,
                 IDENTIFIER(71...72)("c"),
                 PARENTHESIS_LEFT(72...73)("("),
                 ArgumentsNode(73...74)(
                   [CallNode(73...74)(
                      nil,
                      nil,
                      IDENTIFIER(73...74)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(74...75)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(75...76)(")"),
            nil,
            "b"
          ),
          StringNode(78...81)(
            STRING_BEGIN(78...79)("\""),
            STRING_CONTENT(79...80)("x"),
            STRING_END(80...81)("\""),
            "x"
          )]
       ),
       nil,
       BlockNode(82...88)(
         ScopeNode(82...84)([]),
         nil,
         nil,
         (82...84),
         (85...88)
       ),
       "a"
     ),
     CallNode(90...111)(
       nil,
       nil,
       IDENTIFIER(90...91)("a"),
       nil,
       ArgumentsNode(92...104)(
         [CallNode(92...99)(
            nil,
            nil,
            IDENTIFIER(92...93)("b"),
            PARENTHESIS_LEFT(93...94)("("),
            ArgumentsNode(94...98)(
              [CallNode(94...98)(
                 nil,
                 nil,
                 IDENTIFIER(94...95)("c"),
                 PARENTHESIS_LEFT(95...96)("("),
                 ArgumentsNode(96...97)(
                   [CallNode(96...97)(
                      nil,
                      nil,
                      IDENTIFIER(96...97)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(97...98)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(98...99)(")"),
            nil,
            "b"
          ),
          RegularExpressionNode(101...104)(
            REGEXP_BEGIN(101...102)("/"),
            STRING_CONTENT(102...103)("x"),
            REGEXP_END(103...104)("/"),
            "x"
          )]
       ),
       nil,
       BlockNode(105...111)(
         ScopeNode(105...107)([]),
         nil,
         nil,
         (105...107),
         (108...111)
       ),
       "a"
     ),
     CallNode(113...135)(
       nil,
       nil,
       IDENTIFIER(113...114)("a"),
       nil,
       ArgumentsNode(115...128)(
         [CallNode(115...122)(
            nil,
            nil,
            IDENTIFIER(115...116)("b"),
            PARENTHESIS_LEFT(116...117)("("),
            ArgumentsNode(117...121)(
              [CallNode(117...121)(
                 nil,
                 nil,
                 IDENTIFIER(117...118)("c"),
                 PARENTHESIS_LEFT(118...119)("("),
                 ArgumentsNode(119...120)(
                   [CallNode(119...120)(
                      nil,
                      nil,
                      IDENTIFIER(119...120)("d"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "d"
                    )]
                 ),
                 PARENTHESIS_RIGHT(120...121)(")"),
                 nil,
                 "c"
               )]
            ),
            PARENTHESIS_RIGHT(121...122)(")"),
            nil,
            "b"
          ),
          RegularExpressionNode(124...128)(
            REGEXP_BEGIN(124...125)("/"),
            STRING_CONTENT(125...126)("x"),
            REGEXP_END(126...128)("/m"),
            "x"
          )]
       ),
       nil,
       BlockNode(129...135)(
         ScopeNode(129...131)([]),
         nil,
         nil,
         (129...131),
         (132...135)
       ),
       "a"
     ),
     CallNode(137...157)(
       nil,
       nil,
       IDENTIFIER(137...138)("a"),
       nil,
       ArgumentsNode(139...150)(
         [CallNode(139...145)(
            nil,
            nil,
            IDENTIFIER(139...140)("b"),
            nil,
            nil,
            nil,
            BlockNode(140...145)(
              ScopeNode(140...141)([]),
              nil,
              StatementsNode(141...144)(
                [CallNode(141...144)(
                   nil,
                   nil,
                   IDENTIFIER(141...142)("c"),
                   nil,
                   ArgumentsNode(143...144)(
                     [CallNode(143...144)(
                        nil,
                        nil,
                        IDENTIFIER(143...144)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (140...141),
              (144...145)
            ),
            "b"
          ),
          StringNode(147...150)(
            STRING_BEGIN(147...148)("\""),
            STRING_CONTENT(148...149)("x"),
            STRING_END(149...150)("\""),
            "x"
          )]
       ),
       nil,
       BlockNode(151...157)(
         ScopeNode(151...153)([]),
         nil,
         nil,
         (151...153),
         (154...157)
       ),
       "a"
     ),
     CallNode(159...179)(
       nil,
       nil,
       IDENTIFIER(159...160)("a"),
       nil,
       ArgumentsNode(161...172)(
         [CallNode(161...167)(
            nil,
            nil,
            IDENTIFIER(161...162)("b"),
            nil,
            nil,
            nil,
            BlockNode(162...167)(
              ScopeNode(162...163)([]),
              nil,
              StatementsNode(163...166)(
                [CallNode(163...166)(
                   nil,
                   nil,
                   IDENTIFIER(163...164)("c"),
                   nil,
                   ArgumentsNode(165...166)(
                     [CallNode(165...166)(
                        nil,
                        nil,
                        IDENTIFIER(165...166)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (162...163),
              (166...167)
            ),
            "b"
          ),
          RegularExpressionNode(169...172)(
            REGEXP_BEGIN(169...170)("/"),
            STRING_CONTENT(170...171)("x"),
            REGEXP_END(171...172)("/"),
            "x"
          )]
       ),
       nil,
       BlockNode(173...179)(
         ScopeNode(173...175)([]),
         nil,
         nil,
         (173...175),
         (176...179)
       ),
       "a"
     ),
     CallNode(181...202)(
       nil,
       nil,
       IDENTIFIER(181...182)("a"),
       nil,
       ArgumentsNode(183...195)(
         [CallNode(183...189)(
            nil,
            nil,
            IDENTIFIER(183...184)("b"),
            nil,
            nil,
            nil,
            BlockNode(184...189)(
              ScopeNode(184...185)([]),
              nil,
              StatementsNode(185...188)(
                [CallNode(185...188)(
                   nil,
                   nil,
                   IDENTIFIER(185...186)("c"),
                   nil,
                   ArgumentsNode(187...188)(
                     [CallNode(187...188)(
                        nil,
                        nil,
                        IDENTIFIER(187...188)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   nil,
                   nil,
                   "c"
                 )]
              ),
              (184...185),
              (188...189)
            ),
            "b"
          ),
          RegularExpressionNode(191...195)(
            REGEXP_BEGIN(191...192)("/"),
            STRING_CONTENT(192...193)("x"),
            REGEXP_END(193...195)("/m"),
            "x"
          )]
       ),
       nil,
       BlockNode(196...202)(
         ScopeNode(196...198)([]),
         nil,
         nil,
         (196...198),
         (199...202)
       ),
       "a"
     ),
     CallNode(204...225)(
       nil,
       nil,
       IDENTIFIER(204...205)("a"),
       nil,
       ArgumentsNode(206...218)(
         [CallNode(206...213)(
            nil,
            nil,
            IDENTIFIER(206...207)("b"),
            nil,
            nil,
            nil,
            BlockNode(207...213)(
              ScopeNode(207...208)([]),
              nil,
              StatementsNode(208...212)(
                [CallNode(208...212)(
                   nil,
                   nil,
                   IDENTIFIER(208...209)("c"),
                   PARENTHESIS_LEFT(209...210)("("),
                   ArgumentsNode(210...211)(
                     [CallNode(210...211)(
                        nil,
                        nil,
                        IDENTIFIER(210...211)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(211...212)(")"),
                   nil,
                   "c"
                 )]
              ),
              (207...208),
              (212...213)
            ),
            "b"
          ),
          StringNode(215...218)(
            STRING_BEGIN(215...216)("\""),
            STRING_CONTENT(216...217)("x"),
            STRING_END(217...218)("\""),
            "x"
          )]
       ),
       nil,
       BlockNode(219...225)(
         ScopeNode(219...221)([]),
         nil,
         nil,
         (219...221),
         (222...225)
       ),
       "a"
     ),
     CallNode(227...248)(
       nil,
       nil,
       IDENTIFIER(227...228)("a"),
       nil,
       ArgumentsNode(229...241)(
         [CallNode(229...236)(
            nil,
            nil,
            IDENTIFIER(229...230)("b"),
            nil,
            nil,
            nil,
            BlockNode(230...236)(
              ScopeNode(230...231)([]),
              nil,
              StatementsNode(231...235)(
                [CallNode(231...235)(
                   nil,
                   nil,
                   IDENTIFIER(231...232)("c"),
                   PARENTHESIS_LEFT(232...233)("("),
                   ArgumentsNode(233...234)(
                     [CallNode(233...234)(
                        nil,
                        nil,
                        IDENTIFIER(233...234)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(234...235)(")"),
                   nil,
                   "c"
                 )]
              ),
              (230...231),
              (235...236)
            ),
            "b"
          ),
          RegularExpressionNode(238...241)(
            REGEXP_BEGIN(238...239)("/"),
            STRING_CONTENT(239...240)("x"),
            REGEXP_END(240...241)("/"),
            "x"
          )]
       ),
       nil,
       BlockNode(242...248)(
         ScopeNode(242...244)([]),
         nil,
         nil,
         (242...244),
         (245...248)
       ),
       "a"
     ),
     CallNode(250...272)(
       nil,
       nil,
       IDENTIFIER(250...251)("a"),
       nil,
       ArgumentsNode(252...265)(
         [CallNode(252...259)(
            nil,
            nil,
            IDENTIFIER(252...253)("b"),
            nil,
            nil,
            nil,
            BlockNode(253...259)(
              ScopeNode(253...254)([]),
              nil,
              StatementsNode(254...258)(
                [CallNode(254...258)(
                   nil,
                   nil,
                   IDENTIFIER(254...255)("c"),
                   PARENTHESIS_LEFT(255...256)("("),
                   ArgumentsNode(256...257)(
                     [CallNode(256...257)(
                        nil,
                        nil,
                        IDENTIFIER(256...257)("d"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "d"
                      )]
                   ),
                   PARENTHESIS_RIGHT(257...258)(")"),
                   nil,
                   "c"
                 )]
              ),
              (253...254),
              (258...259)
            ),
            "b"
          ),
          RegularExpressionNode(261...265)(
            REGEXP_BEGIN(261...262)("/"),
            STRING_CONTENT(262...263)("x"),
            REGEXP_END(263...265)("/m"),
            "x"
          )]
       ),
       nil,
       BlockNode(266...272)(
         ScopeNode(266...268)([]),
         nil,
         nil,
         (266...268),
         (269...272)
       ),
       "a"
     )]
  )
)
