ProgramNode(0...22)(
  ScopeNode(0...0)([]),
  StatementsNode(0...22)(
    [SingletonClassNode(0...22)(
       ScopeNode(0...5)([]),
       KEYWORD_CLASS(0...5)("class"),
       LESS_LESS(6...8)("<<"),
       CallNode(9...12)(
         nil,
         nil,
         IDENTIFIER(9...12)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(14...17)([NilNode(14...17)()]),
       KEYWORD_END(19...22)("end")
     )]
  )
)
