ProgramNode(0...29)(
  ScopeNode(0...0)([]),
  StatementsNode(0...29)(
    [CallNode(0...7)(
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       DOT(3...4)("."),
       IDENTIFIER(4...7)("fun"),
       nil,
       nil,
       nil,
       nil,
       "fun"
     ),
     CallNode(9...19)(
       CallNode(9...12)(
         nil,
         nil,
         IDENTIFIER(9...12)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       COLON_COLON(12...14)("::"),
       CONSTANT(14...17)("Fun"),
       PARENTHESIS_LEFT(17...18)("("),
       nil,
       PARENTHESIS_RIGHT(18...19)(")"),
       nil,
       "Fun"
     ),
     CallNode(21...29)(
       CallNode(21...24)(
         nil,
         nil,
         IDENTIFIER(21...24)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       COLON_COLON(24...26)("::"),
       IDENTIFIER(26...29)("fun"),
       nil,
       nil,
       nil,
       nil,
       "fun"
     )]
  )
)
