ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [LambdaNode(0...7)(
       ScopeNode(0...2)([LABEL(3...4)("a")]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(3...7)(
         ParametersNode(3...7)(
           [],
           [],
           [],
           nil,
           [KeywordParameterNode(3...7)(
              LABEL(3...5)("a:"),
              IntegerNode(6...7)()
            )],
           nil,
           nil
         ),
         [],
         nil,
         nil
       ),
       nil
     ),
     LambdaNode(13...18)(
       ScopeNode(13...15)([LABEL(16...17)("a")]),
       MINUS_GREATER(13...15)("->"),
       BlockParametersNode(16...18)(
         ParametersNode(16...18)(
           [],
           [],
           [],
           nil,
           [KeywordParameterNode(16...18)(LABEL(16...18)("a:"), nil)],
           nil,
           nil
         ),
         [],
         nil,
         nil
       ),
       nil
     )]
  )
)
