ProgramNode(0...42)(
  ScopeNode(0...0)([]),
  StatementsNode(0...42)(
    [CallNode(0...10)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       nil,
       nil,
       nil,
       BlockNode(4...10)(ScopeNode(4...6)([]), nil, nil, (4...6), (7...10)),
       "fun"
     ),
     CallNode(12...19)(
       nil,
       nil,
       IDENTIFIER(12...15)("fun"),
       nil,
       nil,
       nil,
       BlockNode(16...19)(
         ScopeNode(16...17)([]),
         nil,
         nil,
         (16...17),
         (18...19)
       ),
       "fun"
     ),
     CallNode(21...30)(
       nil,
       nil,
       IDENTIFIER(21...24)("fun"),
       PARENTHESIS_LEFT(24...25)("("),
       nil,
       PARENTHESIS_RIGHT(25...26)(")"),
       BlockNode(27...30)(
         ScopeNode(27...28)([]),
         nil,
         nil,
         (27...28),
         (29...30)
       ),
       "fun"
     ),
     CallNode(32...42)(
       nil,
       nil,
       IDENTIFIER(32...35)("fun"),
       PARENTHESIS_LEFT(35...36)("("),
       ArgumentsNode(36...37)([IntegerNode(36...37)()]),
       PARENTHESIS_RIGHT(37...38)(")"),
       BlockNode(39...42)(
         ScopeNode(39...40)([]),
         nil,
         nil,
         (39...40),
         (41...42)
       ),
       "fun"
     )]
  )
)
