ProgramNode(0...200)(
  ScopeNode(0...0)([]),
  StatementsNode(0...200)(
    [CallNode(0...8)(
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       BANG_EQUAL(4...6)("!="),
       nil,
       ArgumentsNode(7...8)([IntegerNode(7...8)()]),
       nil,
       nil,
       "!="
     ),
     CallNode(10...18)(
       CallNode(10...13)(
         nil,
         nil,
         IDENTIFIER(10...13)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       BANG_TILDE(14...16)("!~"),
       nil,
       ArgumentsNode(17...18)([IntegerNode(17...18)()]),
       nil,
       nil,
       "!~"
     ),
     CallNode(20...27)(
       CallNode(20...23)(
         nil,
         nil,
         IDENTIFIER(20...23)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       PERCENT(24...25)("%"),
       nil,
       ArgumentsNode(26...27)([IntegerNode(26...27)()]),
       nil,
       nil,
       "%"
     ),
     CallNode(29...36)(
       CallNode(29...32)(
         nil,
         nil,
         IDENTIFIER(29...32)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       AMPERSAND(33...34)("&"),
       nil,
       ArgumentsNode(35...36)([IntegerNode(35...36)()]),
       nil,
       nil,
       "&"
     ),
     CallNode(38...45)(
       CallNode(38...41)(
         nil,
         nil,
         IDENTIFIER(38...41)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       STAR(42...43)("*"),
       nil,
       ArgumentsNode(44...45)([IntegerNode(44...45)()]),
       nil,
       nil,
       "*"
     ),
     CallNode(47...55)(
       CallNode(47...50)(
         nil,
         nil,
         IDENTIFIER(47...50)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       STAR_STAR(51...53)("**"),
       nil,
       ArgumentsNode(54...55)([IntegerNode(54...55)()]),
       nil,
       nil,
       "**"
     ),
     CallNode(57...64)(
       CallNode(57...60)(
         nil,
         nil,
         IDENTIFIER(57...60)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       PLUS(61...62)("+"),
       nil,
       ArgumentsNode(63...64)([IntegerNode(63...64)()]),
       nil,
       nil,
       "+"
     ),
     CallNode(66...73)(
       CallNode(66...69)(
         nil,
         nil,
         IDENTIFIER(66...69)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       MINUS(70...71)("-"),
       nil,
       ArgumentsNode(72...73)([IntegerNode(72...73)()]),
       nil,
       nil,
       "-"
     ),
     CallNode(75...82)(
       CallNode(75...78)(
         nil,
         nil,
         IDENTIFIER(75...78)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       SLASH(79...80)("/"),
       nil,
       ArgumentsNode(81...82)([IntegerNode(81...82)()]),
       nil,
       nil,
       "/"
     ),
     CallNode(84...91)(
       CallNode(84...87)(
         nil,
         nil,
         IDENTIFIER(84...87)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       LESS(88...89)("<"),
       nil,
       ArgumentsNode(90...91)([IntegerNode(90...91)()]),
       nil,
       nil,
       "<"
     ),
     CallNode(93...101)(
       CallNode(93...96)(
         nil,
         nil,
         IDENTIFIER(93...96)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       LESS_LESS(97...99)("<<"),
       nil,
       ArgumentsNode(100...101)([IntegerNode(100...101)()]),
       nil,
       nil,
       "<<"
     ),
     CallNode(103...111)(
       CallNode(103...106)(
         nil,
         nil,
         IDENTIFIER(103...106)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       LESS_EQUAL(107...109)("<="),
       nil,
       ArgumentsNode(110...111)([IntegerNode(110...111)()]),
       nil,
       nil,
       "<="
     ),
     CallNode(113...122)(
       CallNode(113...116)(
         nil,
         nil,
         IDENTIFIER(113...116)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       LESS_EQUAL_GREATER(117...120)("<=>"),
       nil,
       ArgumentsNode(121...122)([IntegerNode(121...122)()]),
       nil,
       nil,
       "<=>"
     ),
     CallNode(124...132)(
       CallNode(124...127)(
         nil,
         nil,
         IDENTIFIER(124...127)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       EQUAL_EQUAL(128...130)("=="),
       nil,
       ArgumentsNode(131...132)([IntegerNode(131...132)()]),
       nil,
       nil,
       "=="
     ),
     CallNode(134...143)(
       CallNode(134...137)(
         nil,
         nil,
         IDENTIFIER(134...137)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       EQUAL_EQUAL_EQUAL(138...141)("==="),
       nil,
       ArgumentsNode(142...143)([IntegerNode(142...143)()]),
       nil,
       nil,
       "==="
     ),
     CallNode(145...153)(
       CallNode(145...148)(
         nil,
         nil,
         IDENTIFIER(145...148)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       EQUAL_TILDE(149...151)("=~"),
       nil,
       ArgumentsNode(152...153)([IntegerNode(152...153)()]),
       nil,
       nil,
       "=~"
     ),
     CallNode(155...162)(
       CallNode(155...158)(
         nil,
         nil,
         IDENTIFIER(155...158)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       GREATER(159...160)(">"),
       nil,
       ArgumentsNode(161...162)([IntegerNode(161...162)()]),
       nil,
       nil,
       ">"
     ),
     CallNode(164...172)(
       CallNode(164...167)(
         nil,
         nil,
         IDENTIFIER(164...167)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       GREATER_EQUAL(168...170)(">="),
       nil,
       ArgumentsNode(171...172)([IntegerNode(171...172)()]),
       nil,
       nil,
       ">="
     ),
     CallNode(174...182)(
       CallNode(174...177)(
         nil,
         nil,
         IDENTIFIER(174...177)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       GREATER_GREATER(178...180)(">>"),
       nil,
       ArgumentsNode(181...182)([IntegerNode(181...182)()]),
       nil,
       nil,
       ">>"
     ),
     CallNode(184...191)(
       CallNode(184...187)(
         nil,
         nil,
         IDENTIFIER(184...187)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       CARET(188...189)("^"),
       nil,
       ArgumentsNode(190...191)([IntegerNode(190...191)()]),
       nil,
       nil,
       "^"
     ),
     CallNode(193...200)(
       CallNode(193...196)(
         nil,
         nil,
         IDENTIFIER(193...196)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       PIPE(197...198)("|"),
       nil,
       ArgumentsNode(199...200)([IntegerNode(199...200)()]),
       nil,
       nil,
       "|"
     )]
  )
)
