ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [CallNode(0...13)(
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       BRACKET_LEFT_RIGHT_EQUAL(3...4)("["),
       BRACKET_LEFT(3...4)("["),
       ArgumentsNode(4...13)(
         [IntegerNode(4...5)(), IntegerNode(7...8)(), IntegerNode(12...13)()]
       ),
       BRACKET_RIGHT(8...9)("]"),
       nil,
       "[]="
     )]
  )
)
