ProgramNode(0...15)(
  ScopeNode(0...0)([]),
  StatementsNode(0...15)(
    [LambdaNode(0...15)(
       ScopeNode(0...2)(
         [IDENTIFIER(3...4)("a"),
          IDENTIFIER(6...9)("foo"),
          IDENTIFIER(11...14)("bar")]
       ),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(2...15)(
         ParametersNode(3...4)(
           [RequiredParameterNode(3...4)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [IDENTIFIER(6...9)("foo"), IDENTIFIER(11...14)("bar")],
         (2...3),
         (14...15)
       ),
       nil
     )]
  )
)
