ProgramNode(0...173)(
  ScopeNode(0...0)([]),
  StatementsNode(0...173)(
    [CallNode(0...21)(
       CallNode(0...13)(
         nil,
         nil,
         IDENTIFIER(0...4)("meth"),
         nil,
         ArgumentsNode(5...6)([IntegerNode(5...6)()]),
         nil,
         BlockNode(7...13)(ScopeNode(7...9)([]), nil, nil, (7...9), (10...13)),
         "meth"
       ),
       DOT(13...14)("."),
       IDENTIFIER(14...17)("fun"),
       nil,
       ArgumentsNode(18...21)(
         [CallNode(18...21)(
            nil,
            nil,
            IDENTIFIER(18...21)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       nil,
       "fun"
     ),
     CallNode(23...51)(
       CallNode(23...36)(
         nil,
         nil,
         IDENTIFIER(23...27)("meth"),
         nil,
         ArgumentsNode(28...29)([IntegerNode(28...29)()]),
         nil,
         BlockNode(30...36)(
           ScopeNode(30...32)([]),
           nil,
           nil,
           (30...32),
           (33...36)
         ),
         "meth"
       ),
       DOT(36...37)("."),
       IDENTIFIER(37...40)("fun"),
       nil,
       ArgumentsNode(41...44)(
         [CallNode(41...44)(
            nil,
            nil,
            IDENTIFIER(41...44)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       BlockNode(45...51)(
         ScopeNode(45...47)([]),
         nil,
         nil,
         (45...47),
         (48...51)
       ),
       "fun"
     ),
     CallNode(53...73)(
       CallNode(53...66)(
         nil,
         nil,
         IDENTIFIER(53...57)("meth"),
         nil,
         ArgumentsNode(58...59)([IntegerNode(58...59)()]),
         nil,
         BlockNode(60...66)(
           ScopeNode(60...62)([]),
           nil,
           nil,
           (60...62),
           (63...66)
         ),
         "meth"
       ),
       DOT(66...67)("."),
       IDENTIFIER(67...70)("fun"),
       nil,
       nil,
       nil,
       BlockNode(71...73)(
         ScopeNode(71...72)([]),
         nil,
         nil,
         (71...72),
         (72...73)
       ),
       "fun"
     ),
     CallNode(75...97)(
       CallNode(75...88)(
         nil,
         nil,
         IDENTIFIER(75...79)("meth"),
         nil,
         ArgumentsNode(80...81)([IntegerNode(80...81)()]),
         nil,
         BlockNode(82...88)(
           ScopeNode(82...84)([]),
           nil,
           nil,
           (82...84),
           (85...88)
         ),
         "meth"
       ),
       DOT(88...89)("."),
       IDENTIFIER(89...92)("fun"),
       PARENTHESIS_LEFT(92...93)("("),
       ArgumentsNode(93...96)(
         [CallNode(93...96)(
            nil,
            nil,
            IDENTIFIER(93...96)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       PARENTHESIS_RIGHT(96...97)(")"),
       nil,
       "fun"
     ),
     CallNode(99...124)(
       CallNode(99...112)(
         nil,
         nil,
         IDENTIFIER(99...103)("meth"),
         nil,
         ArgumentsNode(104...105)([IntegerNode(104...105)()]),
         nil,
         BlockNode(106...112)(
           ScopeNode(106...108)([]),
           nil,
           nil,
           (106...108),
           (109...112)
         ),
         "meth"
       ),
       DOT(112...113)("."),
       IDENTIFIER(113...116)("fun"),
       PARENTHESIS_LEFT(116...117)("("),
       ArgumentsNode(117...120)(
         [CallNode(117...120)(
            nil,
            nil,
            IDENTIFIER(117...120)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       PARENTHESIS_RIGHT(120...121)(")"),
       BlockNode(122...124)(
         ScopeNode(122...123)([]),
         nil,
         nil,
         (122...123),
         (123...124)
       ),
       "fun"
     ),
     CallNode(126...148)(
       CallNode(126...139)(
         nil,
         nil,
         IDENTIFIER(126...130)("meth"),
         nil,
         ArgumentsNode(131...132)([IntegerNode(131...132)()]),
         nil,
         BlockNode(133...139)(
           ScopeNode(133...135)([]),
           nil,
           nil,
           (133...135),
           (136...139)
         ),
         "meth"
       ),
       COLON_COLON(139...141)("::"),
       IDENTIFIER(145...148)("bar"),
       nil,
       ArgumentsNode(145...148)(
         [CallNode(145...148)(
            nil,
            nil,
            IDENTIFIER(145...148)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       nil,
       "bar"
     ),
     CallNode(150...173)(
       CallNode(150...163)(
         nil,
         nil,
         IDENTIFIER(150...154)("meth"),
         nil,
         ArgumentsNode(155...156)([IntegerNode(155...156)()]),
         nil,
         BlockNode(157...163)(
           ScopeNode(157...159)([]),
           nil,
           nil,
           (157...159),
           (160...163)
         ),
         "meth"
       ),
       COLON_COLON(163...165)("::"),
       PARENTHESIS_RIGHT(172...173)(")"),
       PARENTHESIS_LEFT(168...169)("("),
       ArgumentsNode(169...172)(
         [CallNode(169...172)(
            nil,
            nil,
            IDENTIFIER(169...172)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       PARENTHESIS_RIGHT(172...173)(")"),
       nil,
       ")"
     )]
  )
)
