ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [LambdaNode(0...4)(
       ScopeNode(0...2)([STAR(3...4)("*")]),
       MINUS_GREATER(0...2)("->"),
       BlockParametersNode(3...4)(
         ParametersNode(3...4)(
           [],
           [],
           [],
           RestParameterNode(3...4)(STAR(3...4)("*"), nil),
           [],
           nil,
           nil
         ),
         [],
         nil,
         nil
       ),
       nil
     ),
     LambdaNode(10...12)(
       ScopeNode(10...12)([]),
       MINUS_GREATER(10...12)("->"),
       nil,
       nil
     ),
     LambdaNode(21...23)(
       ScopeNode(21...23)([]),
       MINUS_GREATER(21...23)("->"),
       nil,
       nil
     )]
  )
)
