ProgramNode(0...16)(
  ScopeNode(0...0)([]),
  StatementsNode(0...16)(
    [CallNode(0...4)(
       CallNode(1...4)(
         nil,
         nil,
         IDENTIFIER(1...4)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       UPLUS(0...1)("+"),
       nil,
       nil,
       nil,
       nil,
       "+@"
     ),
     CallNode(6...10)(
       CallNode(7...10)(
         nil,
         nil,
         IDENTIFIER(7...10)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       UMINUS(6...7)("-"),
       nil,
       nil,
       nil,
       nil,
       "-@"
     ),
     CallNode(12...16)(
       CallNode(13...16)(
         nil,
         nil,
         IDENTIFIER(13...16)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       nil,
       TILDE(12...13)("~"),
       nil,
       nil,
       nil,
       nil,
       "~"
     )]
  )
)
