ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("a"),
         nil,
         nil,
         nil,
         nil,
         "a"
       ),
       AMPERSAND_DOT(1...3)("&."),
       IDENTIFIER(3...4)("b"),
       nil,
       ArgumentsNode(7...8)([IntegerNode(7...8)()]),
       nil,
       nil,
       "b="
     )]
  )
)
