ProgramNode(0...39)(
  ScopeNode(0...0)([]),
  StatementsNode(0...39)(
    [CallNode(0...11)(
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       DOT(3...4)("."),
       IDENTIFIER(4...7)("fun"),
       nil,
       ArgumentsNode(8...11)(
         [CallNode(8...11)(
            nil,
            nil,
            IDENTIFIER(8...11)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       nil,
       "fun"
     ),
     CallNode(13...25)(
       CallNode(13...16)(
         nil,
         nil,
         IDENTIFIER(13...16)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       COLON_COLON(16...18)("::"),
       CONSTANT(18...21)("Fun"),
       nil,
       ArgumentsNode(22...25)(
         [CallNode(22...25)(
            nil,
            nil,
            IDENTIFIER(22...25)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       nil,
       "Fun"
     ),
     CallNode(27...39)(
       CallNode(27...30)(
         nil,
         nil,
         IDENTIFIER(27...30)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       COLON_COLON(30...32)("::"),
       IDENTIFIER(36...39)("bar"),
       nil,
       ArgumentsNode(36...39)(
         [CallNode(36...39)(
            nil,
            nil,
            IDENTIFIER(36...39)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       nil,
       "bar"
     )]
  )
)
