ProgramNode(0...43)(
  ScopeNode(0...0)([]),
  StatementsNode(0...43)(
    [CallNode(0...14)(
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       DOT(3...4)("."),
       IDENTIFIER(4...7)("fun"),
       nil,
       ArgumentsNode(8...11)(
         [ParenthesesNode(8...11)(
            StatementsNode(9...10)([IntegerNode(9...10)()]),
            (8...9),
            (10...11)
          )]
       ),
       nil,
       BlockNode(12...14)(
         ScopeNode(12...13)([]),
         nil,
         nil,
         (12...13),
         (13...14)
       ),
       "fun"
     ),
     CallNode(16...31)(
       CallNode(16...19)(
         nil,
         nil,
         IDENTIFIER(16...19)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       COLON_COLON(19...21)("::"),
       BRACE_RIGHT(30...31)("}"),
       nil,
       ArgumentsNode(25...28)(
         [ParenthesesNode(25...28)(
            StatementsNode(26...27)([IntegerNode(26...27)()]),
            (25...26),
            (27...28)
          )]
       ),
       nil,
       BlockNode(29...31)(
         ScopeNode(29...30)([]),
         nil,
         nil,
         (29...30),
         (30...31)
       ),
       "}"
     ),
     CallNode(33...43)(
       nil,
       nil,
       IDENTIFIER(33...36)("fun"),
       nil,
       ArgumentsNode(37...40)(
         [ParenthesesNode(37...40)(
            StatementsNode(38...39)([IntegerNode(38...39)()]),
            (37...38),
            (39...40)
          )]
       ),
       nil,
       BlockNode(41...43)(
         ScopeNode(41...42)([]),
         nil,
         nil,
         (41...42),
         (42...43)
       ),
       "fun"
     )]
  )
)
