ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [CallNode(0...8)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       nil,
       ArgumentsNode(4...8)(
         [ParenthesesNode(4...8)(
            StatementsNode(5...6)([IntegerNode(5...6)()]),
            (4...5),
            (7...8)
          )]
       ),
       nil,
       nil,
       "fun"
     )]
  )
)
