ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [CallNode(0...11)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       nil,
       ArgumentsNode(4...11)(
         [ParenthesesNode(4...11)(
            StatementsNode(5...10)(
              [CallNode(5...10)(
                 nil,
                 nil,
                 IDENTIFIER(5...6)("f"),
                 nil,
                 ArgumentsNode(7...10)(
                   [CallNode(7...10)(
                      nil,
                      nil,
                      IDENTIFIER(7...10)("bar"),
                      nil,
                      nil,
                      nil,
                      nil,
                      "bar"
                    )]
                 ),
                 nil,
                 nil,
                 "f"
               )]
            ),
            (4...5),
            (10...11)
          )]
       ),
       nil,
       nil,
       "fun"
     )]
  )
)
