ProgramNode(0...30)(
  ScopeNode(0...0)([]),
  StatementsNode(0...30)(
    [SuperNode(0...9)(
       KEYWORD_SUPER(0...5)("super"),
       nil,
       ArgumentsNode(6...9)(
         [CallNode(6...9)(
            nil,
            nil,
            IDENTIFIER(6...9)("foo"),
            nil,
            nil,
            nil,
            nil,
            "foo"
          )]
       ),
       nil,
       nil
     ),
     SuperNode(11...18)(
       KEYWORD_SUPER(11...16)("super"),
       PARENTHESIS_LEFT(16...17)("("),
       nil,
       PARENTHESIS_RIGHT(17...18)(")"),
       nil
     ),
     SuperNode(20...30)(
       KEYWORD_SUPER(20...25)("super"),
       PARENTHESIS_LEFT(25...26)("("),
       ArgumentsNode(26...29)(
         [CallNode(26...29)(
            nil,
            nil,
            IDENTIFIER(26...29)("foo"),
            nil,
            nil,
            nil,
            nil,
            "foo"
          )]
       ),
       PARENTHESIS_RIGHT(29...30)(")"),
       nil
     )]
  )
)
