ProgramNode(0...34)(
  ScopeNode(0...0)([]),
  StatementsNode(0...34)(
    [CaseNode(0...34)(
       CallNode(5...8)(
         nil,
         nil,
         IDENTIFIER(5...8)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       [WhenNode(10...29)(
          KEYWORD_WHEN(10...14)("when"),
          [StringNode(15...20)(
             STRING_BEGIN(15...16)("'"),
             STRING_CONTENT(16...19)("bar"),
             STRING_END(19...20)("'"),
             "bar"
           )],
          StatementsNode(26...29)(
            [CallNode(26...29)(
               nil,
               nil,
               IDENTIFIER(26...29)("bar"),
               nil,
               nil,
               nil,
               nil,
               "bar"
             )]
          )
        )],
       nil,
       (0...4),
       (31...34)
     )]
  )
)
