ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [XStringNode(0...8)(
       BACKTICK(0...1)("`"),
       STRING_CONTENT(1...7)("foobar"),
       STRING_END(7...8)("`"),
       "foobar"
     )]
  )
)
