#!/usr/bin/env ruby


$LOAD_PATH << File.join(__dir__, "../lib")
require "lrama"

grammar_file = ARGV.shift
y = File.read(grammar_file)
warning = Lrama::Warning.new
grammar = Lrama::Parser.new(y).parse
states = Lrama::States.new(grammar, warning)
states.compute

Lrama::LexState.new(states).compute
