module Prism
  class Compiler
    include _Visitor

    def visit: (Prism::node?) -> untyped
    def visit_all: (Array[Prism::node?]) -> untyped
    def visit_child_nodes: (Prism::node) -> void
  end
end
