<?xml version="1.0" encoding="utf-8"?>
<definitions
    name="foo"
    targetNamespace="urn:foo"
    xmlns:tns="urn:foo"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema elementFormDefault="unqualified" targetNamespace="urn:foo">
      <xsd:element name="get_foo">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" maxOccurs="1" name="number" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>

  <message name="get_foo_in">
    <part name="parameters" element="tns:get_foo" />
  </message>
  <message name="get_foo_out">
    <part name="parameters" type="xsd:string" />
  </message>

  <portType name="foo_porttype">
    <operation name="get_foo">
      <input message="tns:get_foo_in" />
      <output message="tns:get_foo_out" />
    </operation>
  </portType>

  <binding name="foo_binding" type="tns:foo_porttype">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
        style="document" />
    <operation name="get_foo">
      <soap:operation soapAction="urn:foo:get_foo" style="document" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>

  <service name="foo_service">
    <port name="foo_service_port" binding="tns:foo_binding">
      <soap:address location="http://localhost:17171/" />
    </port>
  </service>
</definitions>
