exclude(:test_blocking_mutex_unlocked_on_fork, "fork")
exclude(:test_fork_in_thread, "fork")
exclude(:test_fork_value, "fork")
exclude(:test_fork_while_locked, "fork")
exclude(:test_fork_while_parent_locked, "fork")
exclude(:test_fork_while_mutex_locked_by_forker, "fork")
exclude(:test_join_limit_, "ractor incompatible")
exclude(:test_local_barrier, "gvars")
exclude(:test_thread_native_thread_id_across_fork_on_linux, "fork")
exclude(:test_thread_timer_and_ensure, "ractor incompatible")
exclude(:test_subclass_no_initialize, "global side effects")
exclude(:test_inspect, "global side effects")
