exclude(:test_attr_obsoleted_flag, "class ivars")
exclude(:test_attr_public_at_toplevel, "TOPLEVEL_BINDING")
exclude(:test_class_eval, "class variable access")
exclude(:test_class_variable_defined, "class vars")
exclude(:test_class_variable_get, "class vars")
exclude(:test_class_variable_in_dup_class, "class vars")
exclude(:test_class_variable_set, "class vars")
exclude(:test_class_variables, "class vars")
exclude(:test_remove_class_variable, "class vars")
exclude(:test_const_added, "class ivars")
exclude(:test_const_defined_invalid_symbol_name, "EnvUtil.under_gc_stress")
exclude(:test_const_set, "class ivars")
exclude(:test_extend_module_with_protected_method, "class ivars")
exclude(:test_initialize_copy_empty, "class ivars")
exclude(:test_module_subclass_initialize, "class ivars")
exclude(:test_private_constant_const_missing, "class ivars")
exclude(:test_private_constant_reopen, "TOPLEVEL_BINDING")
exclude(:test_s_constants, "global side effects")
exclude(:test_s_nesting, "global variable access")
exclude(:test_uninitialized_attr_class, "class ivars")
exclude(:test_uninitialized_toplevel_constant, "TOPLEVEL_BINDING")
exclude(:test_nested_get, "global side effects")
exclude(:test_nested_get_symbol, "global side effects")
exclude(:test_nested_defined, "global side effects")
exclude(:test_nested_defined_symbol, "global side effects")
exclude(:test_deprecate_constant, "Warning[]=")
exclude(:test_dup, "global side effects")
exclude(:test_module_exec, "global side effects")
exclude(:test_module_eval, "global side effects")
