exclude(:test_kernel_warn_uplevel, "uses capture_warning_warn")
exclude(:test_thread_signal_location, "subprocess")
exclude(:test_warn_deprecated_backwards_compatibility_category, "ractor incompatible")
exclude(:test_warning_warn, "ractor incompatible")
exclude(:test_warning_warn_circular_require_backtrace, "ractor incompatible")
exclude(:test_warning_category, "global side effects")
exclude(:test_type_error_message_encoding, "global side effects")
exclude(:test_too_many_args_in_eval, "TODO: freezes process")
exclude(:test_catch_throw_in_require, "Tempfile")
exclude(:test_catch_throw_in_require_cant_be_rescued, "Tempfile")
exclude(:test_detailed_message_under_gc_compact_stress, "EnvUtil.under_gc_compact_stress")
