exclude(/_with_callcc$/, "ractor incompatible")
exclude(:test_join, "Uses $,")
exclude(:test_to_s, "Uses $,")
exclude(:test_equal_resize, "global variables")
exclude(:test_replace_wb_variable_width_alloc, "GC.verify_internal_consistency")
exclude(:test_concat_under_gc_stress, "EnvUtil.under_gc_stress")
exclude(:test_product_under_gc_stress, "EnvUtil.under_gc_stress")
exclude(:test_to_h_single_element_with_object, "global side effects")
exclude(:test_to_h_block_single_element_with_object, "global side effects")
