exclude(:test_cvar_scope_with_instance_eval, "ractor incompatible")
exclude(:test_define_method_toplevel, "ractor incompatible")
exclude(:test_eval_with_toplevel_binding, "ractor incompatible")
exclude(:test_fixnum_instance_eval_cvar, "ractor incompatible")
exclude(:test_instance_eval_cvar, "ractor incompatible")
exclude(:test_instance_eval_method, "ractor incompatible")
exclude(:test_instance_exec_cvar, "ractor incompatible")
exclude(:test_instance_eval_on_argf_singleton_class, "ractor incompatible")
exclude(:test_nil_instance_eval_cvar, "ractor incompatible")
exclude(:test_eval_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_eval_binding_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_module_eval_string_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_module_eval_block_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_instance_eval_string_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_instance_eval_block_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_instance_exec_block_basic_ractor_unsafe, "cvars and gvars")
exclude(:test_eval_orig_ractor_unsafe, "global side effects")
