exclude(:test_chomp, "gvars")
exclude(:test_chomp!, "gvars")
exclude(:test_crypt_no_memory_leak, "assert_no_memory_leak, may as well skip")
exclude(:test_each, "gvars")
exclude(:test_each_line, "gvars")
exclude(:test_fs, "gvars")
exclude(:test_split, "gvars")
exclude(:test_split_with_block, "gvars")
exclude(:test_string_interpolations_across_heaps_get_embedded, "ObjectSpace.dump")
exclude(:test_uminus_frozen, "unpredictable")
exclude(:test_uplus_minus_ractor_unsafe, "ObjectSpace.dump")
exclude(:test_chilled_string_setivar, "global side effects (Warning[]=)")
exclude(:test_chilled_string_substring, "global side effects (Warning[]=)")
