exclude(:test_constant, "global side effects")
exclude(:test_constant_cache3, "global variable access")
exclude(:test_constant_cache4, "global variable access")
exclude(:test_constant_cache5, "global variable access")
exclude(:test_cvar_from_instance_method, "class variables")
exclude(:test_cvar_from_singleton_method, "class variables")
exclude(:test_cvar_from_singleton_method2, "class variables")
exclude(:test_gvar, "global variable access")
exclude(:test_opassign_ractor_unsafe, "cvars and gvars")
