exclude(:test_expand_path_compose, "Dir.chdir")
exclude(:test_expand_path_home, "global side effects")
exclude(:test_expand_path_home_dir_string, "global side effects")
exclude(:test_expand_path_memsize, "ObjectSpace.memsize_of")
exclude(:test_expand_path_encoding_filesystem, "global side effects")
exclude(:test_expand_path_error_for_non_absolute_home, "global side effects")
exclude(:test_expand_path_converts_a_pathname_to_an_absolute_pathname_using_home_as_base, "global side effects")
exclude(:test_expand_path_converts_a_pathname_to_an_absolute_pathname_using_unc_home, "global side effects")
exclude(:test_expand_path_does_not_modify_a_home_string_argument, "global side effects")
exclude(:test_flock_exclusive, "subprocess")
exclude(:test_flock_shared, "subprocess")
exclude(:test_stat_dotted_prefix_ractor_unsafe, "Dir.chdir")
exclude(:test_utime_ractor_unsafe, "Dir.chdir")
exclude(:test_umask, "global side effects")
