exclude(:test__fork, "fork")
exclude(:test__fork_pid_cache, "fork")
exclude(:test_argv0_frozen, "gvars")
exclude(:test_concurrent_group_and_pid_wait, "Timeout.timeout")
exclude(:test_daemon_default, "fork")
exclude(:test_daemon_detached, "fork")
exclude(:test_daemon_no_threads, "fork")
exclude(:test_daemon_nochdir_noclose, "fork")
exclude(:test_daemon_noclose, "fork")
exclude(:test_daemon_pid, "fork")
exclude(:test_daemon_readwrite, "fork")
exclude(/test_execopts_env_popen/, "ENV changes")
exclude(:test_execopts_redirect_tempfile, "Tempfile")
exclude(:test_popen_fork, "fork")
exclude(:test_popen_fork_ensure, "fork")
exclude(:test_execopts_env_popen, "ENV changes")
exclude(:test_execopts_unsetenv_others, "ENV changes")
exclude(:test_process_detach, "fork")
exclude(:test_seteuid_name, "unsafe Etc method")
exclude(:test_signals_work_after_exec_fail, "Timeout.timeout")
exclude(:test_system_sigpipe, "Timeout.timeout")
exclude(:test_threading_works_after_exec_fail, "Timeout.timeout")
exclude(:test_to_hash_on_arguments, "separate processes")
exclude(:test_waitall, "global side effects")
exclude(:test_uid_from_name_ractor_unsafe, "Etc.getpwuid")
exclude(:test_gid_from_name_ractor_unsafe, "Etc.getgrgid")
