exclude(:test_load, "Tempfile")
exclude(:test_load_error_path, "Tempfile")
exclude(:test_load_into_module, "Tempfile")
exclude(:test_load_scope, "Tempfile")
exclude(:test_loaded_features_encoding, "gvars")
exclude(:test_loading_fifo_fd_leak, "Tempfile")
exclude(:test_loading_fifo_threading_raise, "Tempfile")
exclude(:test_loading_fifo_threading_success, "Tempfile")
exclude(:test_private_in_wrapped_load, "Tempfile")
exclude(:test_provide_in_required_file, "gvars")
exclude(:test_public_in_wrapped_load, "Tempfile")
exclude(:test_race_exception, "Tempfile")
exclude(:test_relative, "gvars")
exclude(:test_relative_symlink, "Dir.chdir")
exclude(:test_relative_symlink_realpath, "Dir.chdir")
exclude(:test_require_invalid_shared_object, "Tempfile")
exclude(:test_require_twice, "ractor incompatible")
exclude(:test_require_with_loaded_features_pop, "Tempfile")
exclude(:test_require_with_unc, "Tempfile")
exclude(:test_resolve_feature_path, "gvars")
exclude(:test_resolve_feature_path_with_missing_feature, "$LOAD_PATH")
exclude(:test_require_nonascii_path, "$LOAD_PATH")
exclude(:test_require_nonascii_path_utf8, "$LOAD_PATH")
exclude(:test_require_nonascii_path_shift_jis, "$LOAD_PATH")
exclude(:test_throw_while_loading, "Tempfile")
exclude(:test_require_path_home_1, "global side effects")
exclude(:test_require_path_home_2, "global side effects")
exclude(:test_require_path_home_3, "global side effects")
exclude(:test_require_syntax_error, "$LOADED_FEATURES")
exclude(:test_require_syntax_error_rescued, "$LOADED_FEATURES")
exclude(:test_load_syntax_error, "$LOADED_FEATURES")
exclude(:test_require_changed_current_dir, "Dir.chdir")
exclude(:test_require_changed_home, "Dir.chdir")
exclude(:test_require_to_path_redefined_in_load_path, "Dir.chdir")
exclude(:test_require_not_modified_load_path, "Dir.chdir")
exclude(:test_require_to_str_redefined_in_load_path, "Dir.chdir")
exclude(:test_require_with_array_pop, "Dir.chdir")
exclude(:test_require_with_array_shift, "Dir.chdir")
exclude(:test_require_local_var_on_toplevel, "Dir.chdir")
exclude(:test_bug_21568, "$LOADED_FEATURES")
