exclude(:test_binmode_pipe, "global side effects")
exclude(:test_advise_pipe, "ractor incompatible")
exclude(:test_autoclose_false_closed_by_finalizer, "Tempfile")
exclude(:test_autoclose_true_closed_by_finalizer, "Tempfile")
exclude(:test_autoclose, "TODO: assert_raise buggy")
exclude(:test_copy_stream_dup_buffer, "Tempfile")
exclude(:test_copy_stream_no_busy_wait, "unpredictable")
exclude(:test_copy_stream_socket7, "fork")
exclude(:test_copy_stream_strio_to_tempfile, "Tempfile")
exclude(:test_fcntl_dupfd, "Tempfile")
exclude(:test_fcntl_lock_freebsd, "Tempfile + fork")
exclude(:test_fcntl_lock_linux, "Tempfile + fork")
exclude(:test_flush_in_finalizer1, "Tempfile + ObjectSpace.each_object")
exclude(:test_flush_in_finalizer2, "Tempfile + ObjectSpace.each_object")
exclude(:test_pid_after_close_read, "TODO: buggy")
exclude(:test_print_separators, "global variable access")
exclude(:test_race_between_read, "Tempfile")
exclude(:test_readline_limit_without_separator, "Tempfile")
exclude(:test_readline_separators_limits, "Tempfile")
exclude(:test_set_lineno_gets, "global variable access")
exclude(:test_set_lineno_readline, "global variable access")
exclude(:test_threaded_flush, "subprocesses")
exclude(:test_try_convert, "uses STDOUT")
exclude(:test_close_read_write_separately, "TODO: buggy with ractors")
exclude(:test_exception_at_close, "TODO: assert_raise sometimes fails under multiple ractors")
exclude(:test_std_fileno_ractor_unsafe, "unshareable objects")
exclude(/buffer_not_raise_shared_string_error/, "Tempfile")
