exclude(:test_cloned_allows_setting_cvar, "cvars")
exclude(:test_cloned_classes_copy_cvar_cache, "cvars")
exclude(:test_cvar_overtaken_by_module, "cvars")
exclude(:test_cvar_overtaken_by_parent_class, "cvars")
exclude(:test_global_variable_popped, "gvars")
exclude(:test_global_variables, "gvars")
exclude(:test_include_refined_module_class_variable, "cvars")
exclude(:test_remove_instance_variables_class, "class ivars")
exclude(:test_set_class_variable_on_frozen_object, "cvars")
exclude(:test_setting_class_variable_on_module_through_inheritance, "cvars")
exclude(:test_singleton_class_included_class_variable, "cvars")
exclude(:test_variable, "cvars")
